In [11]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [12]:
result_path = Path("../results/downstream_task")
# bias_types = ["less_negative_class", "less_positive_class", "mean_difference"]
bias_types = ["less_positive_class"]
metrics = ["AUROC", "AUPRC"]
less_bias_strengths = ["0.1"]
mean_bias_strengthts = ["0.8"]
method_name_replacer = {"uniform": "Uniform", "kmm": "KMM", "psa": "PSA", "mrs-forest": "MRS",
                            # "soft-mrs-exponential": "Soft-MRS-Exponential",
                               "mrs-forest": "MRS", 
                       # "fw-mrs-temperature-svm": "FW-MRS-SVM", 
                        "fw-mrs-temperature": "FW-MRS",
                        "fw-mrs-temperature-negative": "FW-MRS$_{Neg}$",
                          }
data_set_replacer = {"folktables_employment": "Employment", "folktables_income": "Income",
                               "breast_cancer": "Breast Cancer", "hr_analytics": "HR Analytic", "loan_prediction": "Loan",
                               "diabetes": "Diabetes", "german_credit": "German Credit", "bank_marketing": "Bank Marketing"}

In [13]:
aurocs = []
auprcs = []
dict_list = []
for dataset in data_set_replacer.keys():
    for bias_type in bias_types:
        for method in method_name_replacer.keys():
            if bias_type == "mean_difference":
                bias_strengths = mean_bias_strengthts
            else : 
                bias_strengths = less_bias_strengths
            for bias_strength in bias_strengths:
                json_file = result_path / dataset / bias_type /  bias_strength/ method / "classification_results.json"
                try:
                    result_file = pd.read_json(str(json_file))
                except FileNotFoundError:
                    continue
                dict_list.append(
                    {
                        "Method": method, "Data Set": dataset, 
                        "AUROC Mean": result_file["random forest auroc"]["mean"], 
                        "AUROC Std": result_file["random forest auroc"]["sd"], 
                        "AUPRC Mean": result_file["random forest auprc"]["mean"], 
                        "AUPRC Std": result_file["random forest auprc"]["sd"], 
                        "Bias Type": bias_type, "Bias Strength": bias_strength,
                        "Dropped Samples Mean": result_file["dropped_samples"]["mean"],
                        "Dropped Samples Std": result_file["dropped_samples"]["std"]
                    }
                                )
result_df = pd.DataFrame(data=dict_list)

In [14]:
result_df = result_df.replace(method_name_replacer)
result_df

,Method,Data Set,AUROC Mean,AUROC Std,AUPRC Mean,AUPRC Std,Bias Type,Bias Strength,Dropped Samples Mean,Dropped Samples Std
0,Uniform,folktables_employment,0.870601,0.010491,0.826992,0.017307,less_positive_class,0.1,0.000000,0.000000
1,KMM,folktables_employment,0.856910,0.012538,0.809240,0.020048,less_positive_class,0.1,0.000000,0.000000
2,PSA,folktables_employment,0.867229,0.011378,0.823210,0.017361,less_positive_class,0.1,0.020000,0.140000
3,MRS,folktables_employment,0.869439,0.010185,0.825394,0.016376,less_positive_class,0.1,283.100000,114.960384
4,FW-MRS,folktables_employment,0.864510,0.011807,0.819362,0.018359,less_positive_class,0.1,378.400000,89.595982
5,FW-MRS$_{Neg}$,folktables_employment,0.874457,0.009650,0.831544,0.015783,less_positive_class,0.1,296.914894,102.415264
6,Uniform,folktables_income,0.838084,0.012878,0.788634,0.020309,less_positive_class,0.1,0.000000,0.000000
7,KMM,folktables_income,0.819722,0.014641,0.764636,0.020496,less_positive_class,0.1,0.000000,0.000000
8,PSA,folktables_income,0.831327,0.012480,0.781005,0.019604,less_positive_class,0.1,0.020000,0.140000
9,MRS,folktables_income,0.837534,0.012058,0.788396,0.018049,less_positive_class,0.1,267.600000,93.065783
10,FW-MRS,folktables_income,0.833814,0.013552,0.785426,0.020318,less_positive_class,0.1,277.200000,87.722061
11,FW-MRS$_{Neg}$,folktables_income,0.837393,0.012479,0.786446,0.019375,less_positive_class,0.1,271.900000,73.436299
12,Uniform,breast_cancer,0.987591,0.006273,0.993799,0.003288,less_positive_class,0.1,0.000000,0.000000
13,KMM,breast_cancer,0.989295,0.005433,0.994710,0.002723,less_positive_class,0.1,0.000000,0.000000
14,PSA,breast_cancer,0.987893,0.006442,0.994015,0.003248,less_positive_class,0.1,0.000000,0.000000
15,MRS,breast_cancer,0.989370,0.005493,0.994989,0.002489,less_positive_class,0.1,61.460000,3.811614
16,FW-MRS,breast_cancer,0.987224,0.006237,0.993717,0.003263,less_positive_class,0.1,52.960000,6.590781
17,FW-MRS$_{Neg}$,breast_cancer,0.986913,0.003776,0.993620,0.001852,less_positive_class,0.1,52.300000,7.681797
18,Uniform,hr_analytics,0.752772,0.018290,0.455071,0.029285,less_positive_class,0.1,0.000000,0.000000
19,KMM,hr_analytics,0.749002,0.019434,0.448185,0.032729,less_positive_class,0.1,0.000000,0.000000
20,PSA,hr_analytics,0.751383,0.018162,0.454841,0.032244,less_positive_class,0.1,0.000000,0.000000
21,MRS,hr_analytics,0.751748,0.019214,0.452949,0.032516,less_positive_class,0.1,102.900000,49.407388
22,FW-MRS,hr_analytics,0.751094,0.018895,0.452212,0.034181,less_positive_class,0.1,111.600000,55.203623
23,FW-MRS$_{Neg}$,hr_analytics,0.748607,0.019764,0.448754,0.035796,less_positive_class,0.1,106.900000,42.671888
24,Uniform,loan_prediction,0.658389,0.080697,0.794671,0.050524,less_positive_class,0.1,0.000000,0.000000
25,KMM,loan_prediction,0.607083,0.094867,0.774866,0.060109,less_positive_class,0.1,0.000000,0.000000
26,PSA,loan_prediction,0.627560,0.095193,0.780323,0.058087,less_positive_class,0.1,0.000000,0.000000
27,MRS,loan_prediction,0.643460,0.088463,0.792112,0.053565,less_positive_class,0.1,8.480000,5.231596
28,FW-MRS,loan_prediction,0.623944,0.088692,0.781456,0.058525,less_positive_class,0.1,5.060000,4.149265
29,FW-MRS$_{Neg}$,loan_prediction,0.672877,0.088862,0.801040,0.059406,less_positive_class,0.1,9.720000,5.295432
30,Uniform,diabetes,0.791498,0.022072,0.371281,0.037717,less_positive_class,0.1,0.000000,0.000000
31,KMM,diabetes,0.779991,0.023522,0.356094,0.043511,less_positive_class,0.1,0.000000,0.000000
32,PSA,diabetes,0.787610,0.022154,0.366169,0.037045,less_positive_class,0.1,0.000000,0.000000
33,MRS,diabetes,0.789972,0.023758,0.367945,0.038361,less_positive_class,0.1,49.400000,32.521378
34,FW-MRS,diabetes,0.787696,0.022278,0.365354,0.038042,less_positive_class,0.1,41.300000,29.168648
35,FW-MRS$_{Neg}$,diabetes,0.786245,0.026559,0.364790,0.040879,less_positive_class,0.1,59.100000,30.833261
36,Uniform,german_credit,0.667239,0.053736,0.460906,0.064090,less_positive_class,0.1,0.000000,0.000000
37,KMM,german_credit,0.644018,0.049244,0.436716,0.061674,less_positive_class,0.1,0.000000,0.000000
38,PSA,german_credit,0.662777,0.053089,0.457506,0.063577,less_positive_class,0.1,0.000000,0.000000
39,MRS,german_credit,0.668430,0.051887,0.461986,0.063911,less_positive_class,0.1,14.000000,11.532563
40,FW-MRS,german_credit,0.655887,0.062202,0.447350,0.067879,less_positive_class,0.1,11.600000,10.316976
41,FW-MRS$_{Neg}$,german_credit,0.666668,0.054945,0.456374,0.061602,less_positive_class,0.1,17.800000,10.870143
42,Uniform,bank_marketing,0.846908,0.021440,0.465787,0.051725,less_positive_class,0.1,0.000000,0.000000
43,KMM,bank_marketing,0.828878,0.029112,0.441257,0.058968,less_positive_class,0.1,0.000000,0.000000
44,PSA,bank_marketing,0.838104,0.026760,0.452609,0.052087,less_positive_class,0.1,0.000000,0.000000
45,MRS,bank_marketing,0.843901,0.022132,0.468323,0.052949,less_positive_class,0.1,68.200000,32.027488
46,FW-MRS,bank_marketing,0.838275,0.025422,0.454864,0.051325,less_positive_class,0.1,68.700000,39.291348
47,FW-MRS$_{Neg}$,bank_marketing,0.850318,0.022160,0.469194,0.050410,less_positive_class,0.1,68.600000,36.083791

In [15]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_auroc_values = []
            std_auroc_values = []
            for method in result_df["Method"].unique():
                try:
                    mean_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUROC Mean"].iloc[0]
                    mean_auroc_values.append(np.round(mean_auroc, 3))

                    std_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUROC Std"].iloc[0]
                    std_auroc_values.append(np.round(std_auroc, 2))
                except IndexError:
                    mean_auroc_values.append(0)
                    std_auroc_values.append(0)

            print(f"{data_set_replacer[dataset]} \
& ${mean_auroc_values[0]}\\pm{std_auroc_values[0]}$ \
& ${mean_auroc_values[1]}\\pm{std_auroc_values[1]}$ \
& ${mean_auroc_values[2]}\\pm{std_auroc_values[2]}$ \
& ${mean_auroc_values[3]}\\pm{std_auroc_values[3]}$ \
& ${mean_auroc_values[4]}\\pm{std_auroc_values[4]}$ \
& ${mean_auroc_values[5]}\\pm{std_auroc_values[5]}$ \
\\\\")
        print("\n")

less_positive_class, 0.1
Employment & $0.871\pm0.01$ & $0.857\pm0.01$ & $0.867\pm0.01$ & $0.869\pm0.01$ & $0.865\pm0.01$ & $0.874\pm0.01$ \\
Income & $0.838\pm0.01$ & $0.82\pm0.01$ & $0.831\pm0.01$ & $0.838\pm0.01$ & $0.834\pm0.01$ & $0.837\pm0.01$ \\
Breast Cancer & $0.988\pm0.01$ & $0.989\pm0.01$ & $0.988\pm0.01$ & $0.989\pm0.01$ & $0.987\pm0.01$ & $0.987\pm0.0$ \\
HR Analytic & $0.753\pm0.02$ & $0.749\pm0.02$ & $0.751\pm0.02$ & $0.752\pm0.02$ & $0.751\pm0.02$ & $0.749\pm0.02$ \\
Loan & $0.658\pm0.08$ & $0.607\pm0.09$ & $0.628\pm0.1$ & $0.643\pm0.09$ & $0.624\pm0.09$ & $0.673\pm0.09$ \\
Diabetes & $0.791\pm0.02$ & $0.78\pm0.02$ & $0.788\pm0.02$ & $0.79\pm0.02$ & $0.788\pm0.02$ & $0.786\pm0.03$ \\
German Credit & $0.667\pm0.05$ & $0.644\pm0.05$ & $0.663\pm0.05$ & $0.668\pm0.05$ & $0.656\pm0.06$ & $0.667\pm0.05$ \\
Bank Marketing & $0.847\pm0.02$ & $0.829\pm0.03$ & $0.838\pm0.03$ & $0.844\pm0.02$ & $0.838\pm0.03$ & $0.85\pm0.02$ \\

In [16]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_auprc_values = []
            std_auprc_values = []
            for method in result_df["Method"].unique():
                try:
                    mean_auprc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUPRC Mean"].iloc[0]
                    mean_auprc_values.append(np.round(mean_auprc, 3))

                    std_auprc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUPRC Std"].iloc[0]
                    std_auprc_values.append(np.round(std_auprc, 2))
                except IndexError:
                    mean_auprc_values.append(0)
                    std_auprc_values.append(0)

            print(f"{data_set_replacer[dataset]} \
& ${mean_auprc_values[0]}\\pm{std_auprc_values[0]}$ \
& ${mean_auprc_values[1]}\\pm{std_auprc_values[1]}$ \
& ${mean_auprc_values[2]}\\pm{std_auprc_values[2]}$ \
& ${mean_auprc_values[3]}\\pm{std_auprc_values[3]}$ \
& ${mean_auprc_values[4]}\\pm{std_auprc_values[4]}$ \
& ${mean_auprc_values[5]}\\pm{std_auprc_values[5]}$ \
& \\\\")
        print("\n")

less_positive_class, 0.1
Employment & $0.827\pm0.02$ & $0.809\pm0.02$ & $0.823\pm0.02$ & $0.825\pm0.02$ & $0.819\pm0.02$ & $0.832\pm0.02$ & \\
Income & $0.789\pm0.02$ & $0.765\pm0.02$ & $0.781\pm0.02$ & $0.788\pm0.02$ & $0.785\pm0.02$ & $0.786\pm0.02$ & \\
Breast Cancer & $0.994\pm0.0$ & $0.995\pm0.0$ & $0.994\pm0.0$ & $0.995\pm0.0$ & $0.994\pm0.0$ & $0.994\pm0.0$ & \\
HR Analytic & $0.455\pm0.03$ & $0.448\pm0.03$ & $0.455\pm0.03$ & $0.453\pm0.03$ & $0.452\pm0.03$ & $0.449\pm0.04$ & \\
Loan & $0.795\pm0.05$ & $0.775\pm0.06$ & $0.78\pm0.06$ & $0.792\pm0.05$ & $0.781\pm0.06$ & $0.801\pm0.06$ & \\
Diabetes & $0.371\pm0.04$ & $0.356\pm0.04$ & $0.366\pm0.04$ & $0.368\pm0.04$ & $0.365\pm0.04$ & $0.365\pm0.04$ & \\
German Credit & $0.461\pm0.06$ & $0.437\pm0.06$ & $0.458\pm0.06$ & $0.462\pm0.06$ & $0.447\pm0.07$ & $0.456\pm0.06$ & \\
Bank Marketing & $0.466\pm0.05$ & $0.441\pm0.06$ & $0.453\pm0.05$ & $0.468\pm0.05$ & $0.455\pm0.05$ & $0.469\pm0.05$ & \\

In [17]:
result_df.round(3)

,Method,Data Set,AUROC Mean,AUROC Std,AUPRC Mean,AUPRC Std,Bias Type,Bias Strength,Dropped Samples Mean,Dropped Samples Std
0,Uniform,folktables_employment,0.871,0.010,0.827,0.017,less_positive_class,0.1,0.000,0.000
1,KMM,folktables_employment,0.857,0.013,0.809,0.020,less_positive_class,0.1,0.000,0.000
2,PSA,folktables_employment,0.867,0.011,0.823,0.017,less_positive_class,0.1,0.020,0.140
3,MRS,folktables_employment,0.869,0.010,0.825,0.016,less_positive_class,0.1,283.100,114.960
4,FW-MRS,folktables_employment,0.865,0.012,0.819,0.018,less_positive_class,0.1,378.400,89.596
5,FW-MRS$_{Neg}$,folktables_employment,0.874,0.010,0.832,0.016,less_positive_class,0.1,296.915,102.415
6,Uniform,folktables_income,0.838,0.013,0.789,0.020,less_positive_class,0.1,0.000,0.000
7,KMM,folktables_income,0.820,0.015,0.765,0.020,less_positive_class,0.1,0.000,0.000
8,PSA,folktables_income,0.831,0.012,0.781,0.020,less_positive_class,0.1,0.020,0.140
9,MRS,folktables_income,0.838,0.012,0.788,0.018,less_positive_class,0.1,267.600,93.066
10,FW-MRS,folktables_income,0.834,0.014,0.785,0.020,less_positive_class,0.1,277.200,87.722
11,FW-MRS$_{Neg}$,folktables_income,0.837,0.012,0.786,0.019,less_positive_class,0.1,271.900,73.436
12,Uniform,breast_cancer,0.988,0.006,0.994,0.003,less_positive_class,0.1,0.000,0.000
13,KMM,breast_cancer,0.989,0.005,0.995,0.003,less_positive_class,0.1,0.000,0.000
14,PSA,breast_cancer,0.988,0.006,0.994,0.003,less_positive_class,0.1,0.000,0.000
15,MRS,breast_cancer,0.989,0.005,0.995,0.002,less_positive_class,0.1,61.460,3.812
16,FW-MRS,breast_cancer,0.987,0.006,0.994,0.003,less_positive_class,0.1,52.960,6.591
17,FW-MRS$_{Neg}$,breast_cancer,0.987,0.004,0.994,0.002,less_positive_class,0.1,52.300,7.682
18,Uniform,hr_analytics,0.753,0.018,0.455,0.029,less_positive_class,0.1,0.000,0.000
19,KMM,hr_analytics,0.749,0.019,0.448,0.033,less_positive_class,0.1,0.000,0.000
20,PSA,hr_analytics,0.751,0.018,0.455,0.032,less_positive_class,0.1,0.000,0.000
21,MRS,hr_analytics,0.752,0.019,0.453,0.033,less_positive_class,0.1,102.900,49.407
22,FW-MRS,hr_analytics,0.751,0.019,0.452,0.034,less_positive_class,0.1,111.600,55.204
23,FW-MRS$_{Neg}$,hr_analytics,0.749,0.020,0.449,0.036,less_positive_class,0.1,106.900,42.672
24,Uniform,loan_prediction,0.658,0.081,0.795,0.051,less_positive_class,0.1,0.000,0.000
25,KMM,loan_prediction,0.607,0.095,0.775,0.060,less_positive_class,0.1,0.000,0.000
26,PSA,loan_prediction,0.628,0.095,0.780,0.058,less_positive_class,0.1,0.000,0.000
27,MRS,loan_prediction,0.643,0.088,0.792,0.054,less_positive_class,0.1,8.480,5.232
28,FW-MRS,loan_prediction,0.624,0.089,0.781,0.059,less_positive_class,0.1,5.060,4.149
29,FW-MRS$_{Neg}$,loan_prediction,0.673,0.089,0.801,0.059,less_positive_class,0.1,9.720,5.295
30,Uniform,diabetes,0.791,0.022,0.371,0.038,less_positive_class,0.1,0.000,0.000
31,KMM,diabetes,0.780,0.024,0.356,0.044,less_positive_class,0.1,0.000,0.000
32,PSA,diabetes,0.788,0.022,0.366,0.037,less_positive_class,0.1,0.000,0.000
33,MRS,diabetes,0.790,0.024,0.368,0.038,less_positive_class,0.1,49.400,32.521
34,FW-MRS,diabetes,0.788,0.022,0.365,0.038,less_positive_class,0.1,41.300,29.169
35,FW-MRS$_{Neg}$,diabetes,0.786,0.027,0.365,0.041,less_positive_class,0.1,59.100,30.833
36,Uniform,german_credit,0.667,0.054,0.461,0.064,less_positive_class,0.1,0.000,0.000
37,KMM,german_credit,0.644,0.049,0.437,0.062,less_positive_class,0.1,0.000,0.000
38,PSA,german_credit,0.663,0.053,0.458,0.064,less_positive_class,0.1,0.000,0.000
39,MRS,german_credit,0.668,0.052,0.462,0.064,less_positive_class,0.1,14.000,11.533
40,FW-MRS,german_credit,0.656,0.062,0.447,0.068,less_positive_class,0.1,11.600,10.317
41,FW-MRS$_{Neg}$,german_credit,0.667,0.055,0.456,0.062,less_positive_class,0.1,17.800,10.870
42,Uniform,bank_marketing,0.847,0.021,0.466,0.052,less_positive_class,0.1,0.000,0.000
43,KMM,bank_marketing,0.829,0.029,0.441,0.059,less_positive_class,0.1,0.000,0.000
44,PSA,bank_marketing,0.838,0.027,0.453,0.052,less_positive_class,0.1,0.000,0.000
45,MRS,bank_marketing,0.844,0.022,0.468,0.053,less_positive_class,0.1,68.200,32.027
46,FW-MRS,bank_marketing,0.838,0.025,0.455,0.051,less_positive_class,0.1,68.700,39.291
47,FW-MRS$_{Neg}$,bank_marketing,0.850,0.022,0.469,0.050,less_positive_class,0.1,68.600,36.084

In [18]:
result_df["Rank AUROC"] = result_df.round(3).groupby("Data Set")["AUROC Mean"].rank(ascending=False)
result_df["Rank AUPRC"] = result_df.round(3).groupby("Data Set")["AUPRC Mean"].rank(ascending=False)
result_df[["Method", "Rank AUROC", "Rank AUPRC"]].groupby("Method").mean()

                Rank AUROC  Rank AUPRC
Method
FW-MRS              4.5000      4.3750
FW-MRS$_{Neg}$      3.0625      3.0000
KMM                 5.3750      5.4375
MRS                 2.1250      2.1875
PSA                 4.0000      3.8750
Uniform             1.9375      2.1250