In [74]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [75]:
result_path = Path("../results/decomposition")
# methods_list = ["uniform","psa", "kmm", "mrs-forest", "fw-mrs-temperature",  "fw-mrs-temperature-svm", "soft-mrs-linear", "soft-mrs-exponential"]
methods_list = ["uniform","psa", "kmm", "mrs-forest", "fw-mrs-temperature",  "fw-mrs-temperature-svm",]
# bias_types = ["less_negative_class", "less_positive_class", "mean_difference"]
bias_types = ["less_positive_class"]
# less_bias_strengths = ["0.1", "0.2", "0.3"]
less_bias_strengths = ["0.1"]
mean_bias_strengthts = ["0.8", "0.9"]
datasets = ["folktables_employment", "folktables_income", "hr_analytics", "breast_cancer", "loan_prediction"]

In [76]:
aurocs = []
auprcs = []
dict_list = []
for dataset in datasets:
    for bias_type in bias_types:
        for method in methods_list:
            if bias_type == "mean_difference":
                bias_strengths = mean_bias_strengthts
            else : 
                bias_strengths = less_bias_strengths
            for bias_strength in bias_strengths:
                json_file = result_path / dataset / bias_type /  bias_strength/ method / "bias_variance_decomposition.json"
                result_file = pd.read_json(str(json_file))
                dict_list.append(
                    {
                        "Method": method, "Data Set": dataset, 
                        "0-1 Bias": result_file["0-1 loss"]["average_bias"], 
                        "0-1 Variance": result_file["0-1 loss"]["average variance"], 
                        "0-1 Expexted Loss": result_file["0-1 loss"]["average expected loss"],
                        "MSE Bias": result_file["mse loss"]["average_bias"], 
                        "MSE Variance": result_file["mse loss"]["average variance"], 
                        "MSE Expexted Loss": result_file["mse loss"]["average expected loss"],
                        "Bias Type": bias_type, "Bias Strength": bias_strength,
                    }
                                )
result_df = pd.DataFrame(data=dict_list)

In [77]:
result_df = result_df.replace({"uniform": "Uniform", "kmm": "KMM", "psa": "PSA", "mrs-forest": "MRS",
                               "soft-mrs-linear": "Soft-MRS-Linear", "soft-mrs-exponential": "Soft-MRS-Exponential",
                               "fw-mrs-temperature-svm": "FW-MRS-SVM", "fw-mrs-temperature": "FW-MRS-RF"})
result_df

,Method,Data Set,0-1 Bias,0-1 Variance,0-1 Expexted Loss,MSE Bias,MSE Variance,MSE Expexted Loss,Bias Type,Bias Strength
0,Uniform,folktables_employment,0.459000,0.023730,0.441550,0.298388,0.006043,0.304431,less_positive_class,0.1
1,PSA,folktables_employment,0.459000,0.030460,0.436640,0.286891,0.006826,0.293717,less_positive_class,0.1
2,KMM,folktables_employment,0.459000,0.022640,0.442060,0.277505,0.005791,0.283296,less_positive_class,0.1
3,MRS,folktables_employment,0.459000,0.032320,0.435780,0.287949,0.007141,0.295090,less_positive_class,0.1
4,FW-MRS-RF,folktables_employment,0.459000,0.014630,0.449510,0.329163,0.005860,0.335023,less_positive_class,0.1
5,FW-MRS-SVM,folktables_employment,0.459000,0.000000,0.459000,0.362854,0.001043,0.363897,less_positive_class,0.1
6,Uniform,folktables_income,0.441000,0.014990,0.429690,0.313483,0.004985,0.318468,less_positive_class,0.1
7,PSA,folktables_income,0.441000,0.016870,0.428390,0.298089,0.005161,0.303250,less_positive_class,0.1
8,KMM,folktables_income,0.441000,0.012100,0.431320,0.287222,0.004226,0.291447,less_positive_class,0.1
9,MRS,folktables_income,0.441000,0.025010,0.421350,0.300217,0.006767,0.306984,less_positive_class,0.1
10,FW-MRS-RF,folktables_income,0.441000,0.013520,0.430820,0.330042,0.005524,0.335566,less_positive_class,0.1
11,FW-MRS-SVM,folktables_income,0.441000,0.000000,0.441000,0.360879,0.000798,0.361677,less_positive_class,0.1
12,Uniform,hr_analytics,0.165494,0.000322,0.165454,0.146324,0.000800,0.147124,less_positive_class,0.1
13,PSA,hr_analytics,0.165494,0.000389,0.165400,0.145956,0.000883,0.146839,less_positive_class,0.1
14,KMM,hr_analytics,0.165494,0.000402,0.165441,0.146218,0.000910,0.147128,less_positive_class,0.1
15,MRS,hr_analytics,0.165494,0.000342,0.165461,0.146306,0.000819,0.147124,less_positive_class,0.1
16,FW-MRS-RF,hr_analytics,0.165494,0.000348,0.165467,0.148625,0.000926,0.149551,less_positive_class,0.1
17,FW-MRS-SVM,hr_analytics,0.165494,0.000241,0.165441,0.150511,0.000818,0.151329,less_positive_class,0.1
18,Uniform,breast_cancer,0.035088,0.019123,0.045263,0.035101,0.004892,0.039993,less_positive_class,0.1
19,PSA,breast_cancer,0.035088,0.019561,0.043947,0.034155,0.004845,0.038999,less_positive_class,0.1
20,KMM,breast_cancer,0.035088,0.019123,0.044561,0.033752,0.004359,0.038110,less_positive_class,0.1
21,MRS,breast_cancer,0.039474,0.016754,0.039737,0.031049,0.004352,0.035401,less_positive_class,0.1
22,FW-MRS-RF,breast_cancer,0.039474,0.026053,0.050439,0.034004,0.007784,0.041788,less_positive_class,0.1
23,FW-MRS-SVM,breast_cancer,0.043860,0.030965,0.052895,0.034951,0.009922,0.044872,less_positive_class,0.1
24,Uniform,loan_prediction,0.693750,0.035750,0.666750,0.403742,0.011582,0.415324,less_positive_class,0.1
25,PSA,loan_prediction,0.693750,0.039250,0.664250,0.399697,0.012482,0.412178,less_positive_class,0.1
26,KMM,loan_prediction,0.693750,0.042375,0.666875,0.411745,0.014839,0.426584,less_positive_class,0.1
27,MRS,loan_prediction,0.693750,0.059500,0.655250,0.391085,0.015477,0.406561,less_positive_class,0.1
28,FW-MRS-RF,loan_prediction,0.693750,0.050625,0.656875,0.414764,0.016403,0.431167,less_positive_class,0.1
29,FW-MRS-SVM,loan_prediction,0.693750,0.044000,0.666750,0.432086,0.017495,0.449581,less_positive_class,0.1

In [78]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            bias_01_values = []
            for dataset in datasets:
                bias_01 = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["0-1 Bias"].iloc[0]
                bias_01_values.append(np.round(bias_01, 4))


            print(f"\t& {method} & {bias_01_values[0]} & {bias_01_values[1]} & {bias_01_values[2]} & {bias_01_values[3]} & {bias_01_values[4]} & \\\\")
        print("\n")

less_positive_class, 0.1
	& Uniform & 0.459 & 0.441 & 0.1655 & 0.0351 & 0.6938 & \\
	& PSA & 0.459 & 0.441 & 0.1655 & 0.0351 & 0.6938 & \\
	& KMM & 0.459 & 0.441 & 0.1655 & 0.0351 & 0.6938 & \\
	& MRS & 0.459 & 0.441 & 0.1655 & 0.0395 & 0.6938 & \\
	& FW-MRS-RF & 0.459 & 0.441 & 0.1655 & 0.0395 & 0.6938 & \\
	& FW-MRS-SVM & 0.459 & 0.441 & 0.1655 & 0.0439 & 0.6938 & \\

In [79]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            variance_01_values = []
            for dataset in datasets:
                variance_01 = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["0-1 Variance"].iloc[0]
                variance_01_values.append(np.round(variance_01, 4))

            print(f"\t& {method} & {variance_01_values[0]} & {variance_01_values[1]} & {variance_01_values[2]} & {variance_01_values[3]} & \
{variance_01_values[4]} & \\\\")
        print("\n")

less_positive_class, 0.1
	& Uniform & 0.0237 & 0.015 & 0.0003 & 0.0191 & 0.0358 & \\
	& PSA & 0.0305 & 0.0169 & 0.0004 & 0.0196 & 0.0392 & \\
	& KMM & 0.0226 & 0.0121 & 0.0004 & 0.0191 & 0.0424 & \\
	& MRS & 0.0323 & 0.025 & 0.0003 & 0.0168 & 0.0595 & \\
	& FW-MRS-RF & 0.0146 & 0.0135 & 0.0003 & 0.0261 & 0.0506 & \\
	& FW-MRS-SVM & 0.0 & 0.0 & 0.0002 & 0.031 & 0.044 & \\

In [80]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else: 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            bias_mse_values = []
            for dataset in datasets:
                bias_mse = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["MSE Bias"].iloc[0]
                bias_mse_values.append(np.round(bias_mse, 4))


            print(f"\t & {method} & {bias_mse_values[0]} & {bias_mse_values[1]} & {bias_mse_values[2]} & {bias_mse_values[3]} & {bias_mse_values[4]} & \\\\")
        print("\n")

less_positive_class, 0.1
	 & Uniform & 0.2984 & 0.3135 & 0.1463 & 0.0351 & 0.4037 & \\
	 & PSA & 0.2869 & 0.2981 & 0.146 & 0.0342 & 0.3997 & \\
	 & KMM & 0.2775 & 0.2872 & 0.1462 & 0.0338 & 0.4117 & \\
	 & MRS & 0.2879 & 0.3002 & 0.1463 & 0.031 & 0.3911 & \\
	 & FW-MRS-RF & 0.3292 & 0.33 & 0.1486 & 0.034 & 0.4148 & \\
	 & FW-MRS-SVM & 0.3629 & 0.3609 & 0.1505 & 0.035 & 0.4321 & \\

In [83]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else: 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            variance_mse_values = []
            for dataset in datasets:
                variance_mse = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["MSE Variance"].iloc[0]
                variance_mse_values.append(np.round(variance_mse, 4))

            print(f"\t & {method} & {variance_mse_values[0]} & {variance_mse_values[1]} & {variance_mse_values[2]} & {variance_mse_values[3]} & \
{variance_mse_values[4]} & \\\\")
        print("\n")

less_positive_class, 0.1
	 & Uniform & 0.006 & 0.005 & 0.0008 & 0.0049 & 0.0116 & \\
	 & PSA & 0.0068 & 0.0052 & 0.0009 & 0.0048 & 0.0125 & \\
	 & KMM & 0.0058 & 0.0042 & 0.0009 & 0.0044 & 0.0148 & \\
	 & MRS & 0.0071 & 0.0068 & 0.0008 & 0.0044 & 0.0155 & \\
	 & FW-MRS-RF & 0.0059 & 0.0055 & 0.0009 & 0.0078 & 0.0164 & \\
	 & FW-MRS-SVM & 0.001 & 0.0008 & 0.0008 & 0.0099 & 0.0175 & \\

In [98]:
result_df["Rank Bias"] = result_df.groupby("Data Set")["0-1 Bias"].rank(ascending=True)
result_df["Rank Variance"] = result_df.groupby("Data Set")["0-1 Variance"].rank(ascending=True)
result_df[["Method", "Rank Bias", "Rank Variance"]].groupby("Method").mean()

            Rank Bias  Rank Variance
Method
FW-MRS-RF         3.7            3.8
FW-MRS-SVM        4.0            2.6
KMM               3.2            3.3
MRS               3.7            4.4
PSA               3.2            4.2
Uniform           3.2            2.7

In [101]:
result_df["Rank Bias"] = result_df.groupby("Data Set")["MSE Bias"].rank(ascending=True)
result_df["Rank Variance"] = result_df.groupby("Data Set")["MSE Variance"].rank(ascending=True)
result_df[["Method", "Rank Bias", "Rank Variance"]].groupby("Method").mean()

            Rank Bias  Rank Variance
Method
FW-MRS-RF         4.6            4.8
FW-MRS-SVM        5.8            3.2
KMM               2.0            2.8
MRS               2.2            4.0
PSA               2.2            3.6
Uniform           4.2            2.6

In [105]:
result_df["MSE Expexted Loss"] = result_df.groupby("Data Set")["MSE Expexted Loss"].rank(ascending=True)
result_df["0-1 Expexted Loss"] = result_df.groupby("Data Set")["0-1 Expexted Loss"].rank(ascending=True)
result_df[["Method", "MSE Expexted Loss", "0-1 Expexted Loss"]].groupby("Method").mean()

            MSE Expexted Loss  0-1 Expexted Loss
Method
FW-MRS-RF                 5.0                4.4
FW-MRS-SVM                6.0                5.0
KMM                       2.4                4.1
MRS                       2.2                1.8
PSA                       2.0                2.0
Uniform                   3.4                3.7