In [59]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [60]:
result_path = Path("../thesis_results/downstream_task")
methods_list = ["uniform","psa", "kmm", "mrs-forest", "soft-mrs-exponential", "fw-mrs-temperature",  "fw-mrs-temperature-svm"]
# bias_types = ["less_negative_class", "less_positive_class", "mean_difference"]
bias_types = ["mean_difference"]
metrics = ["AUROC", "AUPRC"]
# less_bias_strengths = ["0.1", "0.2", "0.3"]
less_bias_strengths = ["0.1"]
mean_bias_strengthts = ["0.8"]
datasets = ["folktables_employment", "folktables_income", "hr_analytics", "breast_cancer", "loan_prediction"]

In [61]:
aurocs = []
auprcs = []
dict_list = []
for dataset in datasets:
    for bias_type in bias_types:
        for method in methods_list:
            if bias_type == "mean_difference":
                bias_strengths = mean_bias_strengthts
            else : 
                bias_strengths = less_bias_strengths
            for bias_strength in bias_strengths:
                json_file = result_path / dataset / bias_type /  bias_strength/ method / "classification_results.json"
                result_file = pd.read_json(str(json_file))
                dict_list.append(
                    {
                        "Method": method, "Data Set": dataset, 
                        "AUROC Mean": result_file["random forest auroc"]["mean"], 
                        "AUROC Std": result_file["random forest auroc"]["sd"], 
                        "AUPRC Mean": result_file["random forest auprc"]["mean"], 
                        "AUPRC Std": result_file["random forest auprc"]["sd"], 
                        "Bias Type": bias_type, "Bias Strength": bias_strength,
                        "Dropped Samples Mean": result_file["dropped_samples"]["mean"],
                        "Dropped Samples Std": result_file["dropped_samples"]["std"]
                    }
                                )
result_df = pd.DataFrame(data=dict_list)

In [62]:
result_df = result_df.replace({"uniform": "Uniform", "kmm": "KMM", "psa": "PSA", "mrs-forest": "MRS",
                               "soft-mrs-linear": "Soft-MRS-Linear", "soft-mrs-exponential": "Soft-MRS-Exponential",
                               "fw-mrs-temperature-svm": "FW-MRS-SVM", "fw-mrs-temperature": "FW-MRS-RF"})
result_df

,Method,Data Set,AUROC Mean,AUROC Std,AUPRC Mean,AUPRC Std,Bias Type,Bias Strength,Dropped Samples Mean,Dropped Samples Std
0,Uniform,folktables_employment,0.885053,0.007930,0.845045,0.013863,mean_difference,0.8,0.00,0.000000
1,PSA,folktables_employment,0.885395,0.007804,0.845636,0.014192,mean_difference,0.8,0.00,0.000000
2,KMM,folktables_employment,0.881620,0.008066,0.839454,0.015406,mean_difference,0.8,0.00,0.000000
3,MRS,folktables_employment,0.884941,0.007886,0.844889,0.014057,mean_difference,0.8,194.30,37.416707
4,Soft-MRS-Exponential,folktables_employment,0.885599,0.008035,0.845740,0.013996,mean_difference,0.8,0.00,0.000000
5,FW-MRS-RF,folktables_employment,0.876028,0.008141,0.832883,0.013800,mean_difference,0.8,188.50,42.311346
6,FW-MRS-SVM,folktables_employment,0.883324,0.008371,0.842921,0.013805,mean_difference,0.8,478.90,67.448425
7,Uniform,folktables_income,0.855276,0.008886,0.814747,0.013880,mean_difference,0.8,0.00,0.000000
8,PSA,folktables_income,0.858145,0.009160,0.818174,0.013560,mean_difference,0.8,0.00,0.000000
9,KMM,folktables_income,0.853194,0.009154,0.811642,0.014052,mean_difference,0.8,0.00,0.000000
10,MRS,folktables_income,0.855398,0.009011,0.814775,0.014128,mean_difference,0.8,184.50,37.259227
11,Soft-MRS-Exponential,folktables_income,0.858799,0.009197,0.818604,0.013774,mean_difference,0.8,0.00,0.000000
12,FW-MRS-RF,folktables_income,0.851250,0.011039,0.810201,0.015850,mean_difference,0.8,131.20,65.936030
13,FW-MRS-SVM,folktables_income,0.850018,0.010662,0.807106,0.014185,mean_difference,0.8,585.60,130.868789
14,Uniform,hr_analytics,0.764915,0.017774,0.470300,0.029334,mean_difference,0.8,0.00,0.000000
15,PSA,hr_analytics,0.761622,0.018469,0.468824,0.030727,mean_difference,0.8,0.00,0.000000
16,KMM,hr_analytics,0.756333,0.019465,0.462033,0.027267,mean_difference,0.8,0.00,0.000000
17,MRS,hr_analytics,0.763788,0.017849,0.470460,0.027828,mean_difference,0.8,360.00,70.880181
18,Soft-MRS-Exponential,hr_analytics,0.759271,0.018947,0.467918,0.030288,mean_difference,0.8,0.00,0.000000
19,FW-MRS-RF,hr_analytics,0.762050,0.016213,0.468152,0.028293,mean_difference,0.8,372.30,75.101332
20,FW-MRS-SVM,hr_analytics,0.759218,0.017588,0.465357,0.029926,mean_difference,0.8,999.70,274.627766
21,Uniform,breast_cancer,0.991069,0.005276,0.995991,0.002195,mean_difference,0.8,0.00,0.000000
22,PSA,breast_cancer,0.990746,0.005036,0.995877,0.002123,mean_difference,0.8,0.00,0.000000
23,KMM,breast_cancer,0.990428,0.005683,0.995755,0.002380,mean_difference,0.8,0.00,0.000000
24,MRS,breast_cancer,0.990969,0.005474,0.995976,0.002260,mean_difference,0.8,19.32,9.405190
25,Soft-MRS-Exponential,breast_cancer,0.991236,0.005225,0.996068,0.002199,mean_difference,0.8,0.00,0.000000
26,FW-MRS-RF,breast_cancer,0.987687,0.007961,0.994288,0.004902,mean_difference,0.8,17.02,12.055687
27,FW-MRS-SVM,breast_cancer,0.988763,0.006699,0.994899,0.003322,mean_difference,0.8,34.96,15.031913
28,Uniform,loan_prediction,0.761189,0.054065,0.855635,0.038695,mean_difference,0.8,0.00,0.000000
29,PSA,loan_prediction,0.756169,0.057088,0.852064,0.042676,mean_difference,0.8,0.00,0.000000
30,KMM,loan_prediction,0.749974,0.054986,0.850062,0.039031,mean_difference,0.8,0.00,0.000000
31,MRS,loan_prediction,0.754625,0.055201,0.852030,0.038561,mean_difference,0.8,5.84,6.313034
32,Soft-MRS-Exponential,loan_prediction,0.752908,0.056381,0.847707,0.040547,mean_difference,0.8,0.00,0.000000
33,FW-MRS-RF,loan_prediction,0.735388,0.061146,0.832657,0.047783,mean_difference,0.8,4.26,7.101577
34,FW-MRS-SVM,loan_prediction,0.737460,0.053051,0.840006,0.036170,mean_difference,0.8,13.16,11.432165

In [63]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            mean_auroc_values = []
            std_auroc_values = []
            for dataset in datasets:
                mean_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["AUROC Mean"].iloc[0]
                mean_auroc_values.append(np.round(mean_auroc, 3))

                std_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["AUROC Std"].iloc[0]
                std_auroc_values.append(np.round(std_auroc, 3))

            print(f"\t& {method} \
& ${mean_auroc_values[0]}\\pm{std_auroc_values[0]}$ \
& ${mean_auroc_values[1]}\\pm{std_auroc_values[1]}$ \
& ${mean_auroc_values[2]}\\pm{std_auroc_values[2]}$ \
& ${mean_auroc_values[3]}\\pm{std_auroc_values[3]}$ \
& ${mean_auroc_values[4]}\\pm{std_auroc_values[4]}$ & \\\\")
        print("\n")

mean_difference, 0.8
	& Uniform & $0.885\pm0.008$ & $0.855\pm0.009$ & $0.765\pm0.018$ & $0.991\pm0.005$ & $0.761\pm0.054$ & \\
	& PSA & $0.885\pm0.008$ & $0.858\pm0.009$ & $0.762\pm0.018$ & $0.991\pm0.005$ & $0.756\pm0.057$ & \\
	& KMM & $0.882\pm0.008$ & $0.853\pm0.009$ & $0.756\pm0.019$ & $0.99\pm0.006$ & $0.75\pm0.055$ & \\
	& MRS & $0.885\pm0.008$ & $0.855\pm0.009$ & $0.764\pm0.018$ & $0.991\pm0.005$ & $0.755\pm0.055$ & \\
	& Soft-MRS-Exponential & $0.886\pm0.008$ & $0.859\pm0.009$ & $0.759\pm0.019$ & $0.991\pm0.005$ & $0.753\pm0.056$ & \\
	& FW-MRS-RF & $0.876\pm0.008$ & $0.851\pm0.011$ & $0.762\pm0.016$ & $0.988\pm0.008$ & $0.735\pm0.061$ & \\
	& FW-MRS-SVM & $0.883\pm0.008$ & $0.85\pm0.011$ & $0.759\pm0.018$ & $0.989\pm0.007$ & $0.737\pm0.053$ & \\

In [64]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            mean_auprc_values = []
            std_auprc_values = []
            for dataset in datasets:
                mean_auprc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["AUPRC Mean"].iloc[0]
                mean_auprc_values.append(np.round(mean_auprc, 3))

                std_auprc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["AUPRC Std"].iloc[0]
                std_auprc_values.append(np.round(std_auprc, 3))

            print(f"\t& {method} \
& ${mean_auprc_values[0]}\\pm{std_auprc_values[0]}$ \
& ${mean_auprc_values[1]}\\pm{std_auprc_values[1]}$ \
& ${mean_auprc_values[2]}\\pm{std_auprc_values[2]}$ \
& ${mean_auprc_values[3]}\\pm{std_auprc_values[3]}$ \
& ${mean_auprc_values[4]}\\pm{std_auprc_values[4]}$ & \\\\")
        print("\n")

mean_difference, 0.8
	& Uniform & $0.845\pm0.014$ & $0.815\pm0.014$ & $0.47\pm0.029$ & $0.996\pm0.002$ & $0.856\pm0.039$ & \\
	& PSA & $0.846\pm0.014$ & $0.818\pm0.014$ & $0.469\pm0.031$ & $0.996\pm0.002$ & $0.852\pm0.043$ & \\
	& KMM & $0.839\pm0.015$ & $0.812\pm0.014$ & $0.462\pm0.027$ & $0.996\pm0.002$ & $0.85\pm0.039$ & \\
	& MRS & $0.845\pm0.014$ & $0.815\pm0.014$ & $0.47\pm0.028$ & $0.996\pm0.002$ & $0.852\pm0.039$ & \\
	& Soft-MRS-Exponential & $0.846\pm0.014$ & $0.819\pm0.014$ & $0.468\pm0.03$ & $0.996\pm0.002$ & $0.848\pm0.041$ & \\
	& FW-MRS-RF & $0.833\pm0.014$ & $0.81\pm0.016$ & $0.468\pm0.028$ & $0.994\pm0.005$ & $0.833\pm0.048$ & \\
	& FW-MRS-SVM & $0.843\pm0.014$ & $0.807\pm0.014$ & $0.465\pm0.03$ & $0.995\pm0.003$ & $0.84\pm0.036$ & \\

In [65]:
result_df["Rank AUROC"] = result_df.groupby("Data Set")["AUROC Mean"].rank(ascending=False)
result_df["Rank AUPRC"] = result_df.groupby("Data Set")["AUPRC Mean"].rank(ascending=False)
result_df[["Method", "Rank AUROC", "Rank AUPRC"]].groupby("Method").mean()

                      Rank AUROC  Rank AUPRC
Method
FW-MRS-RF                    6.0         6.2
FW-MRS-SVM                   6.0         6.0
KMM                          5.6         5.4
MRS                          3.0         2.8
PSA                          2.8         2.6
Soft-MRS-Exponential         2.4         2.6
Uniform                      2.2         2.4