In [22]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [23]:
result_path = Path("../results/downstream_task")
methods_list = ["uniform","psa", "kmm", "mrs-forest", 
               # "soft-mrs-exponential", 
                "fw-mrs-temperature_old",  
                "fw-mrs-temperature-svm_old",
                "fw-mrs-temperature",  "fw-mrs-temperature-svm",
                ]
# bias_types = ["less_negative_class", "less_positive_class", "mean_difference"]
bias_types = ["less_positive_class"]
metrics = ["AUROC", "AUPRC"]
less_bias_strengths = ["0.1"]
mean_bias_strengthts = ["0.8"]
datasets = ["folktables_employment", "folktables_income", "hr_analytics", "breast_cancer", "loan_prediction", "diabetes", "bank_marketing", 
            "german_credit"]
method_name_replacer = {"uniform": "Uniform", "kmm": "KMM", "psa": "PSA", "mrs-forest": "MRS",
                            # "soft-mrs-exponential": "Soft-MRS-Exponential",
                               "mrs-forest": "MRS", "fw-mrs-temperature_old": "FW-MRS-RF-Abs", "fw-mrs-temperature-svm_old": "FW-MRS-SVM-Abs",
                        "fw-mrs-temperature-svm": "FW-MRS-SVM-Signed", "fw-mrs-temperature": "FW-MRS-RF-Signed",
                          }

In [24]:
aurocs = []
auprcs = []
dict_list = []
for dataset in datasets:
    for bias_type in bias_types:
        for method in methods_list:
            if bias_type == "mean_difference":
                bias_strengths = mean_bias_strengthts
            else : 
                bias_strengths = less_bias_strengths
            for bias_strength in bias_strengths:
                json_file = result_path / dataset / bias_type /  bias_strength/ method / "classification_results.json"
                try:
                    result_file = pd.read_json(str(json_file))
                except FileNotFoundError:
                    continue
                dict_list.append(
                    {
                        "Method": method, "Data Set": dataset, 
                        "AUROC Mean": result_file["random forest auroc"]["mean"], 
                        "AUROC Std": result_file["random forest auroc"]["sd"], 
                        "AUPRC Mean": result_file["random forest auprc"]["mean"], 
                        "AUPRC Std": result_file["random forest auprc"]["sd"], 
                        "Bias Type": bias_type, "Bias Strength": bias_strength,
                        "Dropped Samples Mean": result_file["dropped_samples"]["mean"],
                        "Dropped Samples Std": result_file["dropped_samples"]["std"]
                    }
                                )
result_df = pd.DataFrame(data=dict_list)

In [25]:
result_df = result_df.replace(method_name_replacer)
result_df

,Method,Data Set,AUROC Mean,AUROC Std,AUPRC Mean,AUPRC Std,Bias Type,Bias Strength,Dropped Samples Mean,Dropped Samples Std
0,Uniform,folktables_employment,0.871697,0.010310,0.827937,0.017155,less_positive_class,0.1,0.00,0.000000
1,PSA,folktables_employment,0.867177,0.011390,0.823004,0.017988,less_positive_class,0.1,0.00,0.000000
2,KMM,folktables_employment,0.859151,0.012266,0.812484,0.019343,less_positive_class,0.1,0.00,0.000000
3,MRS,folktables_employment,0.869787,0.010676,0.825169,0.017483,less_positive_class,0.1,300.60,122.006721
4,FW-MRS-RF-Signed,folktables_employment,0.865073,0.011916,0.820736,0.018674,less_positive_class,0.1,393.50,69.658094
5,FW-MRS-SVM-Signed,folktables_employment,0.834048,0.014466,0.776362,0.023446,less_positive_class,0.1,270.90,31.475228
6,Uniform,folktables_income,0.839249,0.011924,0.790149,0.016918,less_positive_class,0.1,0.00,0.000000
7,PSA,folktables_income,0.831454,0.013224,0.780936,0.018020,less_positive_class,0.1,0.06,0.310483
8,KMM,folktables_income,0.821094,0.014272,0.767031,0.019205,less_positive_class,0.1,0.00,0.000000
9,MRS,folktables_income,0.837711,0.012394,0.789246,0.018232,less_positive_class,0.1,307.50,87.676964
10,FW-MRS-RF-Signed,folktables_income,0.835350,0.012927,0.787733,0.018346,less_positive_class,0.1,331.10,63.845830
11,FW-MRS-SVM-Signed,folktables_income,0.827505,0.014039,0.780002,0.019378,less_positive_class,0.1,294.50,30.907119
12,Uniform,hr_analytics,0.752918,0.017054,0.458778,0.024450,less_positive_class,0.1,0.00,0.000000
13,PSA,hr_analytics,0.750735,0.018964,0.455972,0.027790,less_positive_class,0.1,0.00,0.000000
14,KMM,hr_analytics,0.748732,0.019231,0.447820,0.027254,less_positive_class,0.1,0.00,0.000000
15,MRS,hr_analytics,0.750712,0.017800,0.456701,0.027776,less_positive_class,0.1,111.10,51.412936
16,FW-MRS-RF-Signed,hr_analytics,0.749859,0.020314,0.452957,0.028341,less_positive_class,0.1,110.30,39.552623
17,FW-MRS-SVM-Signed,hr_analytics,0.746481,0.018148,0.445253,0.030967,less_positive_class,0.1,168.10,75.557197
18,Uniform,breast_cancer,0.987989,0.006335,0.994033,0.003247,less_positive_class,0.1,0.00,0.000000
19,PSA,breast_cancer,0.988196,0.006332,0.994273,0.003128,less_positive_class,0.1,0.00,0.000000
20,KMM,breast_cancer,0.989529,0.005742,0.994920,0.002798,less_positive_class,0.1,0.00,0.000000
21,MRS,breast_cancer,0.989752,0.005202,0.995170,0.002380,less_positive_class,0.1,61.66,4.096877
22,FW-MRS-RF-Signed,breast_cancer,0.989248,0.005218,0.994872,0.002468,less_positive_class,0.1,55.18,5.545052
23,FW-MRS-SVM-Signed,breast_cancer,0.985257,0.007629,0.993062,0.003493,less_positive_class,0.1,63.12,6.647225
24,Uniform,loan_prediction,0.669057,0.074552,0.801849,0.048870,less_positive_class,0.1,0.00,0.000000
25,PSA,loan_prediction,0.623313,0.089545,0.783215,0.055373,less_positive_class,0.1,0.00,0.000000
26,KMM,loan_prediction,0.607333,0.079340,0.773871,0.051793,less_positive_class,0.1,0.00,0.000000
27,MRS,loan_prediction,0.651567,0.082445,0.796105,0.052890,less_positive_class,0.1,8.94,4.636421
28,FW-MRS-RF-Signed,loan_prediction,0.607258,0.085563,0.770718,0.054057,less_positive_class,0.1,5.28,4.647752
29,FW-MRS-SVM-Signed,loan_prediction,0.551306,0.075223,0.737592,0.048691,less_positive_class,0.1,5.10,5.960705
30,Uniform,diabetes,0.791334,0.018959,0.366981,0.035053,less_positive_class,0.1,0.00,0.000000
31,PSA,diabetes,0.786338,0.021659,0.359501,0.036601,less_positive_class,0.1,0.00,0.000000
32,KMM,diabetes,0.783061,0.021427,0.355495,0.038136,less_positive_class,0.1,0.00,0.000000
33,MRS,diabetes,0.790902,0.019707,0.365957,0.035812,less_positive_class,0.1,52.60,38.668333
34,FW-MRS-RF-Signed,diabetes,0.787795,0.019368,0.359786,0.037486,less_positive_class,0.1,53.10,31.207211
35,FW-MRS-SVM-Signed,diabetes,0.786941,0.021505,0.361401,0.039120,less_positive_class,0.1,86.30,36.685283
36,Uniform,bank_marketing,0.854354,0.019281,0.469682,0.050036,less_positive_class,0.1,0.00,0.000000
37,PSA,bank_marketing,0.848399,0.019737,0.464141,0.047712,less_positive_class,0.1,0.00,0.000000
38,KMM,bank_marketing,0.839341,0.024967,0.450453,0.054114,less_positive_class,0.1,0.00,0.000000
39,MRS,bank_marketing,0.853393,0.019704,0.470003,0.051876,less_positive_class,0.1,69.20,39.753742
40,FW-MRS-RF-Signed,bank_marketing,0.849880,0.018806,0.466810,0.048614,less_positive_class,0.1,63.00,31.953091
41,FW-MRS-SVM-Signed,bank_marketing,0.841677,0.027448,0.455063,0.056276,less_positive_class,0.1,61.90,34.797845
42,Uniform,german_credit,0.679840,0.054176,0.473024,0.062405,less_positive_class,0.1,0.00,0.000000
43,PSA,german_credit,0.659107,0.054370,0.454340,0.065428,less_positive_class,0.1,0.00,0.000000
44,KMM,german_credit,0.652679,0.049341,0.447300,0.055021,less_positive_class,0.1,0.00,0.000000
45,MRS,german_credit,0.674286,0.056304,0.465363,0.062017,less_positive_class,0.1,15.00,11.313708
46,FW-MRS-RF-Signed,german_credit,0.659306,0.054588,0.450963,0.059166,less_positive_class,0.1,10.80,9.816313
47,FW-MRS-SVM-Signed,german_credit,0.641574,0.058517,0.431310,0.058511,less_positive_class,0.1,10.70,10.817116

In [26]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            mean_auroc_values = []
            std_auroc_values = []
            for dataset in datasets:
                try:
                    mean_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUROC Mean"].iloc[0]
                    mean_auroc_values.append(np.round(mean_auroc, 3))

                    std_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUROC Std"].iloc[0]
                    std_auroc_values.append(np.round(std_auroc, 2))
                except IndexError:
                    mean_auroc_values.append(0)
                    std_auroc_values.append(0)

            print(f"\t& {method} \
& ${mean_auroc_values[0]}\\pm{std_auroc_values[0]}$ \
& ${mean_auroc_values[1]}\\pm{std_auroc_values[1]}$ \
& ${mean_auroc_values[2]}\\pm{std_auroc_values[2]}$ \
& ${mean_auroc_values[3]}\\pm{std_auroc_values[3]}$ \
& ${mean_auroc_values[4]}\\pm{std_auroc_values[4]}$ & \\\\")
        print("\n")

less_positive_class, 0.1
	& Uniform & $0.872\pm0.01$ & $0.839\pm0.01$ & $0.753\pm0.02$ & $0.988\pm0.01$ & $0.669\pm0.07$ & \\
	& PSA & $0.867\pm0.01$ & $0.831\pm0.01$ & $0.751\pm0.02$ & $0.988\pm0.01$ & $0.623\pm0.09$ & \\
	& KMM & $0.859\pm0.01$ & $0.821\pm0.01$ & $0.749\pm0.02$ & $0.99\pm0.01$ & $0.607\pm0.08$ & \\
	& MRS & $0.87\pm0.01$ & $0.838\pm0.01$ & $0.751\pm0.02$ & $0.99\pm0.01$ & $0.652\pm0.08$ & \\
	& FW-MRS-RF-Signed & $0.865\pm0.01$ & $0.835\pm0.01$ & $0.75\pm0.02$ & $0.989\pm0.01$ & $0.607\pm0.09$ & \\
	& FW-MRS-SVM-Signed & $0.834\pm0.01$ & $0.828\pm0.01$ & $0.746\pm0.02$ & $0.985\pm0.01$ & $0.551\pm0.08$ & \\

In [27]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            mean_auprc_values = []
            std_auprc_values = []
            for dataset in datasets:
                try:
                    mean_auprc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUPRC Mean"].iloc[0]
                    mean_auprc_values.append(np.round(mean_auprc, 3))

                    std_auprc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUPRC Std"].iloc[0]
                    std_auprc_values.append(np.round(std_auprc, 2))
                except IndexError:
                    mean_auprc_values.append(0)
                    std_auprc_values.append(0)

            print(f"\t& {method} \
& ${mean_auprc_values[0]}\\pm{std_auprc_values[0]}$ \
& ${mean_auprc_values[1]}\\pm{std_auprc_values[1]}$ \
& ${mean_auprc_values[2]}\\pm{std_auprc_values[2]}$ \
& ${mean_auprc_values[3]}\\pm{std_auprc_values[3]}$ \
& ${mean_auprc_values[4]}\\pm{std_auprc_values[4]}$ & \\\\")
        print("\n")

less_positive_class, 0.1
	& Uniform & $0.828\pm0.02$ & $0.79\pm0.02$ & $0.459\pm0.02$ & $0.994\pm0.0$ & $0.802\pm0.05$ & \\
	& PSA & $0.823\pm0.02$ & $0.781\pm0.02$ & $0.456\pm0.03$ & $0.994\pm0.0$ & $0.783\pm0.06$ & \\
	& KMM & $0.812\pm0.02$ & $0.767\pm0.02$ & $0.448\pm0.03$ & $0.995\pm0.0$ & $0.774\pm0.05$ & \\
	& MRS & $0.825\pm0.02$ & $0.789\pm0.02$ & $0.457\pm0.03$ & $0.995\pm0.0$ & $0.796\pm0.05$ & \\
	& FW-MRS-RF-Signed & $0.821\pm0.02$ & $0.788\pm0.02$ & $0.453\pm0.03$ & $0.995\pm0.0$ & $0.771\pm0.05$ & \\
	& FW-MRS-SVM-Signed & $0.776\pm0.02$ & $0.78\pm0.02$ & $0.445\pm0.03$ & $0.993\pm0.0$ & $0.738\pm0.05$ & \\

In [28]:
result_df["Rank AUROC"] = result_df.groupby("Data Set")["AUROC Mean"].rank(ascending=False)
result_df["Rank AUPRC"] = result_df.groupby("Data Set")["AUPRC Mean"].rank(ascending=False)
result_df[["Method", "Rank AUROC", "Rank AUPRC"]].groupby("Method").mean()

                   Rank AUROC  Rank AUPRC
Method
FW-MRS-RF-Signed        3.500       3.750
FW-MRS-SVM-Signed       5.500       5.375
KMM                     4.875       4.875
MRS                     2.000       1.750
PSA                     3.625       3.625
Uniform                 1.500       1.625