In [9]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [10]:
result_path = Path("../results/downstream_task")
bias_types = ["less_positive_class"]
metrics = ["AUROC"]
less_bias_strengths = ["0.1"]
method_name_replacer = {
                        "uniform": "Uniform", 
                        "psa": "PSA", 
                        "kmm": "KMM", 
                        "mrs-forest": "MRS", 
                        "fw-mrs-temperature": "FW-MRS",
                        "fw-mrs-temperature-svm": "FW-MRS$_{SVM}$",
                        }
data_set_replacer = {
                    "diabetes": "Diabetes", 
                    "folktables_employment": "Employment", 
                    "folktables_income": "Income",
                    "bank_marketing": "Bank Marketing",
                    "hr_analytics": "HR Analytic", 
                    "german_credit": "German Credit", 
                    "breast_cancer": "Breast Cancer", 
                    "loan_prediction": "Loan",
                    }

In [11]:
aurocs = []
auprcs = []
dict_list = []
for dataset in data_set_replacer.keys():
    for bias_type in bias_types:
        for method in method_name_replacer.keys():
            for bias_strength in less_bias_strengths:
                json_file = result_path / dataset / bias_type /  bias_strength/ method / "classification_results.json"
                try:
                    result_file = pd.read_json(str(json_file))
                except FileNotFoundError:
                    continue
                dict_list.append(
                    {
                        "Method": method, "Data Set": dataset, 
                        "AUROC Mean": result_file["random forest auroc"]["mean"], 
                        "AUROC Std": result_file["random forest auroc"]["sd"], 
                        "Bias Type": bias_type, "Bias Strength": bias_strength,
                        "Dropped Samples Mean": result_file["dropped_samples"]["mean"],
                        "Dropped Samples Std": result_file["dropped_samples"]["std"],
                        "RF Domain AUROC Mean": result_file["rf domain auroc"]["mean"],
                        "RF Domain AUROC Std": result_file["rf domain auroc"]["sd"],
                    }
                                )
result_df = pd.DataFrame(data=dict_list)

In [12]:
result_df = result_df.replace(method_name_replacer)
result_df

,Method,Data Set,AUROC Mean,AUROC Std,Bias Type,Bias Strength,Dropped Samples Mean,Dropped Samples Std,RF Domain AUROC Mean,RF Domain AUROC Std
0,Uniform,diabetes,0.791498,0.022072,less_positive_class,0.1,0.000000,0.000000,0.524808,0.009243
1,PSA,diabetes,0.787277,0.023148,less_positive_class,0.1,0.000000,0.000000,0.512270,0.003703
2,KMM,diabetes,0.781169,0.021943,less_positive_class,0.1,0.000000,0.000000,0.521981,0.007816
3,MRS,diabetes,0.789326,0.023831,less_positive_class,0.1,39.600000,32.493692,0.522293,0.009748
4,FW-MRS,diabetes,0.786366,0.022672,less_positive_class,0.1,42.700000,34.629612,0.520027,0.009081
5,FW-MRS$_{SVM}$,diabetes,0.781606,0.029615,less_positive_class,0.1,61.400000,33.181923,0.518128,0.007736
6,Uniform,folktables_employment,0.870601,0.010491,less_positive_class,0.1,0.000000,0.000000,0.630367,0.010368
7,PSA,folktables_employment,0.867401,0.010937,less_positive_class,0.1,0.040000,0.280000,0.528106,0.009637
8,KMM,folktables_employment,0.856631,0.013580,less_positive_class,0.1,0.000000,0.000000,0.525253,0.008685
9,MRS,folktables_employment,0.869954,0.009992,less_positive_class,0.1,203.900000,35.061232,0.602020,0.012732
10,FW-MRS,folktables_employment,0.867217,0.011578,less_positive_class,0.1,194.200000,34.933651,0.604252,0.011239
11,FW-MRS$_{SVM}$,folktables_employment,0.864207,0.012261,less_positive_class,0.1,269.259259,29.240500,0.576589,0.011422
12,Uniform,folktables_income,0.838084,0.012878,less_positive_class,0.1,0.000000,0.000000,0.612679,0.014196
13,PSA,folktables_income,0.831057,0.013985,less_positive_class,0.1,0.160000,0.703136,0.519376,0.007730
14,KMM,folktables_income,0.820208,0.014266,less_positive_class,0.1,0.000000,0.000000,0.527638,0.007296
15,MRS,folktables_income,0.837651,0.013005,less_positive_class,0.1,199.400000,49.138987,0.587054,0.018934
16,FW-MRS,folktables_income,0.833737,0.014408,less_positive_class,0.1,198.100000,48.547811,0.585652,0.017469
17,FW-MRS$_{SVM}$,folktables_income,0.831871,0.013569,less_positive_class,0.1,299.200000,34.298105,0.570985,0.014648
18,Uniform,bank_marketing,0.846908,0.021440,less_positive_class,0.1,0.000000,0.000000,0.522693,0.008734
19,PSA,bank_marketing,0.839479,0.025952,less_positive_class,0.1,0.000000,0.000000,0.512231,0.003996
20,KMM,bank_marketing,0.831756,0.026469,less_positive_class,0.1,0.000000,0.000000,0.521086,0.006660
21,MRS,bank_marketing,0.845635,0.021468,less_positive_class,0.1,58.800000,35.207386,0.516828,0.006621
22,FW-MRS,bank_marketing,0.845421,0.019709,less_positive_class,0.1,56.400000,30.100498,0.518480,0.007114
23,FW-MRS$_{SVM}$,bank_marketing,0.840053,0.019759,less_positive_class,0.1,56.000000,32.449961,0.517822,0.006093
24,Uniform,hr_analytics,0.752772,0.018290,less_positive_class,0.1,0.000000,0.000000,0.532918,0.008788
25,PSA,hr_analytics,0.750453,0.019049,less_positive_class,0.1,0.000000,0.000000,0.511088,0.004514
26,KMM,hr_analytics,0.749431,0.019074,less_positive_class,0.1,0.000000,0.000000,0.514326,0.005495
27,MRS,hr_analytics,0.751373,0.019375,less_positive_class,0.1,105.300000,58.020772,0.526627,0.007657
28,FW-MRS,hr_analytics,0.751020,0.018792,less_positive_class,0.1,110.100000,54.785856,0.524931,0.007972
29,FW-MRS$_{SVM}$,hr_analytics,0.751307,0.018748,less_positive_class,0.1,164.200000,76.048406,0.527373,0.009153
30,Uniform,german_credit,0.667239,0.053736,less_positive_class,0.1,0.000000,0.000000,0.538268,0.015928
31,PSA,german_credit,0.658996,0.055090,less_positive_class,0.1,0.000000,0.000000,0.532806,0.009209
32,KMM,german_credit,0.648943,0.052757,less_positive_class,0.1,0.000000,0.000000,0.546872,0.015067
33,MRS,german_credit,0.668462,0.054647,less_positive_class,0.1,12.800000,11.452511,0.533510,0.011700
34,FW-MRS,german_credit,0.643725,0.062229,less_positive_class,0.1,7.700000,11.100000,0.530923,0.011431
35,FW-MRS$_{SVM}$,german_credit,0.632333,0.070733,less_positive_class,0.1,7.700000,9.910096,0.532860,0.010770
36,Uniform,breast_cancer,0.987591,0.006273,less_positive_class,0.1,0.000000,0.000000,0.730549,0.017786
37,PSA,breast_cancer,0.987893,0.006442,less_positive_class,0.1,0.000000,0.000000,0.583283,0.027643
38,KMM,breast_cancer,0.989408,0.005247,less_positive_class,0.1,0.000000,0.000000,0.592115,0.028551
39,MRS,breast_cancer,0.988525,0.006004,less_positive_class,0.1,53.060000,6.300508,0.648704,0.029313
40,FW-MRS,breast_cancer,0.980229,0.011079,less_positive_class,0.1,39.920000,10.834833,0.658380,0.032431
41,FW-MRS$_{SVM}$,breast_cancer,0.977452,0.011680,less_positive_class,0.1,48.240000,9.229431,0.687989,0.044871
42,Uniform,loan_prediction,0.658389,0.080697,less_positive_class,0.1,0.000000,0.000000,0.570285,0.030109
43,PSA,loan_prediction,0.627560,0.095193,less_positive_class,0.1,0.000000,0.000000,0.553523,0.020760
44,KMM,loan_prediction,0.610365,0.096952,less_positive_class,0.1,0.000000,0.000000,0.585211,0.023742
45,MRS,loan_prediction,0.637731,0.097225,less_positive_class,0.1,8.420000,5.366899,0.550919,0.017978
46,FW-MRS,loan_prediction,0.612096,0.091994,less_positive_class,0.1,3.920000,3.520455,0.552784,0.023472
47,FW-MRS$_{SVM}$,loan_prediction,0.574948,0.093397,less_positive_class,0.1,4.500000,4.854894,0.552331,0.017670

In [13]:
for bias_type in bias_types:
    for bias_strength in less_bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_auroc_values = []
            std_auroc_values = []
            for method in result_df["Method"].unique():
                try:
                    mean_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUROC Mean"].iloc[0]
                    mean_auroc_values.append(np.round(mean_auroc, 3))

                    std_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUROC Std"].iloc[0]
                    std_auroc_values.append(np.round(std_auroc, 2))
                except IndexError:
                    mean_auroc_values.append(0)
                    std_auroc_values.append(0)

            print(f"{data_set_replacer[dataset]} \
& ${mean_auroc_values[0]}\\pm{std_auroc_values[0]}$ \
& ${mean_auroc_values[1]}\\pm{std_auroc_values[1]}$ \
& ${mean_auroc_values[2]}\\pm{std_auroc_values[2]}$ \
& ${mean_auroc_values[3]}\\pm{std_auroc_values[3]}$ \
& ${mean_auroc_values[4]}\\pm{std_auroc_values[4]}$ \
& ${mean_auroc_values[5]}\\pm{std_auroc_values[5]}$ \
\\\\")
        print("\n")

less_positive_class, 0.1
Diabetes & $0.791\pm0.02$ & $0.787\pm0.02$ & $0.781\pm0.02$ & $0.789\pm0.02$ & $0.786\pm0.02$ & $0.782\pm0.03$ \\
Employment & $0.871\pm0.01$ & $0.867\pm0.01$ & $0.857\pm0.01$ & $0.87\pm0.01$ & $0.867\pm0.01$ & $0.864\pm0.01$ \\
Income & $0.838\pm0.01$ & $0.831\pm0.01$ & $0.82\pm0.01$ & $0.838\pm0.01$ & $0.834\pm0.01$ & $0.832\pm0.01$ \\
Bank Marketing & $0.847\pm0.02$ & $0.839\pm0.03$ & $0.832\pm0.03$ & $0.846\pm0.02$ & $0.845\pm0.02$ & $0.84\pm0.02$ \\
HR Analytic & $0.753\pm0.02$ & $0.75\pm0.02$ & $0.749\pm0.02$ & $0.751\pm0.02$ & $0.751\pm0.02$ & $0.751\pm0.02$ \\
German Credit & $0.667\pm0.05$ & $0.659\pm0.06$ & $0.649\pm0.05$ & $0.668\pm0.05$ & $0.644\pm0.06$ & $0.632\pm0.07$ \\
Breast Cancer & $0.988\pm0.01$ & $0.988\pm0.01$ & $0.989\pm0.01$ & $0.989\pm0.01$ & $0.98\pm0.01$ & $0.977\pm0.01$ \\
Loan & $0.658\pm0.08$ & $0.628\pm0.1$ & $0.61\pm0.1$ & $0.638\pm0.1$ & $0.612\pm0.09$ & $0.575\pm0.09$ \\

In [14]:
for bias_type in bias_types:
    for bias_strength in less_bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_domain_values = []
            std_domain_values = []
            for method in result_df["Method"].unique():
                try:
                    mean_domain = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["RF Domain AUROC Mean"].iloc[0]
                    mean_domain_values.append(np.round(mean_domain, 3))

                    std_domain = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["RF Domain AUROC Std"].iloc[0]
                    std_domain_values.append(np.round(std_domain, 2))
                except IndexError:
                    mean_domain_values.append(0)
                    std_domain_values.append(0)

            print(f"{data_set_replacer[dataset]} \
& ${mean_domain_values[0]}\\pm{std_domain_values[0]}$ \
& ${mean_domain_values[1]}\\pm{std_domain_values[1]}$ \
& ${mean_domain_values[2]}\\pm{std_domain_values[2]}$ \
& ${mean_domain_values[3]}\\pm{std_domain_values[3]}$ \
& ${mean_domain_values[4]}\\pm{std_domain_values[4]}$ \
& ${mean_domain_values[5]}\\pm{std_domain_values[5]}$ \
& \\\\")
        print("\n")

less_positive_class, 0.1
Diabetes & $0.525\pm0.01$ & $0.512\pm0.0$ & $0.522\pm0.01$ & $0.522\pm0.01$ & $0.52\pm0.01$ & $0.518\pm0.01$ & \\
Employment & $0.63\pm0.01$ & $0.528\pm0.01$ & $0.525\pm0.01$ & $0.602\pm0.01$ & $0.604\pm0.01$ & $0.577\pm0.01$ & \\
Income & $0.613\pm0.01$ & $0.519\pm0.01$ & $0.528\pm0.01$ & $0.587\pm0.02$ & $0.586\pm0.02$ & $0.571\pm0.01$ & \\
Bank Marketing & $0.523\pm0.01$ & $0.512\pm0.0$ & $0.521\pm0.01$ & $0.517\pm0.01$ & $0.518\pm0.01$ & $0.518\pm0.01$ & \\
HR Analytic & $0.533\pm0.01$ & $0.511\pm0.0$ & $0.514\pm0.01$ & $0.527\pm0.01$ & $0.525\pm0.01$ & $0.527\pm0.01$ & \\
German Credit & $0.538\pm0.02$ & $0.533\pm0.01$ & $0.547\pm0.02$ & $0.534\pm0.01$ & $0.531\pm0.01$ & $0.533\pm0.01$ & \\
Breast Cancer & $0.731\pm0.02$ & $0.583\pm0.03$ & $0.592\pm0.03$ & $0.649\pm0.03$ & $0.658\pm0.03$ & $0.688\pm0.04$ & \\
Loan & $0.57\pm0.03$ & $0.554\pm0.02$ & $0.585\pm0.02$ & $0.551\pm0.02$ & $0.553\pm0.02$ & $0.552\pm0.02$ & \\

In [15]:
result_df.round(3)

,Method,Data Set,AUROC Mean,AUROC Std,Bias Type,Bias Strength,Dropped Samples Mean,Dropped Samples Std,RF Domain AUROC Mean,RF Domain AUROC Std
0,Uniform,diabetes,0.791,0.022,less_positive_class,0.1,0.000,0.000,0.525,0.009
1,PSA,diabetes,0.787,0.023,less_positive_class,0.1,0.000,0.000,0.512,0.004
2,KMM,diabetes,0.781,0.022,less_positive_class,0.1,0.000,0.000,0.522,0.008
3,MRS,diabetes,0.789,0.024,less_positive_class,0.1,39.600,32.494,0.522,0.010
4,FW-MRS,diabetes,0.786,0.023,less_positive_class,0.1,42.700,34.630,0.520,0.009
5,FW-MRS$_{SVM}$,diabetes,0.782,0.030,less_positive_class,0.1,61.400,33.182,0.518,0.008
6,Uniform,folktables_employment,0.871,0.010,less_positive_class,0.1,0.000,0.000,0.630,0.010
7,PSA,folktables_employment,0.867,0.011,less_positive_class,0.1,0.040,0.280,0.528,0.010
8,KMM,folktables_employment,0.857,0.014,less_positive_class,0.1,0.000,0.000,0.525,0.009
9,MRS,folktables_employment,0.870,0.010,less_positive_class,0.1,203.900,35.061,0.602,0.013
10,FW-MRS,folktables_employment,0.867,0.012,less_positive_class,0.1,194.200,34.934,0.604,0.011
11,FW-MRS$_{SVM}$,folktables_employment,0.864,0.012,less_positive_class,0.1,269.259,29.241,0.577,0.011
12,Uniform,folktables_income,0.838,0.013,less_positive_class,0.1,0.000,0.000,0.613,0.014
13,PSA,folktables_income,0.831,0.014,less_positive_class,0.1,0.160,0.703,0.519,0.008
14,KMM,folktables_income,0.820,0.014,less_positive_class,0.1,0.000,0.000,0.528,0.007
15,MRS,folktables_income,0.838,0.013,less_positive_class,0.1,199.400,49.139,0.587,0.019
16,FW-MRS,folktables_income,0.834,0.014,less_positive_class,0.1,198.100,48.548,0.586,0.017
17,FW-MRS$_{SVM}$,folktables_income,0.832,0.014,less_positive_class,0.1,299.200,34.298,0.571,0.015
18,Uniform,bank_marketing,0.847,0.021,less_positive_class,0.1,0.000,0.000,0.523,0.009
19,PSA,bank_marketing,0.839,0.026,less_positive_class,0.1,0.000,0.000,0.512,0.004
20,KMM,bank_marketing,0.832,0.026,less_positive_class,0.1,0.000,0.000,0.521,0.007
21,MRS,bank_marketing,0.846,0.021,less_positive_class,0.1,58.800,35.207,0.517,0.007
22,FW-MRS,bank_marketing,0.845,0.020,less_positive_class,0.1,56.400,30.100,0.518,0.007
23,FW-MRS$_{SVM}$,bank_marketing,0.840,0.020,less_positive_class,0.1,56.000,32.450,0.518,0.006
24,Uniform,hr_analytics,0.753,0.018,less_positive_class,0.1,0.000,0.000,0.533,0.009
25,PSA,hr_analytics,0.750,0.019,less_positive_class,0.1,0.000,0.000,0.511,0.005
26,KMM,hr_analytics,0.749,0.019,less_positive_class,0.1,0.000,0.000,0.514,0.005
27,MRS,hr_analytics,0.751,0.019,less_positive_class,0.1,105.300,58.021,0.527,0.008
28,FW-MRS,hr_analytics,0.751,0.019,less_positive_class,0.1,110.100,54.786,0.525,0.008
29,FW-MRS$_{SVM}$,hr_analytics,0.751,0.019,less_positive_class,0.1,164.200,76.048,0.527,0.009
30,Uniform,german_credit,0.667,0.054,less_positive_class,0.1,0.000,0.000,0.538,0.016
31,PSA,german_credit,0.659,0.055,less_positive_class,0.1,0.000,0.000,0.533,0.009
32,KMM,german_credit,0.649,0.053,less_positive_class,0.1,0.000,0.000,0.547,0.015
33,MRS,german_credit,0.668,0.055,less_positive_class,0.1,12.800,11.453,0.534,0.012
34,FW-MRS,german_credit,0.644,0.062,less_positive_class,0.1,7.700,11.100,0.531,0.011
35,FW-MRS$_{SVM}$,german_credit,0.632,0.071,less_positive_class,0.1,7.700,9.910,0.533,0.011
36,Uniform,breast_cancer,0.988,0.006,less_positive_class,0.1,0.000,0.000,0.731,0.018
37,PSA,breast_cancer,0.988,0.006,less_positive_class,0.1,0.000,0.000,0.583,0.028
38,KMM,breast_cancer,0.989,0.005,less_positive_class,0.1,0.000,0.000,0.592,0.029
39,MRS,breast_cancer,0.989,0.006,less_positive_class,0.1,53.060,6.301,0.649,0.029
40,FW-MRS,breast_cancer,0.980,0.011,less_positive_class,0.1,39.920,10.835,0.658,0.032
41,FW-MRS$_{SVM}$,breast_cancer,0.977,0.012,less_positive_class,0.1,48.240,9.229,0.688,0.045
42,Uniform,loan_prediction,0.658,0.081,less_positive_class,0.1,0.000,0.000,0.570,0.030
43,PSA,loan_prediction,0.628,0.095,less_positive_class,0.1,0.000,0.000,0.554,0.021
44,KMM,loan_prediction,0.610,0.097,less_positive_class,0.1,0.000,0.000,0.585,0.024
45,MRS,loan_prediction,0.638,0.097,less_positive_class,0.1,8.420,5.367,0.551,0.018
46,FW-MRS,loan_prediction,0.612,0.092,less_positive_class,0.1,3.920,3.520,0.553,0.023
47,FW-MRS$_{SVM}$,loan_prediction,0.575,0.093,less_positive_class,0.1,4.500,4.855,0.552,0.018

In [16]:
result_df["Rank AUROC"] = result_df.round(3).groupby("Data Set")["AUROC Mean"].rank(ascending=False)
result_df["Rank Domain"] = result_df.round(3).groupby("Data Set")["RF Domain AUROC Mean"].rank(ascending=True)
result_df[["Method", "Rank AUROC", "Rank Domain"]].groupby("Method").mean()

                Rank AUROC  Rank Domain
Method
FW-MRS              3.8125       3.3125
FW-MRS$_{SVM}$      4.8750       3.1875
KMM                 5.0625       3.5625
MRS                 1.8750       3.5000
PSA                 3.8750       1.6875
Uniform             1.5000       5.7500