In [9]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [10]:
result_path = Path("../results/decomposition")
method_name_replacer = {"uniform": "Uniform", 
                        "kmm": "KMM", 
                        "psa": "PSA",
                        "mrs-forest": "MRS", 
                        "fw-mrs-temperature-svm": "FW-MRS-SVM", 
                        "fw-mrs-temperature": "FW-MRS-RF",
                        }
data_set_replacer = {"folktables_employment": "Employment", 
                     "folktables_income": "Income",
                     "breast_cancer": "Breast Cancer", 
                     "hr_analytics": "HR Analytic", 
                     "loan_prediction": "Loan",
                     "diabetes": "Diabetes", 
                     "german_credit": "German Credit", 
                     "bank_marketing": "Bank Marketing"
                    }

In [11]:
aurocs = []
auprcs = []
dict_list = []
for dataset in data_set_replacer.keys():
        for method in method_name_replacer.keys():
            json_file = result_path / dataset / "less_positive_class" /  "0.1" / method / "bias_variance_decomposition.json"
            try:
                result_file = pd.read_json(str(json_file))
            except FileNotFoundError:
                continue
            dict_list.append(
                {
                    "Method": method, 
                    "Data Set": dataset, 
                    "0-1 Bias": result_file["0-1 loss"]["average_bias"], 
                    "0-1 Variance": result_file["0-1 loss"]["average variance"], 
                    "0-1 Expexted Loss": result_file["0-1 loss"]["average expected loss"],
                    "MSE Bias": result_file["mse loss"]["average_bias"], 
                    "MSE Variance": result_file["mse loss"]["average variance"], 
                    "MSE Expexted Loss": result_file["mse loss"]["average expected loss"],
                    "Bias Type": "less_positive_class", 
                    "Bias Strength": 0.1,
                }
                            )
result_df = pd.DataFrame(data=dict_list)

In [12]:
result_df = result_df.replace(method_name_replacer)
result_df = result_df.replace(data_set_replacer)
result_df

,Method,Data Set,0-1 Bias,0-1 Variance,0-1 Expexted Loss,MSE Bias,MSE Variance,MSE Expexted Loss,Bias Type,Bias Strength
0,Uniform,Employment,0.211500,0.157220,0.264080,0.164226,0.014898,0.179124,less_positive_class,0.1
1,KMM,Employment,0.261500,0.200220,0.302880,0.173607,0.021788,0.195394,less_positive_class,0.1
2,PSA,Employment,0.212500,0.143360,0.250840,0.158117,0.012214,0.170331,less_positive_class,0.1
3,MRS,Employment,0.217500,0.152110,0.259090,0.160949,0.012206,0.173155,less_positive_class,0.1
4,FW-MRS-SVM,Employment,0.266500,0.167950,0.290950,0.173117,0.008599,0.181716,less_positive_class,0.1
5,FW-MRS-RF,Employment,0.219000,0.145920,0.255200,0.160291,0.008857,0.169149,less_positive_class,0.1
6,Uniform,Income,0.292000,0.133660,0.307180,0.188564,0.017233,0.205797,less_positive_class,0.1
7,KMM,Income,0.252000,0.256330,0.329710,0.187343,0.036644,0.223986,less_positive_class,0.1
8,PSA,Income,0.288000,0.217420,0.329120,0.196681,0.032110,0.228791,less_positive_class,0.1
9,MRS,Income,0.284000,0.140570,0.304310,0.186255,0.017555,0.203810,less_positive_class,0.1
10,FW-MRS-SVM,Income,0.287500,0.146440,0.308020,0.189803,0.018137,0.207940,less_positive_class,0.1
11,FW-MRS-RF,Income,0.275500,0.136870,0.295630,0.182104,0.015170,0.197273,less_positive_class,0.1
12,Uniform,Breast Cancer,0.048246,0.103947,0.135526,0.051059,0.024326,0.075385,less_positive_class,0.1
13,KMM,Breast Cancer,0.030702,0.077193,0.092807,0.034225,0.028599,0.062824,less_positive_class,0.1
14,PSA,Breast Cancer,0.035088,0.039912,0.062193,0.033548,0.013049,0.046597,less_positive_class,0.1
15,MRS,Breast Cancer,0.035088,0.017281,0.041140,0.035879,0.010112,0.045991,less_positive_class,0.1
16,FW-MRS-SVM,Breast Cancer,0.043860,0.061228,0.081053,0.040482,0.027043,0.067525,less_positive_class,0.1
17,FW-MRS-RF,Breast Cancer,0.048246,0.050088,0.070614,0.042644,0.026692,0.069337,less_positive_class,0.1
18,Uniform,HR Analytic,0.165494,0.071638,0.164449,0.122202,0.039756,0.161958,less_positive_class,0.1
19,KMM,HR Analytic,0.164824,0.157387,0.228489,0.121698,0.043718,0.165417,less_positive_class,0.1
20,PSA,HR Analytic,0.165494,0.109092,0.211028,0.124666,0.039570,0.164236,less_positive_class,0.1
21,MRS,HR Analytic,0.155109,0.089300,0.166271,0.121639,0.041022,0.162662,less_positive_class,0.1
22,FW-MRS-SVM,HR Analytic,0.165494,0.032583,0.172804,0.136545,0.019560,0.156105,less_positive_class,0.1
23,FW-MRS-RF,HR Analytic,0.165494,0.060456,0.168409,0.124643,0.034714,0.159357,less_positive_class,0.1
24,Uniform,Loan,0.693750,0.066125,0.651625,0.386429,0.015094,0.401523,less_positive_class,0.1
25,KMM,Loan,0.693750,0.091000,0.644000,0.385481,0.020298,0.405779,less_positive_class,0.1
26,PSA,Loan,0.693750,0.063875,0.651125,0.395099,0.016051,0.411150,less_positive_class,0.1
27,MRS,Loan,0.693750,0.066375,0.648875,0.382513,0.015622,0.398135,less_positive_class,0.1
28,FW-MRS-SVM,Loan,0.693750,0.129500,0.636750,0.394298,0.031232,0.425531,less_positive_class,0.1
29,FW-MRS-RF,Loan,0.693750,0.081250,0.648000,0.406010,0.019340,0.425350,less_positive_class,0.1
30,Uniform,Diabetes,0.135000,0.076160,0.162380,0.105748,0.033667,0.139415,less_positive_class,0.1
31,KMM,Diabetes,0.135000,0.053230,0.153490,0.106978,0.029184,0.136162,less_positive_class,0.1
32,PSA,Diabetes,0.135000,0.093670,0.171870,0.106273,0.038081,0.144355,less_positive_class,0.1
33,MRS,Diabetes,0.135000,0.070310,0.159390,0.105297,0.031569,0.136866,less_positive_class,0.1
34,FW-MRS-SVM,Diabetes,0.135000,0.096120,0.169300,0.105459,0.036544,0.142003,less_positive_class,0.1
35,FW-MRS-RF,Diabetes,0.135000,0.087590,0.167370,0.105421,0.034893,0.140314,less_positive_class,0.1
36,Uniform,German Credit,0.299401,0.013653,0.298204,0.232248,0.018192,0.250440,less_positive_class,0.1
37,KMM,German Credit,0.299401,0.020120,0.305030,0.249514,0.010533,0.260047,less_positive_class,0.1
38,PSA,German Credit,0.299401,0.024671,0.303353,0.237813,0.018713,0.256526,less_positive_class,0.1
39,MRS,German Credit,0.299401,0.020120,0.298683,0.231053,0.020790,0.251843,less_positive_class,0.1
40,FW-MRS-SVM,German Credit,0.299401,0.048144,0.311257,0.235352,0.025049,0.260401,less_positive_class,0.1
41,FW-MRS-RF,German Credit,0.299401,0.019461,0.301018,0.235346,0.019697,0.255042,less_positive_class,0.1
42,Uniform,Bank Marketing,0.116000,0.013570,0.116890,0.090224,0.013368,0.103592,less_positive_class,0.1
43,KMM,Bank Marketing,0.116000,0.034080,0.131160,0.090166,0.019030,0.109197,less_positive_class,0.1
44,PSA,Bank Marketing,0.116000,0.027100,0.123620,0.092544,0.019676,0.112220,less_positive_class,0.1
45,MRS,Bank Marketing,0.116000,0.013730,0.117190,0.090874,0.013478,0.104352,less_positive_class,0.1
46,FW-MRS-SVM,Bank Marketing,0.116000,0.012450,0.117190,0.093317,0.013513,0.106830,less_positive_class,0.1
47,FW-MRS-RF,Bank Marketing,0.116000,0.013740,0.117420,0.091881,0.014163,0.106044,less_positive_class,0.1

In [17]:
for dataset in data_set_replacer.values():
    bias_01_values = []
    for method in result_df["Method"].unique():
        bias_01 = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]=="less_positive_class") & 
                                            (result_df["Bias Strength"]==0.1) & 
                                            (result_df["Data Set"]==dataset)]["0-1 Bias"].iloc[0]
        bias_01_values.append(round(bias_01, 3))


    print(f"{dataset} \
& {bias_01_values[0]} & {bias_01_values[1]} & {bias_01_values[2]} & {bias_01_values[3]} & {bias_01_values[4]} \
& {bias_01_values[5]}  & \\\\")
print("\n")

Employment & 0.212 & 0.262 & 0.213 & 0.218 & 0.266 & 0.219  & \\
Income & 0.292 & 0.252 & 0.288 & 0.284 & 0.288 & 0.276  & \\
Breast Cancer & 0.048 & 0.031 & 0.035 & 0.035 & 0.044 & 0.048  & \\
HR Analytic & 0.165 & 0.165 & 0.165 & 0.155 & 0.165 & 0.165  & \\
Loan & 0.694 & 0.694 & 0.694 & 0.694 & 0.694 & 0.694  & \\
Diabetes & 0.135 & 0.135 & 0.135 & 0.135 & 0.135 & 0.135  & \\
German Credit & 0.299 & 0.299 & 0.299 & 0.299 & 0.299 & 0.299  & \\
Bank Marketing & 0.116 & 0.116 & 0.116 & 0.116 & 0.116 & 0.116  & \\

In [15]:
for dataset in data_set_replacer.values():
    variance_01_values = []
    for method in result_df["Method"].unique():
        variance_01 = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]=="less_positive_class") & 
                                            (result_df["Bias Strength"]==0.1) & 
                                            (result_df["Data Set"]==dataset)]["0-1 Variance"].iloc[0]
        variance_01_values.append(np.round(variance_01, 3))

    print(f"{dataset} \
& {variance_01_values[0]} & {variance_01_values[1]} & {variance_01_values[2]} & {variance_01_values[3]} & \
{variance_01_values[4]} & {variance_01_values[5]}  &\\\\")
print("\n")

Employment & 0.157 & 0.2 & 0.143 & 0.152 & 0.168 & 0.146  &\\
Income & 0.134 & 0.256 & 0.217 & 0.141 & 0.146 & 0.137  &\\
Breast Cancer & 0.104 & 0.077 & 0.04 & 0.017 & 0.061 & 0.05  &\\
HR Analytic & 0.072 & 0.157 & 0.109 & 0.089 & 0.033 & 0.06  &\\
Loan & 0.066 & 0.091 & 0.064 & 0.066 & 0.13 & 0.081  &\\
Diabetes & 0.076 & 0.053 & 0.094 & 0.07 & 0.096 & 0.088  &\\
German Credit & 0.014 & 0.02 & 0.025 & 0.02 & 0.048 & 0.019  &\\
Bank Marketing & 0.014 & 0.034 & 0.027 & 0.014 & 0.012 & 0.014  &\\

In [20]:
result_df["Rank Bias"] = result_df.round(3).groupby("Data Set")["0-1 Bias"].rank(ascending=True)
result_df["Rank Variance"] = result_df.round(3).groupby("Data Set")["0-1 Variance"].rank(ascending=True)
result_df[["Method", "Rank Bias", "Rank Variance"]].groupby("Method").mean()

            Rank Bias  Rank Variance
Method
FW-MRS-RF      3.6875         2.7500
FW-MRS-SVM     4.0625         4.1250
KMM            3.1250         4.8125
MRS            2.9375         2.7500
PSA            3.3750         3.6250
Uniform        3.8125         2.9375