In [ ]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [2]:
result_path = Path("../results/decomposition")
# methods_list = ["uniform","psa", "kmm", "mrs-forest", "fw-mrs-temperature",  "fw-mrs-temperature-svm", "soft-mrs-linear", "soft-mrs-exponential"]
methods_list = ["uniform","psa", "kmm", "mrs-forest", "fw-mrs-temperature",  "fw-mrs-temperature-svm",]
# bias_types = ["less_negative_class", "less_positive_class", "mean_difference"]
bias_types = ["less_positive_class"]
# less_bias_strengths = ["0.1", "0.2", "0.3"]
less_bias_strengths = ["0.1"]
mean_bias_strengthts = ["0.8", "0.9"]
datasets = ["folktables_employment", "folktables_income", "hr_analytics", "breast_cancer", "loan_prediction"]

In [3]:
aurocs = []
auprcs = []
dict_list = []
for dataset in datasets:
    for bias_type in bias_types:
        for method in methods_list:
            if bias_type == "mean_difference":
                bias_strengths = mean_bias_strengthts
            else : 
                bias_strengths = less_bias_strengths
            for bias_strength in bias_strengths:
                json_file = result_path / dataset / bias_type /  bias_strength/ method / "bias_variance_decomposition.json"
                result_file = pd.read_json(str(json_file))
                dict_list.append(
                    {
                        "Method": method, "Data Set": dataset, 
                        "0-1 Bias": result_file["0-1 loss"]["average_bias"], 
                        "0-1 Variance": result_file["0-1 loss"]["average variance"], 
                        "0-1 Expexted Loss": result_file["0-1 loss"]["average expected loss"],
                        "MSE Bias": result_file["mse loss"]["average_bias"], 
                        "MSE Variance": result_file["mse loss"]["average variance"], 
                        "MSE Expexted Loss": result_file["mse loss"]["average expected loss"],
                        "Bias Type": bias_type, "Bias Strength": bias_strength,
                    }
                                )
result_df = pd.DataFrame(data=dict_list)

In [4]:
result_df = result_df.replace({"uniform": "Uniform", "kmm": "KMM", "psa": "PSA", "mrs-forest": "MRS",
                               "soft-mrs-linear": "Soft-MRS-Linear", "soft-mrs-exponential": "Soft-MRS-Exponential",
                               "fw-mrs-temperature-svm": "FW-MRS-SVM", "fw-mrs-temperature": "FW-MRS-RF"})
result_df

,Method,Data Set,0-1 Bias,0-1 Variance,0-1 Expexted Loss,MSE Bias,MSE Variance,MSE Expexted Loss,Bias Type,Bias Strength
0,Uniform,folktables_employment,0.459000,0.034790,0.433770,0.280569,0.007620,0.288190,less_positive_class,0.1
1,PSA,folktables_employment,0.459000,0.035380,0.432580,0.276896,0.007032,0.283929,less_positive_class,0.1
2,KMM,folktables_employment,0.451500,0.035080,0.431380,0.271521,0.006806,0.278327,less_positive_class,0.1
3,MRS,folktables_employment,0.458500,0.053710,0.420390,0.266761,0.009519,0.276279,less_positive_class,0.1
4,FW-MRS-RF,folktables_employment,0.459000,0.016730,0.448610,0.318456,0.006806,0.325262,less_positive_class,0.1
5,FW-MRS-SVM,folktables_employment,0.459000,0.002560,0.457540,0.351304,0.003751,0.355055,less_positive_class,0.1
6,Uniform,folktables_income,0.441000,0.020260,0.425580,0.295897,0.006191,0.302087,less_positive_class,0.1
7,PSA,folktables_income,0.441000,0.018230,0.426110,0.293069,0.004899,0.297968,less_positive_class,0.1
8,KMM,folktables_income,0.435500,0.022460,0.422200,0.283435,0.005566,0.289001,less_positive_class,0.1
9,MRS,folktables_income,0.440500,0.029660,0.418060,0.288862,0.007476,0.296338,less_positive_class,0.1
10,FW-MRS-RF,folktables_income,0.441000,0.016340,0.428640,0.313537,0.006568,0.320104,less_positive_class,0.1
11,FW-MRS-SVM,folktables_income,0.441000,0.002690,0.438810,0.348674,0.003229,0.351903,less_positive_class,0.1
12,Uniform,hr_analytics,0.165494,0.000375,0.165467,0.143931,0.001343,0.145273,less_positive_class,0.1
13,PSA,hr_analytics,0.165494,0.000663,0.165327,0.143381,0.001511,0.144892,less_positive_class,0.1
14,KMM,hr_analytics,0.165494,0.000704,0.165286,0.143885,0.001596,0.145481,less_positive_class,0.1
15,MRS,hr_analytics,0.165494,0.000730,0.165313,0.143723,0.001388,0.145111,less_positive_class,0.1
16,FW-MRS-RF,hr_analytics,0.165494,0.000931,0.165407,0.145938,0.001746,0.147683,less_positive_class,0.1
17,FW-MRS-SVM,hr_analytics,0.165494,0.001018,0.165347,0.146380,0.002454,0.148834,less_positive_class,0.1
18,Uniform,breast_cancer,0.035088,0.018772,0.045439,0.034935,0.004533,0.039468,less_positive_class,0.1
19,PSA,breast_cancer,0.039474,0.019211,0.044649,0.034211,0.004602,0.038812,less_positive_class,0.1
20,KMM,breast_cancer,0.039474,0.019649,0.045088,0.033827,0.004486,0.038314,less_positive_class,0.1
21,MRS,breast_cancer,0.035088,0.018246,0.040877,0.031926,0.004225,0.036151,less_positive_class,0.1
22,FW-MRS-RF,breast_cancer,0.039474,0.025439,0.048947,0.033517,0.007564,0.041080,less_positive_class,0.1
23,FW-MRS-SVM,breast_cancer,0.043860,0.031491,0.053596,0.034744,0.009853,0.044596,less_positive_class,0.1
24,Uniform,loan_prediction,0.693750,0.050250,0.657750,0.394765,0.013695,0.408460,less_positive_class,0.1
25,PSA,loan_prediction,0.693750,0.053625,0.654625,0.392905,0.015004,0.407909,less_positive_class,0.1
26,KMM,loan_prediction,0.693750,0.046875,0.663625,0.411952,0.015357,0.427309,less_positive_class,0.1
27,MRS,loan_prediction,0.693750,0.058875,0.652125,0.390336,0.015440,0.405776,less_positive_class,0.1
28,FW-MRS-RF,loan_prediction,0.693750,0.044375,0.660875,0.422893,0.015679,0.438572,less_positive_class,0.1
29,FW-MRS-SVM,loan_prediction,0.693750,0.042625,0.667625,0.434395,0.017711,0.452106,less_positive_class,0.1

In [15]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            bias_01_values = []
            for dataset in datasets:
                bias_01 = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["0-1 Bias"].iloc[0]
                bias_01_values.append(round(bias_01, 4))


            print(f"\t& {method} & {bias_01_values[0]} & {bias_01_values[1]} & {bias_01_values[2]} & {bias_01_values[3]} & {bias_01_values[4]} & \\\\")
        print("\n")

less_positive_class, 0.1
	& Uniform & 0.459 & 0.441 & 0.1655 & 0.0351 & 0.6938 & \\
	& PSA & 0.459 & 0.441 & 0.1655 & 0.0395 & 0.6938 & \\
	& KMM & 0.4515 & 0.4355 & 0.1655 & 0.0395 & 0.6938 & \\
	& MRS & 0.4585 & 0.4405 & 0.1655 & 0.0351 & 0.6938 & \\
	& FW-MRS-RF & 0.459 & 0.441 & 0.1655 & 0.0395 & 0.6938 & \\
	& FW-MRS-SVM & 0.459 & 0.441 & 0.1655 & 0.0439 & 0.6938 & \\

In [6]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            variance_01_values = []
            for dataset in datasets:
                variance_01 = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["0-1 Variance"].iloc[0]
                variance_01_values.append(np.round(variance_01, 4))

            print(f"\t& {method} & {variance_01_values[0]} & {variance_01_values[1]} & {variance_01_values[2]} & {variance_01_values[3]} & \
{variance_01_values[4]} & \\\\")
        print("\n")

less_positive_class, 0.1
	& Uniform & 0.0348 & 0.0203 & 0.0004 & 0.0188 & 0.0502 & \\
	& PSA & 0.0354 & 0.0182 & 0.0007 & 0.0192 & 0.0536 & \\
	& KMM & 0.0351 & 0.0225 & 0.0007 & 0.0196 & 0.0469 & \\
	& MRS & 0.0537 & 0.0297 & 0.0007 & 0.0182 & 0.0589 & \\
	& FW-MRS-RF & 0.0167 & 0.0163 & 0.0009 & 0.0254 & 0.0444 & \\
	& FW-MRS-SVM & 0.0026 & 0.0027 & 0.001 & 0.0315 & 0.0426 & \\

In [13]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else: 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            bias_mse_values = []
            for dataset in datasets:
                bias_mse = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["MSE Bias"].iloc[0]
                bias_mse_values.append(np.round(bias_mse, 6))


            print(f"\t & {method} & {bias_mse_values[0]} & {bias_mse_values[1]} & {bias_mse_values[2]} & {bias_mse_values[3]} & {bias_mse_values[4]} & \\\\")
        print("\n")

less_positive_class, 0.1
	 & Uniform & 0.280569 & 0.295897 & 0.143931 & 0.034935 & 0.394765 & \\
	 & PSA & 0.276896 & 0.293069 & 0.143381 & 0.034211 & 0.392905 & \\
	 & KMM & 0.271521 & 0.283435 & 0.143885 & 0.033827 & 0.411952 & \\
	 & MRS & 0.266761 & 0.288862 & 0.143723 & 0.031926 & 0.390336 & \\
	 & FW-MRS-RF & 0.318456 & 0.313537 & 0.145938 & 0.033517 & 0.422893 & \\
	 & FW-MRS-SVM & 0.351304 & 0.348674 & 0.14638 & 0.034744 & 0.434395 & \\

In [12]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else: 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            variance_mse_values = []
            for dataset in datasets:
                variance_mse = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["MSE Variance"].iloc[0]
                variance_mse_values.append(np.round(variance_mse, 6))

            print(f"\t & {method} & {variance_mse_values[0]} & {variance_mse_values[1]} & {variance_mse_values[2]} & {variance_mse_values[3]} & \
{variance_mse_values[4]} & \\\\")
        print("\n")

less_positive_class, 0.1
	 & Uniform & 0.00762 & 0.006191 & 0.001343 & 0.004533 & 0.013695 & \\
	 & PSA & 0.007032 & 0.004899 & 0.001511 & 0.004602 & 0.015004 & \\
	 & KMM & 0.006806 & 0.005566 & 0.001596 & 0.004486 & 0.015357 & \\
	 & MRS & 0.009519 & 0.007476 & 0.001388 & 0.004225 & 0.01544 & \\
	 & FW-MRS-RF & 0.006806 & 0.006568 & 0.001746 & 0.007564 & 0.015679 & \\
	 & FW-MRS-SVM & 0.003751 & 0.003229 & 0.002454 & 0.009853 & 0.017711 & \\

In [9]:
result_df["Rank Bias"] = result_df.groupby("Data Set")["0-1 Bias"].rank(ascending=True)
result_df["Rank Variance"] = result_df.groupby("Data Set")["0-1 Variance"].rank(ascending=True)
result_df[["Method", "Rank Bias", "Rank Variance"]].groupby("Method").mean()

            Rank Bias  Rank Variance
Method
FW-MRS-RF         4.0            3.2
FW-MRS-SVM        4.4            3.0
KMM               2.6            3.8
MRS               2.5            4.6
PSA               4.0            3.6
Uniform           3.5            2.8

In [10]:
result_df["Rank Bias"] = result_df.groupby("Data Set")["MSE Bias"].rank(ascending=True)
result_df["Rank Variance"] = result_df.groupby("Data Set")["MSE Variance"].rank(ascending=True)
result_df[["Method", "Rank Bias", "Rank Variance"]].groupby("Method").mean()

            Rank Bias  Rank Variance
Method
FW-MRS-RF         4.4            4.6
FW-MRS-SVM        5.8            4.0
KMM               2.6            2.8
MRS               1.4            3.8
PSA               2.6            3.0
Uniform           4.2            2.8

In [11]:
result_df["MSE Expexted Loss"] = result_df.groupby("Data Set")["MSE Expexted Loss"].rank(ascending=True)
result_df["0-1 Expexted Loss"] = result_df.groupby("Data Set")["0-1 Expexted Loss"].rank(ascending=True)
result_df[["Method", "MSE Expexted Loss", "0-1 Expexted Loss"]].groupby("Method").mean()

            MSE Expexted Loss  0-1 Expexted Loss
Method
FW-MRS-RF                 5.0                4.8
FW-MRS-SVM                6.0                5.6
KMM                       2.6                2.6
MRS                       1.4                1.2
PSA                       2.4                2.8
Uniform                   3.6                4.0