In [31]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [32]:
result_path = Path("../thesis_results/decomposition")
methods_list = ["uniform","psa", "kmm", "mrs-forest", "soft-mrs-exponential", "fw-mrs-temperature",  "fw-mrs-temperature-svm"]
# bias_types = ["less_negative_class", "less_positive_class", "mean_difference"]
bias_types = ["mean_difference"]
less_bias_strengths = ["0.1"]
mean_bias_strengthts = ["0.8"]
datasets = ["folktables_employment", "folktables_income", "hr_analytics", "breast_cancer", "loan_prediction"]

In [33]:
aurocs = []
auprcs = []
dict_list = []
for dataset in datasets:
    for bias_type in bias_types:
        for method in methods_list:
            if bias_type == "mean_difference":
                bias_strengths = mean_bias_strengthts
            else : 
                bias_strengths = less_bias_strengths
            for bias_strength in bias_strengths:
                json_file = result_path / dataset / bias_type /  bias_strength/ method / "bias_variance_decomposition.json"
                result_file = pd.read_json(str(json_file))
                dict_list.append(
                    {
                        "Method": method, "Data Set": dataset, 
                        "0-1 Bias": result_file["0-1 loss"]["average_bias"], 
                        "0-1 Variance": result_file["0-1 loss"]["average variance"], 
                        "0-1 Expexted Loss": result_file["0-1 loss"]["average expected loss"],
                        "MSE Bias": result_file["mse loss"]["average_bias"], 
                        "MSE Variance": result_file["mse loss"]["average variance"], 
                        "MSE Expexted Loss": result_file["mse loss"]["average expected loss"],
                        "Bias Type": bias_type, "Bias Strength": bias_strength,
                    }
                                )
result_df = pd.DataFrame(data=dict_list)

In [34]:
result_df = result_df.replace({"uniform": "Uniform", "kmm": "KMM", "psa": "PSA", "mrs-forest": "MRS",
                               "soft-mrs-linear": "Soft-MRS-Linear", "soft-mrs-exponential": "Soft-MRS-Exponential",
                               "fw-mrs-temperature-svm": "FW-MRS-SVM", "fw-mrs-temperature": "FW-MRS-RF"})
result_df

,Method,Data Set,0-1 Bias,0-1 Variance,0-1 Expexted Loss,MSE Bias,MSE Variance,MSE Expexted Loss,Bias Type,Bias Strength
0,Uniform,folktables_employment,0.205000,0.037640,0.210780,0.143804,0.002184,0.145988,mean_difference,0.8
1,PSA,folktables_employment,0.200000,0.036340,0.207320,0.143043,0.001978,0.145021,mean_difference,0.8
2,KMM,folktables_employment,0.202000,0.055850,0.214110,0.143857,0.004053,0.147910,mean_difference,0.8
3,MRS,folktables_employment,0.203500,0.039340,0.210240,0.143346,0.002382,0.145728,mean_difference,0.8
4,Soft-MRS-Exponential,folktables_employment,0.198500,0.034520,0.206120,0.144012,0.002188,0.146200,mean_difference,0.8
5,FW-MRS-RF,folktables_employment,0.219500,0.049270,0.225010,0.149847,0.002853,0.152700,mean_difference,0.8
6,FW-MRS-SVM,folktables_employment,0.205000,0.043120,0.212460,0.144399,0.002650,0.147050,mean_difference,0.8
7,Uniform,folktables_income,0.210000,0.062530,0.221790,0.155820,0.002572,0.158391,mean_difference,0.8
8,PSA,folktables_income,0.209500,0.059680,0.218540,0.154956,0.002411,0.157368,mean_difference,0.8
9,KMM,folktables_income,0.211500,0.078650,0.227050,0.155938,0.004312,0.160250,mean_difference,0.8
10,MRS,folktables_income,0.212500,0.064930,0.222670,0.155552,0.002983,0.158535,mean_difference,0.8
11,Soft-MRS-Exponential,folktables_income,0.216000,0.061350,0.219150,0.153597,0.002927,0.156524,mean_difference,0.8
12,FW-MRS-RF,folktables_income,0.222500,0.071120,0.226380,0.158562,0.003485,0.162047,mean_difference,0.8
13,FW-MRS-SVM,folktables_income,0.218500,0.079470,0.228230,0.156245,0.004413,0.160658,mean_difference,0.8
14,Uniform,hr_analytics,0.145059,0.021943,0.145722,0.117003,0.006955,0.123958,mean_difference,0.8
15,PSA,hr_analytics,0.145394,0.018935,0.146278,0.115689,0.005957,0.121646,mean_difference,0.8
16,KMM,hr_analytics,0.144389,0.016590,0.146720,0.120977,0.007352,0.128329,mean_difference,0.8
17,MRS,hr_analytics,0.143384,0.020462,0.145608,0.116743,0.006496,0.123239,mean_difference,0.8
18,Soft-MRS-Exponential,hr_analytics,0.144054,0.019069,0.146827,0.118005,0.007006,0.125010,mean_difference,0.8
19,FW-MRS-RF,hr_analytics,0.143719,0.030479,0.148590,0.119361,0.007570,0.126932,mean_difference,0.8
20,FW-MRS-SVM,hr_analytics,0.143384,0.027946,0.145977,0.107809,0.005729,0.113538,mean_difference,0.8
21,Uniform,breast_cancer,0.021930,0.007544,0.023158,0.021641,0.002831,0.024472,mean_difference,0.8
22,PSA,breast_cancer,0.021930,0.007105,0.023421,0.021593,0.002554,0.024146,mean_difference,0.8
23,KMM,breast_cancer,0.017544,0.009298,0.022982,0.022581,0.003776,0.026357,mean_difference,0.8
24,MRS,breast_cancer,0.021930,0.006316,0.022105,0.020928,0.002547,0.023475,mean_difference,0.8
25,Soft-MRS-Exponential,breast_cancer,0.017544,0.008421,0.023158,0.021804,0.003335,0.025139,mean_difference,0.8
26,FW-MRS-RF,breast_cancer,0.021930,0.010789,0.023947,0.020662,0.003253,0.023915,mean_difference,0.8
27,FW-MRS-SVM,breast_cancer,0.017544,0.013509,0.024035,0.021157,0.004814,0.025970,mean_difference,0.8
28,Uniform,loan_prediction,0.200000,0.032625,0.213875,0.159363,0.008383,0.167746,mean_difference,0.8
29,PSA,loan_prediction,0.200000,0.035750,0.214250,0.160703,0.009073,0.169776,mean_difference,0.8
30,KMM,loan_prediction,0.200000,0.042750,0.223000,0.162568,0.010084,0.172652,mean_difference,0.8
31,MRS,loan_prediction,0.200000,0.040125,0.218875,0.160124,0.009653,0.169777,mean_difference,0.8
32,Soft-MRS-Exponential,loan_prediction,0.200000,0.038375,0.217625,0.162140,0.009413,0.171552,mean_difference,0.8
33,FW-MRS-RF,loan_prediction,0.200000,0.023625,0.211875,0.158250,0.011645,0.169895,mean_difference,0.8
34,FW-MRS-SVM,loan_prediction,0.200000,0.054250,0.225250,0.160794,0.013695,0.174489,mean_difference,0.8

In [35]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            bias_01_values = []
            for dataset in datasets:
                bias_01 = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["0-1 Bias"].iloc[0]
                bias_01_values.append(round(bias_01, 3))


            print(f"\t& {method} & {bias_01_values[0]} & {bias_01_values[1]} & {bias_01_values[2]} & {bias_01_values[3]} & {bias_01_values[4]} & \\\\")
        print("\n")

mean_difference, 0.8
	& Uniform & 0.205 & 0.21 & 0.145 & 0.022 & 0.2 & \\
	& PSA & 0.2 & 0.21 & 0.145 & 0.022 & 0.2 & \\
	& KMM & 0.202 & 0.212 & 0.144 & 0.018 & 0.2 & \\
	& MRS & 0.204 & 0.213 & 0.143 & 0.022 & 0.2 & \\
	& Soft-MRS-Exponential & 0.198 & 0.216 & 0.144 & 0.018 & 0.2 & \\
	& FW-MRS-RF & 0.22 & 0.222 & 0.144 & 0.022 & 0.2 & \\
	& FW-MRS-SVM & 0.205 & 0.218 & 0.143 & 0.018 & 0.2 & \\

In [36]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            variance_01_values = []
            for dataset in datasets:
                variance_01 = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["0-1 Variance"].iloc[0]
                variance_01_values.append(np.round(variance_01, 3))

            print(f"\t& {method} & {variance_01_values[0]} & {variance_01_values[1]} & {variance_01_values[2]} & {variance_01_values[3]} & \
{variance_01_values[4]} & \\\\")
        print("\n")

mean_difference, 0.8
	& Uniform & 0.038 & 0.063 & 0.022 & 0.008 & 0.033 & \\
	& PSA & 0.036 & 0.06 & 0.019 & 0.007 & 0.036 & \\
	& KMM & 0.056 & 0.079 & 0.017 & 0.009 & 0.043 & \\
	& MRS & 0.039 & 0.065 & 0.02 & 0.006 & 0.04 & \\
	& Soft-MRS-Exponential & 0.035 & 0.061 & 0.019 & 0.008 & 0.038 & \\
	& FW-MRS-RF & 0.049 & 0.071 & 0.03 & 0.011 & 0.024 & \\
	& FW-MRS-SVM & 0.043 & 0.079 & 0.028 & 0.014 & 0.054 & \\

In [37]:
result_df["Rank Bias"] = result_df.groupby("Data Set")["0-1 Bias"].rank(ascending=True)
result_df["Rank Variance"] = result_df.groupby("Data Set")["0-1 Variance"].rank(ascending=True)
result_df[["Method", "Rank Bias", "Rank Variance"]].groupby("Method").mean()

                      Rank Bias  Rank Variance
Method
FW-MRS-RF                   5.3            5.0
FW-MRS-SVM                  3.8            6.4
KMM                         3.4            5.0
MRS                         3.8            3.6
PSA                         3.9            2.0
Soft-MRS-Exponential        3.2            2.8
Uniform                     4.6            3.2