In [25]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [26]:
result_path = Path("../results/downstream_task")
# bias_types = ["less_negative_class", "less_positive_class", "mean_difference"]
bias_types = ["less_positive_class"]
metrics = ["AUROC", "AUPRC"]
less_bias_strengths = ["0.1"]
mean_bias_strengthts = ["0.8"]
method_name_replacer = {"uniform": "Uniform", "kmm": "KMM", "psa": "PSA", "mrs-forest": "MRS",
                            # "soft-mrs-exponential": "Soft-MRS-Exponential",
                               "mrs-forest": "MRS", 
                       # "fw-mrs-temperature-svm": "FW-MRS-SVM", 
                        "fw-mrs-temperature": "FW-MRS",
                        "fw-mrs-temperature-negative": "FW-MRS$_{Neg}$",
                        "fw-mrs-temperature-svm": "FW-MRS$_{SVM}$",
                          }
data_set_replacer = {"folktables_employment": "Employment", "folktables_income": "Income",
                               "breast_cancer": "Breast Cancer", "hr_analytics": "HR Analytic", "loan_prediction": "Loan",
                               "diabetes": "Diabetes", "german_credit": "German Credit", "bank_marketing": "Bank Marketing"}

In [27]:
aurocs = []
auprcs = []
dict_list = []
for dataset in data_set_replacer.keys():
    for bias_type in bias_types:
        for method in method_name_replacer.keys():
            if bias_type == "mean_difference":
                bias_strengths = mean_bias_strengthts
            else : 
                bias_strengths = less_bias_strengths
            for bias_strength in bias_strengths:
                json_file = result_path / dataset / bias_type /  bias_strength/ method / "classification_results.json"
                try:
                    result_file = pd.read_json(str(json_file))
                except FileNotFoundError:
                    continue
                dict_list.append(
                    {
                        "Method": method, "Data Set": dataset, 
                        "AUROC Mean": result_file["random forest auroc"]["mean"], 
                        "AUROC Std": result_file["random forest auroc"]["sd"], 
                        "AUPRC Mean": result_file["random forest auprc"]["mean"], 
                        "AUPRC Std": result_file["random forest auprc"]["sd"], 
                        "Bias Type": bias_type, "Bias Strength": bias_strength,
                        "Dropped Samples Mean": result_file["dropped_samples"]["mean"],
                        "Dropped Samples Std": result_file["dropped_samples"]["std"]
                    }
                                )
result_df = pd.DataFrame(data=dict_list)

In [28]:
result_df = result_df.replace(method_name_replacer)
result_df

,Method,Data Set,AUROC Mean,AUROC Std,AUPRC Mean,AUPRC Std,Bias Type,Bias Strength,Dropped Samples Mean,Dropped Samples Std
0,Uniform,folktables_employment,0.870601,0.010491,0.826992,0.017307,less_positive_class,0.1,0.00,0.000000
1,KMM,folktables_employment,0.856631,0.013580,0.808776,0.021985,less_positive_class,0.1,0.00,0.000000
2,PSA,folktables_employment,0.867401,0.010937,0.823689,0.017363,less_positive_class,0.1,0.04,0.280000
3,MRS,folktables_employment,0.868702,0.010788,0.824747,0.017384,less_positive_class,0.1,354.00,74.799733
4,FW-MRS,folktables_employment,0.864302,0.011904,0.819250,0.018954,less_positive_class,0.1,397.50,54.490825
5,FW-MRS$_{Neg}$,folktables_employment,0.873639,0.010306,0.830388,0.016388,less_positive_class,0.1,350.10,77.591817
6,FW-MRS$_{SVM}$,folktables_employment,0.834438,0.013173,0.776956,0.023196,less_positive_class,0.1,271.80,31.044484
7,Uniform,folktables_income,0.838084,0.012878,0.788634,0.020309,less_positive_class,0.1,0.00,0.000000
8,KMM,folktables_income,0.820208,0.014266,0.765446,0.019706,less_positive_class,0.1,0.00,0.000000
9,PSA,folktables_income,0.831057,0.013985,0.780822,0.021689,less_positive_class,0.1,0.16,0.703136
10,MRS,folktables_income,0.836398,0.012073,0.786392,0.019558,less_positive_class,0.1,313.80,55.367499
11,FW-MRS,folktables_income,0.833551,0.013161,0.785542,0.019384,less_positive_class,0.1,328.80,52.664599
12,FW-MRS$_{Neg}$,folktables_income,0.836812,0.012480,0.785795,0.019494,less_positive_class,0.1,308.70,60.339125
13,FW-MRS$_{SVM}$,folktables_income,0.827242,0.015384,0.778617,0.021220,less_positive_class,0.1,293.80,31.961852
14,Uniform,breast_cancer,0.987591,0.006273,0.993799,0.003288,less_positive_class,0.1,0.00,0.000000
15,KMM,breast_cancer,0.989408,0.005247,0.994803,0.002604,less_positive_class,0.1,0.00,0.000000
16,PSA,breast_cancer,0.987893,0.006442,0.994015,0.003248,less_positive_class,0.1,0.00,0.000000
17,MRS,breast_cancer,0.988802,0.005566,0.994663,0.002617,less_positive_class,0.1,53.12,6.035362
18,FW-MRS,breast_cancer,0.986791,0.006654,0.993563,0.003257,less_positive_class,0.1,41.90,9.822932
19,FW-MRS$_{Neg}$,breast_cancer,0.986515,0.007035,0.993247,0.003640,less_positive_class,0.1,42.40,9.472064
20,FW-MRS$_{SVM}$,breast_cancer,0.982593,0.008938,0.990768,0.005948,less_positive_class,0.1,56.08,6.764141
21,Uniform,hr_analytics,0.752772,0.018290,0.455071,0.029285,less_positive_class,0.1,0.00,0.000000
22,KMM,hr_analytics,0.749431,0.019074,0.449147,0.032049,less_positive_class,0.1,0.00,0.000000
23,PSA,hr_analytics,0.750453,0.019049,0.453771,0.034252,less_positive_class,0.1,0.00,0.000000
24,MRS,hr_analytics,0.749303,0.019677,0.449488,0.036120,less_positive_class,0.1,124.90,39.679844
25,FW-MRS,hr_analytics,0.751345,0.018505,0.452117,0.032531,less_positive_class,0.1,125.80,44.758910
26,FW-MRS$_{Neg}$,hr_analytics,0.748392,0.020073,0.451749,0.032503,less_positive_class,0.1,127.20,42.663333
27,FW-MRS$_{SVM}$,hr_analytics,0.751504,0.020317,0.452559,0.038628,less_positive_class,0.1,177.00,69.426220
28,Uniform,loan_prediction,0.658389,0.080697,0.794671,0.050524,less_positive_class,0.1,0.00,0.000000
29,KMM,loan_prediction,0.610365,0.096952,0.776497,0.061962,less_positive_class,0.1,0.00,0.000000
30,PSA,loan_prediction,0.627560,0.095193,0.780323,0.058087,less_positive_class,0.1,0.00,0.000000
31,MRS,loan_prediction,0.647196,0.081763,0.792874,0.052769,less_positive_class,0.1,8.82,5.140778
32,FW-MRS,loan_prediction,0.615731,0.090476,0.780248,0.058839,less_positive_class,0.1,5.50,4.295346
33,FW-MRS$_{Neg}$,loan_prediction,0.677324,0.086606,0.803817,0.057679,less_positive_class,0.1,10.18,4.962620
34,FW-MRS$_{SVM}$,loan_prediction,0.552487,0.070394,0.740471,0.046635,less_positive_class,0.1,4.72,6.026740
35,Uniform,diabetes,0.791498,0.022072,0.371281,0.037717,less_positive_class,0.1,0.00,0.000000
36,KMM,diabetes,0.781169,0.021943,0.357066,0.041765,less_positive_class,0.1,0.00,0.000000
37,PSA,diabetes,0.787277,0.023148,0.367046,0.037046,less_positive_class,0.1,0.00,0.000000
38,MRS,diabetes,0.788985,0.023296,0.366484,0.038332,less_positive_class,0.1,55.10,32.179030
39,FW-MRS,diabetes,0.788148,0.021102,0.365465,0.035373,less_positive_class,0.1,50.30,30.763777
40,FW-MRS$_{Neg}$,diabetes,0.787469,0.022604,0.365998,0.038069,less_positive_class,0.1,64.00,30.805844
41,FW-MRS$_{SVM}$,diabetes,0.783347,0.025240,0.359421,0.038292,less_positive_class,0.1,87.40,34.252591
42,Uniform,german_credit,0.667239,0.053736,0.460906,0.064090,less_positive_class,0.1,0.00,0.000000
43,KMM,german_credit,0.648943,0.052757,0.443033,0.062464,less_positive_class,0.1,0.00,0.000000
44,PSA,german_credit,0.658996,0.055090,0.452393,0.063956,less_positive_class,0.1,0.00,0.000000
45,MRS,german_credit,0.665318,0.056760,0.455774,0.068795,less_positive_class,0.1,14.80,10.390380
46,FW-MRS,german_credit,0.660023,0.058264,0.449507,0.064493,less_positive_class,0.1,11.30,10.526633
47,FW-MRS$_{Neg}$,german_credit,0.666946,0.053617,0.457900,0.064881,less_positive_class,0.1,18.00,11.313708
48,FW-MRS$_{SVM}$,german_credit,0.638839,0.065018,0.435471,0.064144,less_positive_class,0.1,10.10,10.793053
49,Uniform,bank_marketing,0.846908,0.021440,0.465787,0.051725,less_positive_class,0.1,0.00,0.000000
50,KMM,bank_marketing,0.831756,0.026469,0.445607,0.058065,less_positive_class,0.1,0.00,0.000000
51,PSA,bank_marketing,0.839479,0.025952,0.454844,0.048837,less_positive_class,0.1,0.00,0.000000
52,MRS,bank_marketing,0.843858,0.022388,0.466409,0.051351,less_positive_class,0.1,67.60,29.124560
53,FW-MRS,bank_marketing,0.838002,0.024908,0.452531,0.051921,less_positive_class,0.1,73.90,36.909213
54,FW-MRS$_{Neg}$,bank_marketing,0.851231,0.021702,0.469119,0.047594,less_positive_class,0.1,74.40,37.425125
55,FW-MRS$_{SVM}$,bank_marketing,0.834780,0.021560,0.444561,0.054846,less_positive_class,0.1,63.60,36.647510

In [29]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_auroc_values = []
            std_auroc_values = []
            for method in result_df["Method"].unique():
                try:
                    mean_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUROC Mean"].iloc[0]
                    mean_auroc_values.append(np.round(mean_auroc, 3))

                    std_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUROC Std"].iloc[0]
                    std_auroc_values.append(np.round(std_auroc, 2))
                except IndexError:
                    mean_auroc_values.append(0)
                    std_auroc_values.append(0)

            print(f"{data_set_replacer[dataset]} \
& ${mean_auroc_values[0]}\\pm{std_auroc_values[0]}$ \
& ${mean_auroc_values[1]}\\pm{std_auroc_values[1]}$ \
& ${mean_auroc_values[2]}\\pm{std_auroc_values[2]}$ \
& ${mean_auroc_values[3]}\\pm{std_auroc_values[3]}$ \
& ${mean_auroc_values[4]}\\pm{std_auroc_values[4]}$ \
& ${mean_auroc_values[5]}\\pm{std_auroc_values[5]}$ \
\\\\")
        print("\n")

less_positive_class, 0.1
Employment & $0.871\pm0.01$ & $0.857\pm0.01$ & $0.867\pm0.01$ & $0.869\pm0.01$ & $0.864\pm0.01$ & $0.874\pm0.01$ \\
Income & $0.838\pm0.01$ & $0.82\pm0.01$ & $0.831\pm0.01$ & $0.836\pm0.01$ & $0.834\pm0.01$ & $0.837\pm0.01$ \\
Breast Cancer & $0.988\pm0.01$ & $0.989\pm0.01$ & $0.988\pm0.01$ & $0.989\pm0.01$ & $0.987\pm0.01$ & $0.987\pm0.01$ \\
HR Analytic & $0.753\pm0.02$ & $0.749\pm0.02$ & $0.75\pm0.02$ & $0.749\pm0.02$ & $0.751\pm0.02$ & $0.748\pm0.02$ \\
Loan & $0.658\pm0.08$ & $0.61\pm0.1$ & $0.628\pm0.1$ & $0.647\pm0.08$ & $0.616\pm0.09$ & $0.677\pm0.09$ \\
Diabetes & $0.791\pm0.02$ & $0.781\pm0.02$ & $0.787\pm0.02$ & $0.789\pm0.02$ & $0.788\pm0.02$ & $0.787\pm0.02$ \\
German Credit & $0.667\pm0.05$ & $0.649\pm0.05$ & $0.659\pm0.06$ & $0.665\pm0.06$ & $0.66\pm0.06$ & $0.667\pm0.05$ \\
Bank Marketing & $0.847\pm0.02$ & $0.832\pm0.03$ & $0.839\pm0.03$ & $0.844\pm0.02$ & $0.838\pm0.02$ & $0.851\pm0.02$ \\

In [30]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_auprc_values = []
            std_auprc_values = []
            for method in result_df["Method"].unique():
                try:
                    mean_auprc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUPRC Mean"].iloc[0]
                    mean_auprc_values.append(np.round(mean_auprc, 3))

                    std_auprc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUPRC Std"].iloc[0]
                    std_auprc_values.append(np.round(std_auprc, 2))
                except IndexError:
                    mean_auprc_values.append(0)
                    std_auprc_values.append(0)

            print(f"{data_set_replacer[dataset]} \
& ${mean_auprc_values[0]}\\pm{std_auprc_values[0]}$ \
& ${mean_auprc_values[1]}\\pm{std_auprc_values[1]}$ \
& ${mean_auprc_values[2]}\\pm{std_auprc_values[2]}$ \
& ${mean_auprc_values[3]}\\pm{std_auprc_values[3]}$ \
& ${mean_auprc_values[4]}\\pm{std_auprc_values[4]}$ \
& ${mean_auprc_values[5]}\\pm{std_auprc_values[5]}$ \
& \\\\")
        print("\n")

less_positive_class, 0.1
Employment & $0.827\pm0.02$ & $0.809\pm0.02$ & $0.824\pm0.02$ & $0.825\pm0.02$ & $0.819\pm0.02$ & $0.83\pm0.02$ & \\
Income & $0.789\pm0.02$ & $0.765\pm0.02$ & $0.781\pm0.02$ & $0.786\pm0.02$ & $0.786\pm0.02$ & $0.786\pm0.02$ & \\
Breast Cancer & $0.994\pm0.0$ & $0.995\pm0.0$ & $0.994\pm0.0$ & $0.995\pm0.0$ & $0.994\pm0.0$ & $0.993\pm0.0$ & \\
HR Analytic & $0.455\pm0.03$ & $0.449\pm0.03$ & $0.454\pm0.03$ & $0.449\pm0.04$ & $0.452\pm0.03$ & $0.452\pm0.03$ & \\
Loan & $0.795\pm0.05$ & $0.776\pm0.06$ & $0.78\pm0.06$ & $0.793\pm0.05$ & $0.78\pm0.06$ & $0.804\pm0.06$ & \\
Diabetes & $0.371\pm0.04$ & $0.357\pm0.04$ & $0.367\pm0.04$ & $0.366\pm0.04$ & $0.365\pm0.04$ & $0.366\pm0.04$ & \\
German Credit & $0.461\pm0.06$ & $0.443\pm0.06$ & $0.452\pm0.06$ & $0.456\pm0.07$ & $0.45\pm0.06$ & $0.458\pm0.06$ & \\
Bank Marketing & $0.466\pm0.05$ & $0.446\pm0.06$ & $0.455\pm0.05$ & $0.466\pm0.05$ & $0.453\pm0.05$ & $0.469\pm0.05$ & \\

In [31]:
result_df.round(3)

,Method,Data Set,AUROC Mean,AUROC Std,AUPRC Mean,AUPRC Std,Bias Type,Bias Strength,Dropped Samples Mean,Dropped Samples Std
0,Uniform,folktables_employment,0.871,0.010,0.827,0.017,less_positive_class,0.1,0.00,0.000
1,KMM,folktables_employment,0.857,0.014,0.809,0.022,less_positive_class,0.1,0.00,0.000
2,PSA,folktables_employment,0.867,0.011,0.824,0.017,less_positive_class,0.1,0.04,0.280
3,MRS,folktables_employment,0.869,0.011,0.825,0.017,less_positive_class,0.1,354.00,74.800
4,FW-MRS,folktables_employment,0.864,0.012,0.819,0.019,less_positive_class,0.1,397.50,54.491
5,FW-MRS$_{Neg}$,folktables_employment,0.874,0.010,0.830,0.016,less_positive_class,0.1,350.10,77.592
6,FW-MRS$_{SVM}$,folktables_employment,0.834,0.013,0.777,0.023,less_positive_class,0.1,271.80,31.044
7,Uniform,folktables_income,0.838,0.013,0.789,0.020,less_positive_class,0.1,0.00,0.000
8,KMM,folktables_income,0.820,0.014,0.765,0.020,less_positive_class,0.1,0.00,0.000
9,PSA,folktables_income,0.831,0.014,0.781,0.022,less_positive_class,0.1,0.16,0.703
10,MRS,folktables_income,0.836,0.012,0.786,0.020,less_positive_class,0.1,313.80,55.367
11,FW-MRS,folktables_income,0.834,0.013,0.786,0.019,less_positive_class,0.1,328.80,52.665
12,FW-MRS$_{Neg}$,folktables_income,0.837,0.012,0.786,0.019,less_positive_class,0.1,308.70,60.339
13,FW-MRS$_{SVM}$,folktables_income,0.827,0.015,0.779,0.021,less_positive_class,0.1,293.80,31.962
14,Uniform,breast_cancer,0.988,0.006,0.994,0.003,less_positive_class,0.1,0.00,0.000
15,KMM,breast_cancer,0.989,0.005,0.995,0.003,less_positive_class,0.1,0.00,0.000
16,PSA,breast_cancer,0.988,0.006,0.994,0.003,less_positive_class,0.1,0.00,0.000
17,MRS,breast_cancer,0.989,0.006,0.995,0.003,less_positive_class,0.1,53.12,6.035
18,FW-MRS,breast_cancer,0.987,0.007,0.994,0.003,less_positive_class,0.1,41.90,9.823
19,FW-MRS$_{Neg}$,breast_cancer,0.987,0.007,0.993,0.004,less_positive_class,0.1,42.40,9.472
20,FW-MRS$_{SVM}$,breast_cancer,0.983,0.009,0.991,0.006,less_positive_class,0.1,56.08,6.764
21,Uniform,hr_analytics,0.753,0.018,0.455,0.029,less_positive_class,0.1,0.00,0.000
22,KMM,hr_analytics,0.749,0.019,0.449,0.032,less_positive_class,0.1,0.00,0.000
23,PSA,hr_analytics,0.750,0.019,0.454,0.034,less_positive_class,0.1,0.00,0.000
24,MRS,hr_analytics,0.749,0.020,0.449,0.036,less_positive_class,0.1,124.90,39.680
25,FW-MRS,hr_analytics,0.751,0.019,0.452,0.033,less_positive_class,0.1,125.80,44.759
26,FW-MRS$_{Neg}$,hr_analytics,0.748,0.020,0.452,0.033,less_positive_class,0.1,127.20,42.663
27,FW-MRS$_{SVM}$,hr_analytics,0.752,0.020,0.453,0.039,less_positive_class,0.1,177.00,69.426
28,Uniform,loan_prediction,0.658,0.081,0.795,0.051,less_positive_class,0.1,0.00,0.000
29,KMM,loan_prediction,0.610,0.097,0.776,0.062,less_positive_class,0.1,0.00,0.000
30,PSA,loan_prediction,0.628,0.095,0.780,0.058,less_positive_class,0.1,0.00,0.000
31,MRS,loan_prediction,0.647,0.082,0.793,0.053,less_positive_class,0.1,8.82,5.141
32,FW-MRS,loan_prediction,0.616,0.090,0.780,0.059,less_positive_class,0.1,5.50,4.295
33,FW-MRS$_{Neg}$,loan_prediction,0.677,0.087,0.804,0.058,less_positive_class,0.1,10.18,4.963
34,FW-MRS$_{SVM}$,loan_prediction,0.552,0.070,0.740,0.047,less_positive_class,0.1,4.72,6.027
35,Uniform,diabetes,0.791,0.022,0.371,0.038,less_positive_class,0.1,0.00,0.000
36,KMM,diabetes,0.781,0.022,0.357,0.042,less_positive_class,0.1,0.00,0.000
37,PSA,diabetes,0.787,0.023,0.367,0.037,less_positive_class,0.1,0.00,0.000
38,MRS,diabetes,0.789,0.023,0.366,0.038,less_positive_class,0.1,55.10,32.179
39,FW-MRS,diabetes,0.788,0.021,0.365,0.035,less_positive_class,0.1,50.30,30.764
40,FW-MRS$_{Neg}$,diabetes,0.787,0.023,0.366,0.038,less_positive_class,0.1,64.00,30.806
41,FW-MRS$_{SVM}$,diabetes,0.783,0.025,0.359,0.038,less_positive_class,0.1,87.40,34.253
42,Uniform,german_credit,0.667,0.054,0.461,0.064,less_positive_class,0.1,0.00,0.000
43,KMM,german_credit,0.649,0.053,0.443,0.062,less_positive_class,0.1,0.00,0.000
44,PSA,german_credit,0.659,0.055,0.452,0.064,less_positive_class,0.1,0.00,0.000
45,MRS,german_credit,0.665,0.057,0.456,0.069,less_positive_class,0.1,14.80,10.390
46,FW-MRS,german_credit,0.660,0.058,0.450,0.064,less_positive_class,0.1,11.30,10.527
47,FW-MRS$_{Neg}$,german_credit,0.667,0.054,0.458,0.065,less_positive_class,0.1,18.00,11.314
48,FW-MRS$_{SVM}$,german_credit,0.639,0.065,0.435,0.064,less_positive_class,0.1,10.10,10.793
49,Uniform,bank_marketing,0.847,0.021,0.466,0.052,less_positive_class,0.1,0.00,0.000
50,KMM,bank_marketing,0.832,0.026,0.446,0.058,less_positive_class,0.1,0.00,0.000
51,PSA,bank_marketing,0.839,0.026,0.455,0.049,less_positive_class,0.1,0.00,0.000
52,MRS,bank_marketing,0.844,0.022,0.466,0.051,less_positive_class,0.1,67.60,29.125
53,FW-MRS,bank_marketing,0.838,0.025,0.453,0.052,less_positive_class,0.1,73.90,36.909
54,FW-MRS$_{Neg}$,bank_marketing,0.851,0.022,0.469,0.048,less_positive_class,0.1,74.40,37.425
55,FW-MRS$_{SVM}$,bank_marketing,0.835,0.022,0.445,0.055,less_positive_class,0.1,63.60,36.648

In [32]:
result_df["Rank AUROC"] = result_df.round(3).groupby("Data Set")["AUROC Mean"].rank(ascending=False)
result_df["Rank AUPRC"] = result_df.round(3).groupby("Data Set")["AUPRC Mean"].rank(ascending=False)
result_df[["Method", "Rank AUROC", "Rank AUPRC"]].groupby("Method").mean()

                Rank AUROC  Rank AUPRC
Method
FW-MRS              4.3125      4.5000
FW-MRS$_{Neg}$      2.9375      2.7500
FW-MRS$_{SVM}$      6.0000      6.2500
KMM                 5.7500      5.7500
MRS                 3.0000      3.2500
PSA                 4.2500      3.6875
Uniform             1.7500      1.8125