In [1]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [2]:
result_path = Path("../results/decomposition")
method_name_replacer = {"uniform": "Uniform", 
                        "psa": "PSA",
                        "kmm": "KMM", 
                        "mrs-forest": "MRS", 
                        "fw-mrs-temperature": "FW-MRS-RF",
                        "fw-mrs-temperature-svm": "FW-MRS-SVM", 
                        }
data_set_replacer = {
                    "diabetes", 
                    "folktables_employment", 
                    "folktables_income",
                    "bank_marketing",
                    "hr_analytics", 
                    "german_credit", 
                    "breast_cancer", 
                    "loan_prediction",
                    }

In [3]:
aurocs = []
auprcs = []
dict_list = []
for dataset in data_set_replacer:
        for method in method_name_replacer.keys():
            json_file = result_path / dataset / "less_positive_class" /  "0.1" / method / "bias_variance_decomposition.json"
            try:
                result_file = pd.read_json(str(json_file))
            except FileNotFoundError:
                continue
            dict_list.append(
                {
                    "Method": method, 
                    "Data Set": dataset, 
                    "0-1 Bias": result_file["0-1 loss"]["average_bias"], 
                    "0-1 Variance": result_file["0-1 loss"]["average variance"], 
                    "0-1 Expexted Loss": result_file["0-1 loss"]["average expected loss"],
                    "MSE Bias": result_file["mse loss"]["average_bias"], 
                    "MSE Variance": result_file["mse loss"]["average variance"], 
                    "MSE Expexted Loss": result_file["mse loss"]["average expected loss"],
                    "Bias Type": "less_positive_class", 
                    "Bias Strength": 0.1,
                }
                            )
result_df = pd.DataFrame(data=dict_list)

In [4]:
result_df = result_df.replace(method_name_replacer)
result_df = result_df.replace(data_set_replacer)
result_df

/tmp/ipykernel_2960425/2054981413.py:2: FutureWarning: DataFrame.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  result_df = result_df.replace(data_set_replacer)

,Method,Data Set,0-1 Bias,0-1 Variance,0-1 Expexted Loss,MSE Bias,MSE Variance,MSE Expexted Loss,Bias Type,Bias Strength
0,Uniform,breast_cancer,0.048246,0.103947,0.135526,0.051059,0.024326,0.075385,less_positive_class,0.1
1,PSA,breast_cancer,0.035088,0.039912,0.062193,0.033548,0.013049,0.046597,less_positive_class,0.1
2,KMM,breast_cancer,0.030702,0.077193,0.092807,0.034225,0.028599,0.062824,less_positive_class,0.1
3,MRS,breast_cancer,0.035088,0.017281,0.041140,0.035879,0.010112,0.045991,less_positive_class,0.1
4,FW-MRS-RF,breast_cancer,0.048246,0.054649,0.074649,0.043570,0.027454,0.071024,less_positive_class,0.1
5,FW-MRS-SVM,breast_cancer,0.039474,0.071930,0.092281,0.042802,0.028958,0.071760,less_positive_class,0.1
6,Uniform,hr_analytics,0.165494,0.071638,0.164449,0.122202,0.039756,0.161958,less_positive_class,0.1
7,PSA,hr_analytics,0.165494,0.109092,0.211028,0.124666,0.039570,0.164236,less_positive_class,0.1
8,KMM,hr_analytics,0.164824,0.157387,0.228489,0.121698,0.043718,0.165417,less_positive_class,0.1
9,MRS,hr_analytics,0.165494,0.077280,0.163685,0.121590,0.039533,0.161123,less_positive_class,0.1
10,FW-MRS-RF,hr_analytics,0.165494,0.066734,0.167571,0.122528,0.035455,0.157983,less_positive_class,0.1
11,FW-MRS-SVM,hr_analytics,0.165494,0.059658,0.170492,0.125393,0.034561,0.159954,less_positive_class,0.1
12,Uniform,german_credit,0.299401,0.013653,0.298204,0.232248,0.018192,0.250440,less_positive_class,0.1
13,PSA,german_credit,0.299401,0.024671,0.303353,0.237813,0.018713,0.256526,less_positive_class,0.1
14,KMM,german_credit,0.299401,0.020120,0.305030,0.249514,0.010533,0.260047,less_positive_class,0.1
15,MRS,german_credit,0.299401,0.020120,0.298683,0.231053,0.020790,0.251843,less_positive_class,0.1
16,FW-MRS-RF,german_credit,0.299401,0.017964,0.300240,0.238288,0.019541,0.257829,less_positive_class,0.1
17,FW-MRS-SVM,german_credit,0.299401,0.038323,0.309461,0.238888,0.022442,0.261330,less_positive_class,0.1
18,Uniform,bank_marketing,0.116000,0.013570,0.116890,0.090224,0.013368,0.103592,less_positive_class,0.1
19,PSA,bank_marketing,0.116000,0.027100,0.123620,0.092544,0.019676,0.112220,less_positive_class,0.1
20,KMM,bank_marketing,0.116000,0.034080,0.131160,0.090166,0.019030,0.109197,less_positive_class,0.1
21,MRS,bank_marketing,0.116000,0.015710,0.117690,0.089889,0.014732,0.104621,less_positive_class,0.1
22,FW-MRS-RF,bank_marketing,0.116000,0.011270,0.117090,0.093871,0.012117,0.105988,less_positive_class,0.1
23,FW-MRS-SVM,bank_marketing,0.116000,0.009690,0.115910,0.093062,0.011377,0.104439,less_positive_class,0.1
24,Uniform,folktables_income,0.292000,0.133660,0.307180,0.188564,0.017233,0.205797,less_positive_class,0.1
25,PSA,folktables_income,0.288000,0.217420,0.329120,0.196681,0.032110,0.228791,less_positive_class,0.1
26,KMM,folktables_income,0.252000,0.256330,0.329710,0.187343,0.036644,0.223986,less_positive_class,0.1
27,MRS,folktables_income,0.283000,0.131310,0.301690,0.184421,0.015272,0.199693,less_positive_class,0.1
28,FW-MRS-RF,folktables_income,0.303000,0.135670,0.316870,0.193700,0.018277,0.211977,less_positive_class,0.1
29,FW-MRS-SVM,folktables_income,0.296500,0.149960,0.315640,0.194680,0.021375,0.216056,less_positive_class,0.1
30,Uniform,folktables_employment,0.211500,0.157220,0.264080,0.164226,0.014898,0.179124,less_positive_class,0.1
31,PSA,folktables_employment,0.212500,0.143360,0.250840,0.158117,0.012214,0.170331,less_positive_class,0.1
32,KMM,folktables_employment,0.261500,0.200220,0.302880,0.173607,0.021788,0.195394,less_positive_class,0.1
33,MRS,folktables_employment,0.214500,0.138250,0.249670,0.158285,0.009557,0.167842,less_positive_class,0.1
34,FW-MRS-RF,folktables_employment,0.221500,0.150900,0.261840,0.162383,0.011552,0.173935,less_positive_class,0.1
35,FW-MRS-SVM,folktables_employment,0.223000,0.122000,0.245500,0.160148,0.005641,0.165789,less_positive_class,0.1
36,Uniform,loan_prediction,0.693750,0.066125,0.651625,0.386429,0.015094,0.401523,less_positive_class,0.1
37,PSA,loan_prediction,0.693750,0.063875,0.651125,0.395099,0.016051,0.411150,less_positive_class,0.1
38,KMM,loan_prediction,0.693750,0.091000,0.644000,0.385481,0.020298,0.405779,less_positive_class,0.1
39,MRS,loan_prediction,0.693750,0.066375,0.648875,0.382513,0.015622,0.398135,less_positive_class,0.1
40,FW-MRS-RF,loan_prediction,0.693750,0.094875,0.639625,0.397787,0.022092,0.419879,less_positive_class,0.1
41,FW-MRS-SVM,loan_prediction,0.693750,0.088375,0.646875,0.400088,0.021934,0.422022,less_positive_class,0.1
42,Uniform,diabetes,0.135000,0.076160,0.162380,0.105748,0.033667,0.139415,less_positive_class,0.1
43,PSA,diabetes,0.135000,0.093670,0.171870,0.106273,0.038081,0.144355,less_positive_class,0.1
44,KMM,diabetes,0.135000,0.053230,0.153490,0.106978,0.029184,0.136162,less_positive_class,0.1
45,MRS,diabetes,0.135000,0.074670,0.160650,0.105034,0.032678,0.137712,less_positive_class,0.1
46,FW-MRS-RF,diabetes,0.135000,0.066470,0.158050,0.104691,0.029864,0.134555,less_positive_class,0.1
47,FW-MRS-SVM,diabetes,0.135000,0.092570,0.167730,0.105656,0.036617,0.142273,less_positive_class,0.1

In [5]:
for dataset in data_set_replacer:
    bias_01_values = []
    for method in result_df["Method"].unique():
        bias_01 = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]=="less_positive_class") & 
                                            (result_df["Bias Strength"]==0.1) & 
                                            (result_df["Data Set"]==dataset)]["0-1 Bias"].iloc[0]
        bias_01_values.append(round(bias_01, 3))


    print(f"{dataset} \
& {bias_01_values[0]} & {bias_01_values[1]} & {bias_01_values[2]} & {bias_01_values[3]} & {bias_01_values[4]} \
& {bias_01_values[5]}  & \\\\")
print("\n")

breast_cancer & 0.048 & 0.035 & 0.031 & 0.035 & 0.048 & 0.039  & \\
hr_analytics & 0.165 & 0.165 & 0.165 & 0.165 & 0.165 & 0.165  & \\
german_credit & 0.299 & 0.299 & 0.299 & 0.299 & 0.299 & 0.299  & \\
bank_marketing & 0.116 & 0.116 & 0.116 & 0.116 & 0.116 & 0.116  & \\
folktables_income & 0.292 & 0.288 & 0.252 & 0.283 & 0.303 & 0.297  & \\
folktables_employment & 0.212 & 0.213 & 0.262 & 0.215 & 0.222 & 0.223  & \\
loan_prediction & 0.694 & 0.694 & 0.694 & 0.694 & 0.694 & 0.694  & \\
diabetes & 0.135 & 0.135 & 0.135 & 0.135 & 0.135 & 0.135  & \\

In [6]:
for dataset in data_set_replacer:
    variance_01_values = []
    for method in result_df["Method"].unique():
        variance_01 = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]=="less_positive_class") & 
                                            (result_df["Bias Strength"]==0.1) & 
                                            (result_df["Data Set"]==dataset)]["0-1 Variance"].iloc[0]
        variance_01_values.append(np.round(variance_01, 3))

    print(f"{dataset} \
& {variance_01_values[0]} & {variance_01_values[1]} & {variance_01_values[2]} & {variance_01_values[3]} & \
{variance_01_values[4]} & {variance_01_values[5]}  &\\\\")
print("\n")

breast_cancer & 0.104 & 0.04 & 0.077 & 0.017 & 0.055 & 0.072  &\\
hr_analytics & 0.072 & 0.109 & 0.157 & 0.077 & 0.067 & 0.06  &\\
german_credit & 0.014 & 0.025 & 0.02 & 0.02 & 0.018 & 0.038  &\\
bank_marketing & 0.014 & 0.027 & 0.034 & 0.016 & 0.011 & 0.01  &\\
folktables_income & 0.134 & 0.217 & 0.256 & 0.131 & 0.136 & 0.15  &\\
folktables_employment & 0.157 & 0.143 & 0.2 & 0.138 & 0.151 & 0.122  &\\
loan_prediction & 0.066 & 0.064 & 0.091 & 0.066 & 0.095 & 0.088  &\\
diabetes & 0.076 & 0.094 & 0.053 & 0.075 & 0.066 & 0.093  &\\

In [7]:
result_df["Rank Bias"] = result_df.round(3).groupby("Data Set")["0-1 Bias"].rank(ascending=True)
result_df["Rank Variance"] = result_df.round(3).groupby("Data Set")["0-1 Variance"].rank(ascending=True)
result_df[["Method", "Rank Bias", "Rank Variance"]].groupby("Method").mean()

            Rank Bias  Rank Variance
Method
FW-MRS-RF      4.1250         3.0000
FW-MRS-SVM     3.9375         3.2500
KMM            3.1875         4.8125
MRS            3.1250         2.6250
PSA            3.1250         4.0000
Uniform        3.5000         3.3125