In [119]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [120]:
result_path = Path("../thesis_results/downstream_task")
methods_list = ["uniform","psa", "kmm", "mrs-forest", 
               # "soft-mrs-exponential", 
                "fw-mrs-temperature_old",  
                "fw-mrs-temperature-svm_old",
                "fw-mrs-temperature",  "fw-mrs-temperature-svm",
                "fw-mrs-temperature-svm_soft_threshold", "fw-mrs-temperature_soft_threshold", "mrs-forest_soft_threshold"
                ]
# bias_types = ["less_negative_class", "less_positive_class", "mean_difference"]
bias_types = ["less_positive_class"]
metrics = ["AUROC", "AUPRC"]
# less_bias_strengths = ["0.1", "0.2", "0.3"]
less_bias_strengths = ["0.1"]
mean_bias_strengthts = ["0.8"]
datasets = ["folktables_employment", "folktables_income", "hr_analytics", "breast_cancer", "loan_prediction"]
method_name_replacer = {"uniform": "Uniform", "kmm": "KMM", "psa": "PSA", "mrs-forest": "MRS",
                            # "soft-mrs-exponential": "Soft-MRS-Exponential",
                               "mrs-forest": "MRS", "fw-mrs-temperature_old": "FW-MRS-RF-Abs", "fw-mrs-temperature-svm_old": "FW-MRS-SVM-Abs",
                        "fw-mrs-temperature-svm": "FW-MRS-SVM-Signed", "fw-mrs-temperature": "FW-MRS-RF-Signed",
                          "fw-mrs-temperature-svm_soft_threshold": "FW-MRS-SVM-DA", "fw-mrs-temperature_soft_threshold": "FW-MRS-RF-DA",
                          "mrs-forest_soft_threshold": "MRS-DA",
                          }

In [121]:
aurocs = []
auprcs = []
dict_list = []
for dataset in datasets:
    for bias_type in bias_types:
        for method in methods_list:
            if bias_type == "mean_difference":
                bias_strengths = mean_bias_strengthts
            else : 
                bias_strengths = less_bias_strengths
            for bias_strength in bias_strengths:
                json_file = result_path / dataset / bias_type /  bias_strength/ method / "classification_results.json"
                try:
                    result_file = pd.read_json(str(json_file))
                except FileNotFoundError:
                    continue
                dict_list.append(
                    {
                        "Method": method, "Data Set": dataset, 
                        "AUROC Mean": result_file["random forest auroc"]["mean"], 
                        "AUROC Std": result_file["random forest auroc"]["sd"], 
                        "AUPRC Mean": result_file["random forest auprc"]["mean"], 
                        "AUPRC Std": result_file["random forest auprc"]["sd"], 
                        "Bias Type": bias_type, "Bias Strength": bias_strength,
                        "Dropped Samples Mean": result_file["dropped_samples"]["mean"],
                        "Dropped Samples Std": result_file["dropped_samples"]["std"]
                    }
                                )
result_df = pd.DataFrame(data=dict_list)

In [122]:
result_df = result_df.replace(method_name_replacer)
result_df

,Method,Data Set,AUROC Mean,AUROC Std,AUPRC Mean,AUPRC Std,Bias Type,Bias Strength,Dropped Samples Mean,Dropped Samples Std
0,Uniform,folktables_employment,0.870831,0.010040,0.827021,0.016671,less_positive_class,0.1,0.00,0.000000
1,PSA,folktables_employment,0.867464,0.010494,0.823775,0.016330,less_positive_class,0.1,0.04,0.280000
2,KMM,folktables_employment,0.856957,0.012656,0.809232,0.019908,less_positive_class,0.1,0.00,0.000000
3,MRS,folktables_employment,0.870307,0.010000,0.826587,0.016147,less_positive_class,0.1,176.60,29.264996
4,FW-MRS-RF-Abs,folktables_employment,0.840812,0.012290,0.787853,0.020694,less_positive_class,0.1,149.80,29.865699
5,FW-MRS-SVM-Abs,folktables_employment,0.855381,0.014431,0.809600,0.021618,less_positive_class,0.1,242.80,32.575451
6,FW-MRS-RF-Signed,folktables_employment,0.873373,0.008801,0.831082,0.013719,less_positive_class,0.1,347.70,125.144756
7,FW-MRS-SVM-Signed,folktables_employment,0.868225,0.010563,0.824525,0.017159,less_positive_class,0.1,276.30,33.133216
8,Uniform,folktables_income,0.838550,0.012914,0.788787,0.018468,less_positive_class,0.1,0.00,0.000000
9,PSA,folktables_income,0.831214,0.013329,0.780784,0.019630,less_positive_class,0.1,0.12,0.430813
10,KMM,folktables_income,0.819583,0.014123,0.764315,0.019958,less_positive_class,0.1,0.00,0.000000
11,MRS,folktables_income,0.839169,0.012828,0.789868,0.018501,less_positive_class,0.1,178.00,56.053546
12,FW-MRS-RF-Abs,folktables_income,0.821514,0.016011,0.773798,0.023070,less_positive_class,0.1,141.50,35.598455
13,FW-MRS-SVM-Abs,folktables_income,0.827335,0.014279,0.778599,0.019422,less_positive_class,0.1,278.30,29.010515
14,FW-MRS-RF-Signed,folktables_income,0.839668,0.010883,0.790135,0.016937,less_positive_class,0.1,258.50,93.574836
15,FW-MRS-SVM-Signed,folktables_income,0.834222,0.012678,0.784541,0.019032,less_positive_class,0.1,304.80,38.392187
16,Uniform,hr_analytics,0.752031,0.018491,0.456449,0.033274,less_positive_class,0.1,0.00,0.000000
17,PSA,hr_analytics,0.752660,0.019536,0.457528,0.032741,less_positive_class,0.1,0.00,0.000000
18,KMM,hr_analytics,0.746169,0.019057,0.442272,0.036634,less_positive_class,0.1,0.00,0.000000
19,MRS,hr_analytics,0.753169,0.018477,0.456705,0.030572,less_positive_class,0.1,72.30,48.064644
20,FW-MRS-RF-Abs,hr_analytics,0.749625,0.020111,0.454143,0.036519,less_positive_class,0.1,19.80,23.515102
21,FW-MRS-SVM-Abs,hr_analytics,0.743386,0.024199,0.435751,0.046091,less_positive_class,0.1,113.70,72.434867
22,FW-MRS-RF-Signed,hr_analytics,0.751474,0.018379,0.457186,0.031733,less_positive_class,0.1,107.10,45.575103
23,FW-MRS-SVM-Signed,hr_analytics,0.750367,0.019714,0.452739,0.031031,less_positive_class,0.1,155.20,89.476030
24,FW-MRS-RF-DA,hr_analytics,0.749010,0.019613,0.452065,0.036582,less_positive_class,0.1,69.60,47.873166
25,MRS-DA,hr_analytics,0.751008,0.019673,0.454541,0.037001,less_positive_class,0.1,68.80,44.671691
26,Uniform,breast_cancer,0.987829,0.006468,0.993861,0.003357,less_positive_class,0.1,0.00,0.000000
27,PSA,breast_cancer,0.988082,0.006246,0.994121,0.003116,less_positive_class,0.1,0.00,0.000000
28,KMM,breast_cancer,0.989602,0.005644,0.994860,0.002788,less_positive_class,0.1,0.00,0.000000
29,MRS,breast_cancer,0.989216,0.005663,0.994912,0.002626,less_positive_class,0.1,58.42,5.539278
30,FW-MRS-RF-Abs,breast_cancer,0.988742,0.006121,0.994575,0.002980,less_positive_class,0.1,56.92,6.124835
31,FW-MRS-SVM-Abs,breast_cancer,0.986040,0.006975,0.992918,0.004677,less_positive_class,0.1,60.22,7.707892
32,FW-MRS-RF-Signed,breast_cancer,0.988551,0.005946,0.994478,0.002875,less_positive_class,0.1,60.30,5.717517
33,FW-MRS-SVM-Signed,breast_cancer,0.986964,0.006091,0.993793,0.003023,less_positive_class,0.1,64.04,11.394665
34,FW-MRS-RF-DA,breast_cancer,0.987429,0.006579,0.993642,0.003376,less_positive_class,0.1,12.34,21.016765
35,MRS-DA,breast_cancer,0.987781,0.006604,0.993833,0.003432,less_positive_class,0.1,13.04,20.558171
36,Uniform,loan_prediction,0.671851,0.074621,0.803920,0.048397,less_positive_class,0.1,0.00,0.000000
37,PSA,loan_prediction,0.647647,0.088693,0.793913,0.056209,less_positive_class,0.1,0.00,0.000000
38,KMM,loan_prediction,0.619544,0.083723,0.782096,0.052815,less_positive_class,0.1,0.00,0.000000
39,MRS,loan_prediction,0.655860,0.077066,0.795562,0.049798,less_positive_class,0.1,7.10,5.212485
40,FW-MRS-RF-Abs,loan_prediction,0.558766,0.073201,0.742404,0.052110,less_positive_class,0.1,2.80,4.142463
41,FW-MRS-SVM-Abs,loan_prediction,0.536307,0.089082,0.730430,0.056537,less_positive_class,0.1,5.80,6.409368
42,FW-MRS-RF-Signed,loan_prediction,0.701427,0.071088,0.815119,0.048150,less_positive_class,0.1,12.48,5.204767
43,FW-MRS-SVM-Signed,loan_prediction,0.709926,0.066869,0.813232,0.046954,less_positive_class,0.1,8.58,5.889278
44,FW-MRS-SVM-DA,loan_prediction,0.558308,0.088770,0.745985,0.058786,less_positive_class,0.1,2.98,4.478794
45,FW-MRS-RF-DA,loan_prediction,0.705770,0.066317,0.815994,0.046971,less_positive_class,0.1,6.32,6.156103
46,MRS-DA,loan_prediction,0.670626,0.071560,0.805659,0.047137,less_positive_class,0.1,4.90,4.387482

In [123]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            mean_auroc_values = []
            std_auroc_values = []
            for dataset in datasets:
                try:
                    mean_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUROC Mean"].iloc[0]
                    mean_auroc_values.append(np.round(mean_auroc, 3))

                    std_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUROC Std"].iloc[0]
                    std_auroc_values.append(np.round(std_auroc, 2))
                except IndexError:
                    mean_auroc_values.append(0)
                    std_auroc_values.append(0)

            print(f"\t& {method} \
& ${mean_auroc_values[0]}\\pm{std_auroc_values[0]}$ \
& ${mean_auroc_values[1]}\\pm{std_auroc_values[1]}$ \
& ${mean_auroc_values[2]}\\pm{std_auroc_values[2]}$ \
& ${mean_auroc_values[3]}\\pm{std_auroc_values[3]}$ \
& ${mean_auroc_values[4]}\\pm{std_auroc_values[4]}$ & \\\\")
        print("\n")

less_positive_class, 0.1
	& Uniform & $0.871\pm0.01$ & $0.839\pm0.01$ & $0.752\pm0.02$ & $0.988\pm0.01$ & $0.672\pm0.07$ & \\
	& PSA & $0.867\pm0.01$ & $0.831\pm0.01$ & $0.753\pm0.02$ & $0.988\pm0.01$ & $0.648\pm0.09$ & \\
	& KMM & $0.857\pm0.01$ & $0.82\pm0.01$ & $0.746\pm0.02$ & $0.99\pm0.01$ & $0.62\pm0.08$ & \\
	& MRS & $0.87\pm0.01$ & $0.839\pm0.01$ & $0.753\pm0.02$ & $0.989\pm0.01$ & $0.656\pm0.08$ & \\
	& FW-MRS-RF-Abs & $0.841\pm0.01$ & $0.822\pm0.02$ & $0.75\pm0.02$ & $0.989\pm0.01$ & $0.559\pm0.07$ & \\
	& FW-MRS-SVM-Abs & $0.855\pm0.01$ & $0.827\pm0.01$ & $0.743\pm0.02$ & $0.986\pm0.01$ & $0.536\pm0.09$ & \\
	& FW-MRS-RF-Signed & $0.873\pm0.01$ & $0.84\pm0.01$ & $0.751\pm0.02$ & $0.989\pm0.01$ & $0.701\pm0.07$ & \\
	& FW-MRS-SVM-Signed & $0.868\pm0.01$ & $0.834\pm0.01$ & $0.75\pm0.02$ & $0.987\pm0.01$ & $0.71\pm0.07$ & \\
	& FW-MRS-RF-DA & $0\pm0$ & $0\pm0$ & $0.749\pm0.02$ & $0.987\pm0.01$ & $0.706\pm0.07$ & \\
	& MRS-DA & $0\pm0$ & $0\pm0$ & $0.751\pm0.02$ & $0.988\pm0.01$ & $0.671\pm0.07$ & \\
	& FW-MRS-SVM-DA & $0\pm0$ & $0\pm0$ & $0\pm0$ & $0\pm0$ & $0.558\pm0.09$ & \\

In [124]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            mean_auprc_values = []
            std_auprc_values = []
            for dataset in datasets:
                try:
                    mean_auprc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUPRC Mean"].iloc[0]
                    mean_auprc_values.append(np.round(mean_auprc, 3))

                    std_auprc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUPRC Std"].iloc[0]
                    std_auprc_values.append(np.round(std_auprc, 2))
                except IndexError:
                    mean_auprc_values.append(0)
                    std_auprc_values.append(0)

            print(f"\t& {method} \
& ${mean_auprc_values[0]}\\pm{std_auprc_values[0]}$ \
& ${mean_auprc_values[1]}\\pm{std_auprc_values[1]}$ \
& ${mean_auprc_values[2]}\\pm{std_auprc_values[2]}$ \
& ${mean_auprc_values[3]}\\pm{std_auprc_values[3]}$ \
& ${mean_auprc_values[4]}\\pm{std_auprc_values[4]}$ & \\\\")
        print("\n")

less_positive_class, 0.1
	& Uniform & $0.827\pm0.02$ & $0.789\pm0.02$ & $0.456\pm0.03$ & $0.994\pm0.0$ & $0.804\pm0.05$ & \\
	& PSA & $0.824\pm0.02$ & $0.781\pm0.02$ & $0.458\pm0.03$ & $0.994\pm0.0$ & $0.794\pm0.06$ & \\
	& KMM & $0.809\pm0.02$ & $0.764\pm0.02$ & $0.442\pm0.04$ & $0.995\pm0.0$ & $0.782\pm0.05$ & \\
	& MRS & $0.827\pm0.02$ & $0.79\pm0.02$ & $0.457\pm0.03$ & $0.995\pm0.0$ & $0.796\pm0.05$ & \\
	& FW-MRS-RF-Abs & $0.788\pm0.02$ & $0.774\pm0.02$ & $0.454\pm0.04$ & $0.995\pm0.0$ & $0.742\pm0.05$ & \\
	& FW-MRS-SVM-Abs & $0.81\pm0.02$ & $0.779\pm0.02$ & $0.436\pm0.05$ & $0.993\pm0.0$ & $0.73\pm0.06$ & \\
	& FW-MRS-RF-Signed & $0.831\pm0.01$ & $0.79\pm0.02$ & $0.457\pm0.03$ & $0.994\pm0.0$ & $0.815\pm0.05$ & \\
	& FW-MRS-SVM-Signed & $0.825\pm0.02$ & $0.785\pm0.02$ & $0.453\pm0.03$ & $0.994\pm0.0$ & $0.813\pm0.05$ & \\
	& FW-MRS-RF-DA & $0\pm0$ & $0\pm0$ & $0.452\pm0.04$ & $0.994\pm0.0$ & $0.816\pm0.05$ & \\
	& MRS-DA & $0\pm0$ & $0\pm0$ & $0.455\pm0.04$ & $0.994\pm0.0$ & $0.806\pm0.05$ & \\
	& FW-MRS-SVM-DA & $0\pm0$ & $0\pm0$ & $0\pm0$ & $0\pm0$ & $0.746\pm0.06$ & \\

In [125]:
result_df["Rank AUROC"] = result_df.groupby("Data Set")["AUROC Mean"].rank(ascending=False)
result_df["Rank AUPRC"] = result_df.groupby("Data Set")["AUPRC Mean"].rank(ascending=False)
result_df[["Method", "Rank AUROC", "Rank AUPRC"]].groupby("Method").mean()

                   Rank AUROC  Rank AUPRC
Method
FW-MRS-RF-Abs        6.800000    6.800000
FW-MRS-RF-DA         6.000000    6.000000
FW-MRS-RF-Signed     2.600000    2.000000
FW-MRS-SVM-Abs       8.800000    8.600000
FW-MRS-SVM-DA       10.000000    9.000000
FW-MRS-SVM-Signed    4.800000    5.200000
KMM                  6.400000    6.800000
MRS                  2.800000    3.000000
MRS-DA               5.666667    5.333333
PSA                  4.800000    4.600000
Uniform              3.600000    4.000000