In [41]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [42]:
result_path = Path("../results/downstream_task")
bias_types = ["less_positive_class"]
metrics = ["AUROC", "AUPRC"]
less_bias_strengths = ["0.1"]
method_name_replacer = {
                        "uniform": "Uniform", 
                        "kmm": "KMM", 
                        "psa": "PSA", 
                        "mrs-forest": "MRS", 
                        "fw-mrs-temperature": "FW-MRS",
                        "fw-mrs-temperature-svm": "FW-MRS$_{SVM}$",
                        }
data_set_replacer = {
                    "folktables_employment": "Employment", 
                    "folktables_income": "Income",
                    "breast_cancer": "Breast Cancer", 
                    "hr_analytics": "HR Analytic", 
                    "loan_prediction": "Loan",
                    "diabetes": "Diabetes", 
                    "german_credit": "German Credit", 
                    "bank_marketing": "Bank Marketing"
                    }

In [43]:
aurocs = []
auprcs = []
dict_list = []
for dataset in data_set_replacer.keys():
    for bias_type in bias_types:
        for method in method_name_replacer.keys():
            for bias_strength in less_bias_strengths:
                json_file = result_path / dataset / bias_type /  bias_strength/ method / "classification_results.json"
                try:
                    result_file = pd.read_json(str(json_file))
                except FileNotFoundError:
                    continue
                dict_list.append(
                    {
                        "Method": method, "Data Set": dataset, 
                        "AUROC Mean": result_file["random forest auroc"]["mean"], 
                        "AUROC Std": result_file["random forest auroc"]["sd"], 
                        "AUPRC Mean": result_file["random forest auprc"]["mean"], 
                        "AUPRC Std": result_file["random forest auprc"]["sd"], 
                        "Bias Type": bias_type, "Bias Strength": bias_strength,
                        "Dropped Samples Mean": result_file["dropped_samples"]["mean"],
                        "Dropped Samples Std": result_file["dropped_samples"]["std"],
                        "SVM PAD Mean": result_file["svm pad"]["mean"],
                        "SVM PAD Std": result_file["svm pad"]["sd"],
                        "RF Domain AUROC Mean": result_file["rf domain auroc"]["mean"],
                        "RF Domain AUROC Std": result_file["rf domain auroc"]["sd"],
                    }
                                )
result_df = pd.DataFrame(data=dict_list)

In [44]:
result_df = result_df.replace(method_name_replacer)
result_df

,Method,Data Set,AUROC Mean,AUROC Std,AUPRC Mean,AUPRC Std,Bias Type,Bias Strength,Dropped Samples Mean,Dropped Samples Std,SVM PAD Mean,SVM PAD Std,RF Domain AUROC Mean,RF Domain AUROC Std
0,Uniform,folktables_employment,0.870601,0.010491,0.826992,0.017307,less_positive_class,0.1,0.000000,0.000000,0.357066,0.036606,0.630367,0.010368
1,KMM,folktables_employment,0.856631,0.013580,0.808776,0.021985,less_positive_class,0.1,0.000000,0.000000,0.099177,0.023438,0.525253,0.008685
2,PSA,folktables_employment,0.867401,0.010937,0.823689,0.017363,less_positive_class,0.1,0.040000,0.280000,0.042419,0.011849,0.528106,0.009637
3,MRS,folktables_employment,0.869954,0.009992,0.826332,0.015344,less_positive_class,0.1,203.900000,35.061232,0.289446,0.041109,0.602020,0.012732
4,FW-MRS,folktables_employment,0.868157,0.010889,0.822983,0.017228,less_positive_class,0.1,191.428571,36.860188,0.297351,0.040298,0.605088,0.011545
5,FW-MRS$_{SVM}$,folktables_employment,0.863267,0.012314,0.816441,0.020302,less_positive_class,0.1,267.321429,33.739605,0.147522,0.045246,0.578940,0.012643
6,Uniform,folktables_income,0.838084,0.012878,0.788634,0.020309,less_positive_class,0.1,0.000000,0.000000,0.352737,0.041463,0.612679,0.014196
7,KMM,folktables_income,0.820208,0.014266,0.765446,0.019706,less_positive_class,0.1,0.000000,0.000000,0.092928,0.026392,0.527638,0.007296
8,PSA,folktables_income,0.831057,0.013985,0.780822,0.021689,less_positive_class,0.1,0.160000,0.703136,0.044959,0.014487,0.519376,0.007730
9,MRS,folktables_income,0.837651,0.013005,0.787525,0.019839,less_positive_class,0.1,199.400000,49.138987,0.285773,0.052469,0.587054,0.018934
10,FW-MRS,folktables_income,0.834900,0.014257,0.786557,0.021070,less_positive_class,0.1,196.166667,50.772094,0.268338,0.054428,0.585275,0.016443
11,FW-MRS$_{SVM}$,folktables_income,0.832934,0.013416,0.784748,0.018757,less_positive_class,0.1,299.516129,31.324391,0.115897,0.036646,0.570213,0.015680
12,Uniform,breast_cancer,0.987591,0.006273,0.993799,0.003288,less_positive_class,0.1,0.000000,0.000000,0.934375,0.049196,0.730549,0.017786
13,KMM,breast_cancer,0.989408,0.005247,0.994803,0.002604,less_positive_class,0.1,0.000000,0.000000,0.141982,0.048100,0.592115,0.028551
14,PSA,breast_cancer,0.987893,0.006442,0.994015,0.003248,less_positive_class,0.1,0.000000,0.000000,0.369868,0.087313,0.583283,0.027643
15,MRS,breast_cancer,0.988525,0.006004,0.994553,0.002780,less_positive_class,0.1,53.060000,6.300508,0.668194,0.085055,0.648704,0.029313
16,FW-MRS,breast_cancer,0.979907,0.011535,0.988631,0.007692,less_positive_class,0.1,39.711111,10.590608,0.511007,0.162268,0.659397,0.031133
17,FW-MRS$_{SVM}$,breast_cancer,0.976183,0.015126,0.986204,0.009559,less_positive_class,0.1,50.500000,9.269124,0.359305,0.133758,0.673908,0.047014
18,Uniform,hr_analytics,0.752772,0.018290,0.455071,0.029285,less_positive_class,0.1,0.000000,0.000000,0.103957,0.028068,0.532918,0.008788
19,KMM,hr_analytics,0.749431,0.019074,0.449147,0.032049,less_positive_class,0.1,0.000000,0.000000,0.036428,0.011798,0.514326,0.005495
20,PSA,hr_analytics,0.750453,0.019049,0.453771,0.034252,less_positive_class,0.1,0.000000,0.000000,0.035252,0.012651,0.511088,0.004514
21,MRS,hr_analytics,0.751373,0.019375,0.452664,0.032756,less_positive_class,0.1,105.300000,58.020772,0.085924,0.025301,0.526627,0.007657
22,FW-MRS,hr_analytics,0.749659,0.019565,0.450323,0.037120,less_positive_class,0.1,104.852941,46.739033,0.087501,0.024930,0.524549,0.006799
23,FW-MRS$_{SVM}$,hr_analytics,0.751250,0.021326,0.452175,0.041478,less_positive_class,0.1,164.333333,78.440352,0.083578,0.030133,0.526884,0.008302
24,Uniform,loan_prediction,0.658389,0.080697,0.794671,0.050524,less_positive_class,0.1,0.000000,0.000000,0.350333,0.106762,0.570285,0.030109
25,KMM,loan_prediction,0.610365,0.096952,0.776497,0.061962,less_positive_class,0.1,0.000000,0.000000,0.246098,0.060627,0.585211,0.023742
26,PSA,loan_prediction,0.627560,0.095193,0.780323,0.058087,less_positive_class,0.1,0.000000,0.000000,0.171968,0.054509,0.553523,0.020760
27,MRS,loan_prediction,0.637731,0.097225,0.788255,0.058505,less_positive_class,0.1,8.420000,5.366899,0.281149,0.101353,0.550919,0.017978
28,FW-MRS,loan_prediction,0.612096,0.091994,0.776554,0.056211,less_positive_class,0.1,3.920000,3.520455,0.244441,0.109491,0.552784,0.023472
29,FW-MRS$_{SVM}$,loan_prediction,0.581692,0.095651,0.756347,0.059458,less_positive_class,0.1,5.651163,4.481921,0.204909,0.084229,0.550852,0.020139
30,Uniform,diabetes,0.791498,0.022072,0.371281,0.037717,less_positive_class,0.1,0.000000,0.000000,0.105814,0.034614,0.524808,0.009243
31,KMM,diabetes,0.781169,0.021943,0.357066,0.041765,less_positive_class,0.1,0.000000,0.000000,0.044013,0.011766,0.521981,0.007816
32,PSA,diabetes,0.787277,0.023148,0.367046,0.037046,less_positive_class,0.1,0.000000,0.000000,0.037124,0.010159,0.512270,0.003703
33,MRS,diabetes,0.789326,0.023831,0.367978,0.038977,less_positive_class,0.1,39.600000,32.493692,0.095200,0.036402,0.522293,0.009748
34,FW-MRS,diabetes,0.788723,0.021246,0.362004,0.033155,less_positive_class,0.1,41.463415,35.047771,0.091332,0.031646,0.520329,0.009308
35,FW-MRS$_{SVM}$,diabetes,0.787443,0.025526,0.361890,0.040404,less_positive_class,0.1,72.361111,38.468712,0.080915,0.028881,0.518148,0.005201
36,Uniform,german_credit,0.667239,0.053736,0.460906,0.064090,less_positive_class,0.1,0.000000,0.000000,0.157752,0.067674,0.538268,0.015928
37,KMM,german_credit,0.648943,0.052757,0.443033,0.062464,less_positive_class,0.1,0.000000,0.000000,0.116224,0.041402,0.546872,0.015067
38,PSA,german_credit,0.658996,0.055090,0.452393,0.063956,less_positive_class,0.1,0.000000,0.000000,0.090296,0.026323,0.532806,0.009209
39,MRS,german_credit,0.668462,0.054647,0.457961,0.068650,less_positive_class,0.1,12.800000,11.452511,0.141130,0.056958,0.533510,0.011700
40,FW-MRS,german_credit,0.642997,0.063204,0.438424,0.067489,less_positive_class,0.1,7.708333,11.224895,0.123126,0.065430,0.530930,0.011531
41,FW-MRS$_{SVM}$,german_credit,0.668423,0.037054,0.467843,0.087021,less_positive_class,0.1,2.500000,2.500000,0.077331,0.004943,0.523364,0.006287
42,Uniform,bank_marketing,0.846908,0.021440,0.465787,0.051725,less_positive_class,0.1,0.000000,0.000000,0.080367,0.032421,0.522693,0.008734
43,KMM,bank_marketing,0.831756,0.026469,0.445607,0.058065,less_positive_class,0.1,0.000000,0.000000,0.063037,0.021513,0.521086,0.006660
44,PSA,bank_marketing,0.839479,0.025952,0.454844,0.048837,less_positive_class,0.1,0.000000,0.000000,0.036807,0.011388,0.512231,0.003996
45,MRS,bank_marketing,0.845635,0.021468,0.469522,0.050810,less_positive_class,0.1,58.800000,35.207386,0.065461,0.024151,0.516828,0.006621
46,FW-MRS,bank_marketing,0.845221,0.020324,0.458972,0.051379,less_positive_class,0.1,52.083333,30.101103,0.074830,0.028358,0.519161,0.007346
47,FW-MRS$_{SVM}$,bank_marketing,0.839128,0.019026,0.444848,0.054392,less_positive_class,0.1,66.250000,26.309456,0.064304,0.023603,0.517411,0.006352

In [45]:
for bias_type in bias_types:
    for bias_strength in less_bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_auroc_values = []
            std_auroc_values = []
            for method in result_df["Method"].unique():
                try:
                    mean_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUROC Mean"].iloc[0]
                    mean_auroc_values.append(np.round(mean_auroc, 3))

                    std_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUROC Std"].iloc[0]
                    std_auroc_values.append(np.round(std_auroc, 2))
                except IndexError:
                    mean_auroc_values.append(0)
                    std_auroc_values.append(0)

            print(f"{data_set_replacer[dataset]} \
& ${mean_auroc_values[0]}\\pm{std_auroc_values[0]}$ \
& ${mean_auroc_values[1]}\\pm{std_auroc_values[1]}$ \
& ${mean_auroc_values[2]}\\pm{std_auroc_values[2]}$ \
& ${mean_auroc_values[3]}\\pm{std_auroc_values[3]}$ \
& ${mean_auroc_values[4]}\\pm{std_auroc_values[4]}$ \
& ${mean_auroc_values[5]}\\pm{std_auroc_values[5]}$ \
\\\\")
        print("\n")

less_positive_class, 0.1
Employment & $0.871\pm0.01$ & $0.857\pm0.01$ & $0.867\pm0.01$ & $0.87\pm0.01$ & $0.868\pm0.01$ & $0.863\pm0.01$ \\
Income & $0.838\pm0.01$ & $0.82\pm0.01$ & $0.831\pm0.01$ & $0.838\pm0.01$ & $0.835\pm0.01$ & $0.833\pm0.01$ \\
Breast Cancer & $0.988\pm0.01$ & $0.989\pm0.01$ & $0.988\pm0.01$ & $0.989\pm0.01$ & $0.98\pm0.01$ & $0.976\pm0.02$ \\
HR Analytic & $0.753\pm0.02$ & $0.749\pm0.02$ & $0.75\pm0.02$ & $0.751\pm0.02$ & $0.75\pm0.02$ & $0.751\pm0.02$ \\
Loan & $0.658\pm0.08$ & $0.61\pm0.1$ & $0.628\pm0.1$ & $0.638\pm0.1$ & $0.612\pm0.09$ & $0.582\pm0.1$ \\
Diabetes & $0.791\pm0.02$ & $0.781\pm0.02$ & $0.787\pm0.02$ & $0.789\pm0.02$ & $0.789\pm0.02$ & $0.787\pm0.03$ \\
German Credit & $0.667\pm0.05$ & $0.649\pm0.05$ & $0.659\pm0.06$ & $0.668\pm0.05$ & $0.643\pm0.06$ & $0.668\pm0.04$ \\
Bank Marketing & $0.847\pm0.02$ & $0.832\pm0.03$ & $0.839\pm0.03$ & $0.846\pm0.02$ & $0.845\pm0.02$ & $0.839\pm0.02$ \\

In [46]:
for bias_type in bias_types:
    for bias_strength in less_bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_auprc_values = []
            std_auprc_values = []
            for method in result_df["Method"].unique():
                try:
                    mean_auprc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUPRC Mean"].iloc[0]
                    mean_auprc_values.append(np.round(mean_auprc, 3))

                    std_auprc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUPRC Std"].iloc[0]
                    std_auprc_values.append(np.round(std_auprc, 2))
                except IndexError:
                    mean_auprc_values.append(0)
                    std_auprc_values.append(0)

            print(f"{data_set_replacer[dataset]} \
& ${mean_auprc_values[0]}\\pm{std_auprc_values[0]}$ \
& ${mean_auprc_values[1]}\\pm{std_auprc_values[1]}$ \
& ${mean_auprc_values[2]}\\pm{std_auprc_values[2]}$ \
& ${mean_auprc_values[3]}\\pm{std_auprc_values[3]}$ \
& ${mean_auprc_values[4]}\\pm{std_auprc_values[4]}$ \
& ${mean_auprc_values[5]}\\pm{std_auprc_values[5]}$ \
& \\\\")
        print("\n")

less_positive_class, 0.1
Employment & $0.827\pm0.02$ & $0.809\pm0.02$ & $0.824\pm0.02$ & $0.826\pm0.02$ & $0.823\pm0.02$ & $0.816\pm0.02$ & \\
Income & $0.789\pm0.02$ & $0.765\pm0.02$ & $0.781\pm0.02$ & $0.788\pm0.02$ & $0.787\pm0.02$ & $0.785\pm0.02$ & \\
Breast Cancer & $0.994\pm0.0$ & $0.995\pm0.0$ & $0.994\pm0.0$ & $0.995\pm0.0$ & $0.989\pm0.01$ & $0.986\pm0.01$ & \\
HR Analytic & $0.455\pm0.03$ & $0.449\pm0.03$ & $0.454\pm0.03$ & $0.453\pm0.03$ & $0.45\pm0.04$ & $0.452\pm0.04$ & \\
Loan & $0.795\pm0.05$ & $0.776\pm0.06$ & $0.78\pm0.06$ & $0.788\pm0.06$ & $0.777\pm0.06$ & $0.756\pm0.06$ & \\
Diabetes & $0.371\pm0.04$ & $0.357\pm0.04$ & $0.367\pm0.04$ & $0.368\pm0.04$ & $0.362\pm0.03$ & $0.362\pm0.04$ & \\
German Credit & $0.461\pm0.06$ & $0.443\pm0.06$ & $0.452\pm0.06$ & $0.458\pm0.07$ & $0.438\pm0.07$ & $0.468\pm0.09$ & \\
Bank Marketing & $0.466\pm0.05$ & $0.446\pm0.06$ & $0.455\pm0.05$ & $0.47\pm0.05$ & $0.459\pm0.05$ & $0.445\pm0.05$ & \\

In [47]:
for bias_type in bias_types:
    for bias_strength in less_bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_pad_values = []
            std_pad_values = []
            for method in result_df["Method"].unique():
                try:
                    mean_pad = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["SVM PAD Mean"].iloc[0]
                    mean_pad_values.append(np.round(mean_pad, 3))

                    std_pad = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["SVM PAD Std"].iloc[0]
                    std_pad_values.append(np.round(std_pad, 2))
                except IndexError:
                    mean_pad_values.append(0)
                    std_pad_values.append(0)

            print(f"{data_set_replacer[dataset]} \
& ${mean_pad_values[0]}\\pm{std_pad_values[0]}$ \
& ${mean_pad_values[1]}\\pm{std_pad_values[1]}$ \
& ${mean_pad_values[2]}\\pm{std_pad_values[2]}$ \
& ${mean_pad_values[3]}\\pm{std_pad_values[3]}$ \
& ${mean_pad_values[4]}\\pm{std_pad_values[4]}$ \
& ${mean_pad_values[5]}\\pm{std_pad_values[5]}$ \
& \\\\")
        print("\n")

less_positive_class, 0.1
Employment & $0.357\pm0.04$ & $0.099\pm0.02$ & $0.042\pm0.01$ & $0.289\pm0.04$ & $0.297\pm0.04$ & $0.148\pm0.05$ & \\
Income & $0.353\pm0.04$ & $0.093\pm0.03$ & $0.045\pm0.01$ & $0.286\pm0.05$ & $0.268\pm0.05$ & $0.116\pm0.04$ & \\
Breast Cancer & $0.934\pm0.05$ & $0.142\pm0.05$ & $0.37\pm0.09$ & $0.668\pm0.09$ & $0.511\pm0.16$ & $0.359\pm0.13$ & \\
HR Analytic & $0.104\pm0.03$ & $0.036\pm0.01$ & $0.035\pm0.01$ & $0.086\pm0.03$ & $0.088\pm0.02$ & $0.084\pm0.03$ & \\
Loan & $0.35\pm0.11$ & $0.246\pm0.06$ & $0.172\pm0.05$ & $0.281\pm0.1$ & $0.244\pm0.11$ & $0.205\pm0.08$ & \\
Diabetes & $0.106\pm0.03$ & $0.044\pm0.01$ & $0.037\pm0.01$ & $0.095\pm0.04$ & $0.091\pm0.03$ & $0.081\pm0.03$ & \\
German Credit & $0.158\pm0.07$ & $0.116\pm0.04$ & $0.09\pm0.03$ & $0.141\pm0.06$ & $0.123\pm0.07$ & $0.077\pm0.0$ & \\
Bank Marketing & $0.08\pm0.03$ & $0.063\pm0.02$ & $0.037\pm0.01$ & $0.065\pm0.02$ & $0.075\pm0.03$ & $0.064\pm0.02$ & \\

In [48]:
for bias_type in bias_types:
    for bias_strength in less_bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_domain_values = []
            std_domain_values = []
            for method in result_df["Method"].unique():
                try:
                    mean_domain = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["RF Domain AUROC Mean"].iloc[0]
                    mean_domain_values.append(np.round(mean_domain, 3))

                    std_domain = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["RF Domain AUROC Std"].iloc[0]
                    std_domain_values.append(np.round(std_domain, 2))
                except IndexError:
                    mean_domain_values.append(0)
                    std_domain_values.append(0)

            print(f"{data_set_replacer[dataset]} \
& ${mean_domain_values[0]}\\pm{std_domain_values[0]}$ \
& ${mean_domain_values[1]}\\pm{std_domain_values[1]}$ \
& ${mean_domain_values[2]}\\pm{std_domain_values[2]}$ \
& ${mean_domain_values[3]}\\pm{std_domain_values[3]}$ \
& ${mean_domain_values[4]}\\pm{std_domain_values[4]}$ \
& ${mean_domain_values[5]}\\pm{std_domain_values[5]}$ \
& \\\\")
        print("\n")

less_positive_class, 0.1

Employment & $0.63\pm0.01$ & $0.525\pm0.01$ & $0.528\pm0.01$ & $0.602\pm0.01$ & $0.605\pm0.01$ & $0.579\pm0.01$ & \\
Income & $0.613\pm0.01$ & $0.528\pm0.01$ & $0.519\pm0.01$ & $0.587\pm0.02$ & $0.585\pm0.02$ & $0.57\pm0.02$ & \\
Breast Cancer & $0.731\pm0.02$ & $0.592\pm0.03$ & $0.583\pm0.03$ & $0.649\pm0.03$ & $0.659\pm0.03$ & $0.674\pm0.05$ & \\
HR Analytic & $0.533\pm0.01$ & $0.514\pm0.01$ & $0.511\pm0.0$ & $0.527\pm0.01$ & $0.525\pm0.01$ & $0.527\pm0.01$ & \\
Loan & $0.57\pm0.03$ & $0.585\pm0.02$ & $0.554\pm0.02$ & $0.551\pm0.02$ & $0.553\pm0.02$ & $0.551\pm0.02$ & \\
Diabetes & $0.525\pm0.01$ & $0.522\pm0.01$ & $0.512\pm0.0$ & $0.522\pm0.01$ & $0.52\pm0.01$ & $0.518\pm0.01$ & \\
German Credit & $0.538\pm0.02$ & $0.547\pm0.02$ & $0.533\pm0.01$ & $0.534\pm0.01$ & $0.531\pm0.01$ & $0.523\pm0.01$ & \\
Bank Marketing & $0.523\pm0.01$ & $0.521\pm0.01$ & $0.512\pm0.0$ & $0.517\pm0.01$ & $0.519\pm0.01$ & $0.517\pm0.01$ & \\

In [49]:
result_df.round(3)

,Method,Data Set,AUROC Mean,AUROC Std,AUPRC Mean,AUPRC Std,Bias Type,Bias Strength,Dropped Samples Mean,Dropped Samples Std,SVM PAD Mean,SVM PAD Std,RF Domain AUROC Mean,RF Domain AUROC Std
0,Uniform,folktables_employment,0.871,0.010,0.827,0.017,less_positive_class,0.1,0.000,0.000,0.357,0.037,0.630,0.010
1,KMM,folktables_employment,0.857,0.014,0.809,0.022,less_positive_class,0.1,0.000,0.000,0.099,0.023,0.525,0.009
2,PSA,folktables_employment,0.867,0.011,0.824,0.017,less_positive_class,0.1,0.040,0.280,0.042,0.012,0.528,0.010
3,MRS,folktables_employment,0.870,0.010,0.826,0.015,less_positive_class,0.1,203.900,35.061,0.289,0.041,0.602,0.013
4,FW-MRS,folktables_employment,0.868,0.011,0.823,0.017,less_positive_class,0.1,191.429,36.860,0.297,0.040,0.605,0.012
5,FW-MRS$_{SVM}$,folktables_employment,0.863,0.012,0.816,0.020,less_positive_class,0.1,267.321,33.740,0.148,0.045,0.579,0.013
6,Uniform,folktables_income,0.838,0.013,0.789,0.020,less_positive_class,0.1,0.000,0.000,0.353,0.041,0.613,0.014
7,KMM,folktables_income,0.820,0.014,0.765,0.020,less_positive_class,0.1,0.000,0.000,0.093,0.026,0.528,0.007
8,PSA,folktables_income,0.831,0.014,0.781,0.022,less_positive_class,0.1,0.160,0.703,0.045,0.014,0.519,0.008
9,MRS,folktables_income,0.838,0.013,0.788,0.020,less_positive_class,0.1,199.400,49.139,0.286,0.052,0.587,0.019
10,FW-MRS,folktables_income,0.835,0.014,0.787,0.021,less_positive_class,0.1,196.167,50.772,0.268,0.054,0.585,0.016
11,FW-MRS$_{SVM}$,folktables_income,0.833,0.013,0.785,0.019,less_positive_class,0.1,299.516,31.324,0.116,0.037,0.570,0.016
12,Uniform,breast_cancer,0.988,0.006,0.994,0.003,less_positive_class,0.1,0.000,0.000,0.934,0.049,0.731,0.018
13,KMM,breast_cancer,0.989,0.005,0.995,0.003,less_positive_class,0.1,0.000,0.000,0.142,0.048,0.592,0.029
14,PSA,breast_cancer,0.988,0.006,0.994,0.003,less_positive_class,0.1,0.000,0.000,0.370,0.087,0.583,0.028
15,MRS,breast_cancer,0.989,0.006,0.995,0.003,less_positive_class,0.1,53.060,6.301,0.668,0.085,0.649,0.029
16,FW-MRS,breast_cancer,0.980,0.012,0.989,0.008,less_positive_class,0.1,39.711,10.591,0.511,0.162,0.659,0.031
17,FW-MRS$_{SVM}$,breast_cancer,0.976,0.015,0.986,0.010,less_positive_class,0.1,50.500,9.269,0.359,0.134,0.674,0.047
18,Uniform,hr_analytics,0.753,0.018,0.455,0.029,less_positive_class,0.1,0.000,0.000,0.104,0.028,0.533,0.009
19,KMM,hr_analytics,0.749,0.019,0.449,0.032,less_positive_class,0.1,0.000,0.000,0.036,0.012,0.514,0.005
20,PSA,hr_analytics,0.750,0.019,0.454,0.034,less_positive_class,0.1,0.000,0.000,0.035,0.013,0.511,0.005
21,MRS,hr_analytics,0.751,0.019,0.453,0.033,less_positive_class,0.1,105.300,58.021,0.086,0.025,0.527,0.008
22,FW-MRS,hr_analytics,0.750,0.020,0.450,0.037,less_positive_class,0.1,104.853,46.739,0.088,0.025,0.525,0.007
23,FW-MRS$_{SVM}$,hr_analytics,0.751,0.021,0.452,0.041,less_positive_class,0.1,164.333,78.440,0.084,0.030,0.527,0.008
24,Uniform,loan_prediction,0.658,0.081,0.795,0.051,less_positive_class,0.1,0.000,0.000,0.350,0.107,0.570,0.030
25,KMM,loan_prediction,0.610,0.097,0.776,0.062,less_positive_class,0.1,0.000,0.000,0.246,0.061,0.585,0.024
26,PSA,loan_prediction,0.628,0.095,0.780,0.058,less_positive_class,0.1,0.000,0.000,0.172,0.055,0.554,0.021
27,MRS,loan_prediction,0.638,0.097,0.788,0.059,less_positive_class,0.1,8.420,5.367,0.281,0.101,0.551,0.018
28,FW-MRS,loan_prediction,0.612,0.092,0.777,0.056,less_positive_class,0.1,3.920,3.520,0.244,0.109,0.553,0.023
29,FW-MRS$_{SVM}$,loan_prediction,0.582,0.096,0.756,0.059,less_positive_class,0.1,5.651,4.482,0.205,0.084,0.551,0.020
30,Uniform,diabetes,0.791,0.022,0.371,0.038,less_positive_class,0.1,0.000,0.000,0.106,0.035,0.525,0.009
31,KMM,diabetes,0.781,0.022,0.357,0.042,less_positive_class,0.1,0.000,0.000,0.044,0.012,0.522,0.008
32,PSA,diabetes,0.787,0.023,0.367,0.037,less_positive_class,0.1,0.000,0.000,0.037,0.010,0.512,0.004
33,MRS,diabetes,0.789,0.024,0.368,0.039,less_positive_class,0.1,39.600,32.494,0.095,0.036,0.522,0.010
34,FW-MRS,diabetes,0.789,0.021,0.362,0.033,less_positive_class,0.1,41.463,35.048,0.091,0.032,0.520,0.009
35,FW-MRS$_{SVM}$,diabetes,0.787,0.026,0.362,0.040,less_positive_class,0.1,72.361,38.469,0.081,0.029,0.518,0.005
36,Uniform,german_credit,0.667,0.054,0.461,0.064,less_positive_class,0.1,0.000,0.000,0.158,0.068,0.538,0.016
37,KMM,german_credit,0.649,0.053,0.443,0.062,less_positive_class,0.1,0.000,0.000,0.116,0.041,0.547,0.015
38,PSA,german_credit,0.659,0.055,0.452,0.064,less_positive_class,0.1,0.000,0.000,0.090,0.026,0.533,0.009
39,MRS,german_credit,0.668,0.055,0.458,0.069,less_positive_class,0.1,12.800,11.453,0.141,0.057,0.534,0.012
40,FW-MRS,german_credit,0.643,0.063,0.438,0.067,less_positive_class,0.1,7.708,11.225,0.123,0.065,0.531,0.012
41,FW-MRS$_{SVM}$,german_credit,0.668,0.037,0.468,0.087,less_positive_class,0.1,2.500,2.500,0.077,0.005,0.523,0.006
42,Uniform,bank_marketing,0.847,0.021,0.466,0.052,less_positive_class,0.1,0.000,0.000,0.080,0.032,0.523,0.009
43,KMM,bank_marketing,0.832,0.026,0.446,0.058,less_positive_class,0.1,0.000,0.000,0.063,0.022,0.521,0.007
44,PSA,bank_marketing,0.839,0.026,0.455,0.049,less_positive_class,0.1,0.000,0.000,0.037,0.011,0.512,0.004
45,MRS,bank_marketing,0.846,0.021,0.470,0.051,less_positive_class,0.1,58.800,35.207,0.065,0.024,0.517,0.007
46,FW-MRS,bank_marketing,0.845,0.020,0.459,0.051,less_positive_class,0.1,52.083,30.101,0.075,0.028,0.519,0.007
47,FW-MRS$_{SVM}$,bank_marketing,0.839,0.019,0.445,0.054,less_positive_class,0.1,66.250,26.309,0.064,0.024,0.517,0.006

In [50]:
result_df["Rank AUROC"] = result_df.round(3).groupby("Data Set")["AUROC Mean"].rank(ascending=False)
result_df["Rank AUPRC"] = result_df.round(3).groupby("Data Set")["AUPRC Mean"].rank(ascending=False)
result_df["Rank PAD"] = result_df.round(3).groupby("Data Set")["SVM PAD Mean"].rank(ascending=True)
result_df["Rank Domain"] = result_df.round(3).groupby("Data Set")["RF Domain AUROC Mean"].rank(ascending=True)
result_df[["Method", "Rank AUROC", "Rank AUPRC", "Rank PAD", "Rank Domain"]].groupby("Method").mean()

                Rank AUROC  Rank AUPRC  Rank PAD  Rank Domain
Method
FW-MRS              3.8750      4.3125     4.250       3.5000
FW-MRS$_{SVM}$      4.2500      4.5625     2.500       2.8125
KMM                 5.1875      5.0625     2.250       3.5625
MRS                 1.9375      2.0625     4.625       3.6250
PSA                 4.1250      3.4375     1.375       1.7500
Uniform             1.6250      1.5625     6.000       5.7500