In [31]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [32]:
result_path = Path("../results/downstream_task")
bias_types = ["less_positive_class"]
metrics = ["AUROC"]
less_bias_strengths = ["0.1"]
method_name_replacer = {
                        "uniform": "Uniform", 
                        "kmm": "KMM", 
                        "psa": "PSA", 
                        "mrs-forest": "MRS", 
                        "fw-mrs-temperature": "FW-MRS",
                        "fw-mrs-temperature-svm": "FW-MRS$_{SVM}$",
                        }
data_set_replacer = {
                    "folktables_employment": "Employment", 
                    "folktables_income": "Income",
                    "breast_cancer": "Breast Cancer", 
                    "hr_analytics": "HR Analytic", 
                    "loan_prediction": "Loan",
                    "diabetes": "Diabetes", 
                    "german_credit": "German Credit", 
                    "bank_marketing": "Bank Marketing"
                    }

In [33]:
aurocs = []
auprcs = []
dict_list = []
for dataset in data_set_replacer.keys():
    for bias_type in bias_types:
        for method in method_name_replacer.keys():
            for bias_strength in less_bias_strengths:
                json_file = result_path / dataset / bias_type /  bias_strength/ method / "classification_results.json"
                try:
                    result_file = pd.read_json(str(json_file))
                except FileNotFoundError:
                    continue
                dict_list.append(
                    {
                        "Method": method, "Data Set": dataset, 
                        "AUROC Mean": result_file["random forest auroc"]["mean"], 
                        "AUROC Std": result_file["random forest auroc"]["sd"], 
                        "Bias Type": bias_type, "Bias Strength": bias_strength,
                        "Dropped Samples Mean": result_file["dropped_samples"]["mean"],
                        "Dropped Samples Std": result_file["dropped_samples"]["std"],
                        "SVM PAD Mean": result_file["svm pad"]["mean"],
                        "SVM PAD Std": result_file["svm pad"]["sd"],
                        "RF Domain AUROC Mean": result_file["rf domain auroc"]["mean"],
                        "RF Domain AUROC Std": result_file["rf domain auroc"]["sd"],
                    }
                                )
result_df = pd.DataFrame(data=dict_list)

In [34]:
result_df = result_df.replace(method_name_replacer)
result_df

,Method,Data Set,AUROC Mean,AUROC Std,Bias Type,Bias Strength,Dropped Samples Mean,Dropped Samples Std,SVM PAD Mean,SVM PAD Std,RF Domain AUROC Mean,RF Domain AUROC Std
0,Uniform,folktables_employment,0.870601,0.010491,less_positive_class,0.1,0.000000,0.000000,0.357066,0.036606,0.630367,0.010368
1,KMM,folktables_employment,0.856631,0.013580,less_positive_class,0.1,0.000000,0.000000,0.099177,0.023438,0.525253,0.008685
2,PSA,folktables_employment,0.867401,0.010937,less_positive_class,0.1,0.040000,0.280000,0.042419,0.011849,0.528106,0.009637
3,MRS,folktables_employment,0.869954,0.009992,less_positive_class,0.1,203.900000,35.061232,0.289446,0.041109,0.602020,0.012732
4,FW-MRS,folktables_employment,0.866548,0.011815,less_positive_class,0.1,195.833333,36.854228,0.295478,0.038170,0.604088,0.011630
5,FW-MRS$_{SVM}$,folktables_employment,0.862458,0.011854,less_positive_class,0.1,269.600000,32.616560,0.148346,0.039321,0.576571,0.012588
6,Uniform,folktables_income,0.838084,0.012878,less_positive_class,0.1,0.000000,0.000000,0.352737,0.041463,0.612679,0.014196
7,KMM,folktables_income,0.820208,0.014266,less_positive_class,0.1,0.000000,0.000000,0.092928,0.026392,0.527638,0.007296
8,PSA,folktables_income,0.831057,0.013985,less_positive_class,0.1,0.160000,0.703136,0.044959,0.014487,0.519376,0.007730
9,MRS,folktables_income,0.837651,0.013005,less_positive_class,0.1,199.400000,49.138987,0.285773,0.052469,0.587054,0.018934
10,FW-MRS,folktables_income,0.834124,0.013838,less_positive_class,0.1,201.555556,49.730632,0.267442,0.055133,0.584491,0.017479
11,FW-MRS$_{SVM}$,folktables_income,0.832430,0.013644,less_positive_class,0.1,300.700000,28.618351,0.119675,0.035686,0.571619,0.015038
12,Uniform,breast_cancer,0.987591,0.006273,less_positive_class,0.1,0.000000,0.000000,0.934375,0.049196,0.730549,0.017786
13,KMM,breast_cancer,0.989408,0.005247,less_positive_class,0.1,0.000000,0.000000,0.141982,0.048100,0.592115,0.028551
14,PSA,breast_cancer,0.987893,0.006442,less_positive_class,0.1,0.000000,0.000000,0.369868,0.087313,0.583283,0.027643
15,MRS,breast_cancer,0.988525,0.006004,less_positive_class,0.1,53.060000,6.300508,0.668194,0.085055,0.648704,0.029313
16,FW-MRS,breast_cancer,0.980229,0.011079,less_positive_class,0.1,39.920000,10.834833,0.513432,0.154739,0.658380,0.032431
17,FW-MRS$_{SVM}$,breast_cancer,0.976459,0.014517,less_positive_class,0.1,50.360000,9.322575,0.365778,0.127300,0.678282,0.047675
18,Uniform,hr_analytics,0.752772,0.018290,less_positive_class,0.1,0.000000,0.000000,0.103957,0.028068,0.532918,0.008788
19,KMM,hr_analytics,0.749431,0.019074,less_positive_class,0.1,0.000000,0.000000,0.036428,0.011798,0.514326,0.005495
20,PSA,hr_analytics,0.750453,0.019049,less_positive_class,0.1,0.000000,0.000000,0.035252,0.012651,0.511088,0.004514
21,MRS,hr_analytics,0.751373,0.019375,less_positive_class,0.1,105.300000,58.020772,0.085924,0.025301,0.526627,0.007657
22,FW-MRS,hr_analytics,0.751020,0.018792,less_positive_class,0.1,110.100000,54.785856,0.085617,0.025459,0.524931,0.007972
23,FW-MRS$_{SVM}$,hr_analytics,0.751808,0.019646,less_positive_class,0.1,176.500000,72.644683,0.079404,0.027862,0.526322,0.008616
24,Uniform,loan_prediction,0.658389,0.080697,less_positive_class,0.1,0.000000,0.000000,0.350333,0.106762,0.570285,0.030109
25,KMM,loan_prediction,0.610365,0.096952,less_positive_class,0.1,0.000000,0.000000,0.246098,0.060627,0.585211,0.023742
26,PSA,loan_prediction,0.627560,0.095193,less_positive_class,0.1,0.000000,0.000000,0.171968,0.054509,0.553523,0.020760
27,MRS,loan_prediction,0.637731,0.097225,less_positive_class,0.1,8.420000,5.366899,0.281149,0.101353,0.550919,0.017978
28,FW-MRS,loan_prediction,0.612096,0.091994,less_positive_class,0.1,3.920000,3.520455,0.244441,0.109491,0.552784,0.023472
29,FW-MRS$_{SVM}$,loan_prediction,0.573596,0.096721,less_positive_class,0.1,5.560000,4.512915,0.205706,0.085429,0.550493,0.019074
30,Uniform,diabetes,0.791498,0.022072,less_positive_class,0.1,0.000000,0.000000,0.105814,0.034614,0.524808,0.009243
31,KMM,diabetes,0.781169,0.021943,less_positive_class,0.1,0.000000,0.000000,0.044013,0.011766,0.521981,0.007816
32,PSA,diabetes,0.787277,0.023148,less_positive_class,0.1,0.000000,0.000000,0.037124,0.010159,0.512270,0.003703
33,MRS,diabetes,0.789326,0.023831,less_positive_class,0.1,39.600000,32.493692,0.095200,0.036402,0.522293,0.009748
34,FW-MRS,diabetes,0.786366,0.022672,less_positive_class,0.1,42.700000,34.629612,0.090160,0.030599,0.520027,0.009081
35,FW-MRS$_{SVM}$,diabetes,0.783049,0.027098,less_positive_class,0.1,71.500000,37.473324,0.080497,0.031757,0.518662,0.006649
36,Uniform,german_credit,0.667239,0.053736,less_positive_class,0.1,0.000000,0.000000,0.157752,0.067674,0.538268,0.015928
37,KMM,german_credit,0.648943,0.052757,less_positive_class,0.1,0.000000,0.000000,0.116224,0.041402,0.546872,0.015067
38,PSA,german_credit,0.658996,0.055090,less_positive_class,0.1,0.000000,0.000000,0.090296,0.026323,0.532806,0.009209
39,MRS,german_credit,0.668462,0.054647,less_positive_class,0.1,12.800000,11.452511,0.141130,0.056958,0.533510,0.011700
40,FW-MRS,german_credit,0.643725,0.062229,less_positive_class,0.1,7.700000,11.100000,0.121641,0.064750,0.530923,0.011431
41,FW-MRS$_{SVM}$,german_credit,0.668423,0.037054,less_positive_class,0.1,2.500000,2.500000,0.077331,0.004943,0.523364,0.006287
42,Uniform,bank_marketing,0.846908,0.021440,less_positive_class,0.1,0.000000,0.000000,0.080367,0.032421,0.522693,0.008734
43,KMM,bank_marketing,0.831756,0.026469,less_positive_class,0.1,0.000000,0.000000,0.063037,0.021513,0.521086,0.006660
44,PSA,bank_marketing,0.839479,0.025952,less_positive_class,0.1,0.000000,0.000000,0.036807,0.011388,0.512231,0.003996
45,MRS,bank_marketing,0.845635,0.021468,less_positive_class,0.1,58.800000,35.207386,0.065461,0.024151,0.516828,0.006621
46,FW-MRS,bank_marketing,0.845421,0.019709,less_positive_class,0.1,56.400000,30.100498,0.069679,0.027660,0.518480,0.007114
47,FW-MRS$_{SVM}$,bank_marketing,0.839128,0.019026,less_positive_class,0.1,66.250000,26.309456,0.064304,0.023603,0.517411,0.006352

In [35]:
for bias_type in bias_types:
    for bias_strength in less_bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_auroc_values = []
            std_auroc_values = []
            for method in result_df["Method"].unique():
                try:
                    mean_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUROC Mean"].iloc[0]
                    mean_auroc_values.append(np.round(mean_auroc, 3))

                    std_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["AUROC Std"].iloc[0]
                    std_auroc_values.append(np.round(std_auroc, 2))
                except IndexError:
                    mean_auroc_values.append(0)
                    std_auroc_values.append(0)

            print(f"{data_set_replacer[dataset]} \
& ${mean_auroc_values[0]}\\pm{std_auroc_values[0]}$ \
& ${mean_auroc_values[1]}\\pm{std_auroc_values[1]}$ \
& ${mean_auroc_values[2]}\\pm{std_auroc_values[2]}$ \
& ${mean_auroc_values[3]}\\pm{std_auroc_values[3]}$ \
& ${mean_auroc_values[4]}\\pm{std_auroc_values[4]}$ \
& ${mean_auroc_values[5]}\\pm{std_auroc_values[5]}$ \
\\\\")
        print("\n")

less_positive_class, 0.1
Employment & $0.871\pm0.01$ & $0.857\pm0.01$ & $0.867\pm0.01$ & $0.87\pm0.01$ & $0.867\pm0.01$ & $0.862\pm0.01$ \\
Income & $0.838\pm0.01$ & $0.82\pm0.01$ & $0.831\pm0.01$ & $0.838\pm0.01$ & $0.834\pm0.01$ & $0.832\pm0.01$ \\
Breast Cancer & $0.988\pm0.01$ & $0.989\pm0.01$ & $0.988\pm0.01$ & $0.989\pm0.01$ & $0.98\pm0.01$ & $0.976\pm0.01$ \\
HR Analytic & $0.753\pm0.02$ & $0.749\pm0.02$ & $0.75\pm0.02$ & $0.751\pm0.02$ & $0.751\pm0.02$ & $0.752\pm0.02$ \\
Loan & $0.658\pm0.08$ & $0.61\pm0.1$ & $0.628\pm0.1$ & $0.638\pm0.1$ & $0.612\pm0.09$ & $0.574\pm0.1$ \\
Diabetes & $0.791\pm0.02$ & $0.781\pm0.02$ & $0.787\pm0.02$ & $0.789\pm0.02$ & $0.786\pm0.02$ & $0.783\pm0.03$ \\
German Credit & $0.667\pm0.05$ & $0.649\pm0.05$ & $0.659\pm0.06$ & $0.668\pm0.05$ & $0.644\pm0.06$ & $0.668\pm0.04$ \\
Bank Marketing & $0.847\pm0.02$ & $0.832\pm0.03$ & $0.839\pm0.03$ & $0.846\pm0.02$ & $0.845\pm0.02$ & $0.839\pm0.02$ \\

In [36]:
for bias_type in bias_types:
    for bias_strength in less_bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_pad_values = []
            std_pad_values = []
            for method in result_df["Method"].unique():
                try:
                    mean_pad = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["SVM PAD Mean"].iloc[0]
                    mean_pad_values.append(np.round(mean_pad, 3))

                    std_pad = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["SVM PAD Std"].iloc[0]
                    std_pad_values.append(np.round(std_pad, 2))
                except IndexError:
                    mean_pad_values.append(0)
                    std_pad_values.append(0)

            print(f"{data_set_replacer[dataset]} \
& ${mean_pad_values[0]}\\pm{std_pad_values[0]}$ \
& ${mean_pad_values[1]}\\pm{std_pad_values[1]}$ \
& ${mean_pad_values[2]}\\pm{std_pad_values[2]}$ \
& ${mean_pad_values[3]}\\pm{std_pad_values[3]}$ \
& ${mean_pad_values[4]}\\pm{std_pad_values[4]}$ \
& ${mean_pad_values[5]}\\pm{std_pad_values[5]}$ \
& \\\\")
        print("\n")

less_positive_class, 0.1
Employment & $0.357\pm0.04$ & $0.099\pm0.02$ & $0.042\pm0.01$ & $0.289\pm0.04$ & $0.295\pm0.04$ & $0.148\pm0.04$ & \\
Income & $0.353\pm0.04$ & $0.093\pm0.03$ & $0.045\pm0.01$ & $0.286\pm0.05$ & $0.267\pm0.06$ & $0.12\pm0.04$ & \\
Breast Cancer & $0.934\pm0.05$ & $0.142\pm0.05$ & $0.37\pm0.09$ & $0.668\pm0.09$ & $0.513\pm0.15$ & $0.366\pm0.13$ & \\
HR Analytic & $0.104\pm0.03$ & $0.036\pm0.01$ & $0.035\pm0.01$ & $0.086\pm0.03$ & $0.086\pm0.03$ & $0.079\pm0.03$ & \\
Loan & $0.35\pm0.11$ & $0.246\pm0.06$ & $0.172\pm0.05$ & $0.281\pm0.1$ & $0.244\pm0.11$ & $0.206\pm0.09$ & \\
Diabetes & $0.106\pm0.03$ & $0.044\pm0.01$ & $0.037\pm0.01$ & $0.095\pm0.04$ & $0.09\pm0.03$ & $0.08\pm0.03$ & \\
German Credit & $0.158\pm0.07$ & $0.116\pm0.04$ & $0.09\pm0.03$ & $0.141\pm0.06$ & $0.122\pm0.06$ & $0.077\pm0.0$ & \\
Bank Marketing & $0.08\pm0.03$ & $0.063\pm0.02$ & $0.037\pm0.01$ & $0.065\pm0.02$ & $0.07\pm0.03$ & $0.064\pm0.02$ & \\

In [37]:
for bias_type in bias_types:
    for bias_strength in less_bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_domain_values = []
            std_domain_values = []
            for method in result_df["Method"].unique():
                try:
                    mean_domain = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["RF Domain AUROC Mean"].iloc[0]
                    mean_domain_values.append(np.round(mean_domain, 3))

                    std_domain = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["RF Domain AUROC Std"].iloc[0]
                    std_domain_values.append(np.round(std_domain, 2))
                except IndexError:
                    mean_domain_values.append(0)
                    std_domain_values.append(0)

            print(f"{data_set_replacer[dataset]} \
& ${mean_domain_values[0]}\\pm{std_domain_values[0]}$ \
& ${mean_domain_values[1]}\\pm{std_domain_values[1]}$ \
& ${mean_domain_values[2]}\\pm{std_domain_values[2]}$ \
& ${mean_domain_values[3]}\\pm{std_domain_values[3]}$ \
& ${mean_domain_values[4]}\\pm{std_domain_values[4]}$ \
& ${mean_domain_values[5]}\\pm{std_domain_values[5]}$ \
& \\\\")
        print("\n")

less_positive_class, 0.1
Employment & $0.63\pm0.01$ & $0.525\pm0.01$ & $0.528\pm0.01$ & $0.602\pm0.01$ & $0.604\pm0.01$ & $0.577\pm0.01$ & \\
Income & $0.613\pm0.01$ & $0.528\pm0.01$ & $0.519\pm0.01$ & $0.587\pm0.02$ & $0.584\pm0.02$ & $0.572\pm0.02$ & \\
Breast Cancer & $0.731\pm0.02$ & $0.592\pm0.03$ & $0.583\pm0.03$ & $0.649\pm0.03$ & $0.658\pm0.03$ & $0.678\pm0.05$ & \\
HR Analytic & $0.533\pm0.01$ & $0.514\pm0.01$ & $0.511\pm0.0$ & $0.527\pm0.01$ & $0.525\pm0.01$ & $0.526\pm0.01$ & \\
Loan & $0.57\pm0.03$ & $0.585\pm0.02$ & $0.554\pm0.02$ & $0.551\pm0.02$ & $0.553\pm0.02$ & $0.55\pm0.02$ & \\
Diabetes & $0.525\pm0.01$ & $0.522\pm0.01$ & $0.512\pm0.0$ & $0.522\pm0.01$ & $0.52\pm0.01$ & $0.519\pm0.01$ & \\
German Credit & $0.538\pm0.02$ & $0.547\pm0.02$ & $0.533\pm0.01$ & $0.534\pm0.01$ & $0.531\pm0.01$ & $0.523\pm0.01$ & \\
Bank Marketing & $0.523\pm0.01$ & $0.521\pm0.01$ & $0.512\pm0.0$ & $0.517\pm0.01$ & $0.518\pm0.01$ & $0.517\pm0.01$ & \\

In [38]:
result_df.round(3)

,Method,Data Set,AUROC Mean,AUROC Std,Bias Type,Bias Strength,Dropped Samples Mean,Dropped Samples Std,SVM PAD Mean,SVM PAD Std,RF Domain AUROC Mean,RF Domain AUROC Std
0,Uniform,folktables_employment,0.871,0.010,less_positive_class,0.1,0.000,0.000,0.357,0.037,0.630,0.010
1,KMM,folktables_employment,0.857,0.014,less_positive_class,0.1,0.000,0.000,0.099,0.023,0.525,0.009
2,PSA,folktables_employment,0.867,0.011,less_positive_class,0.1,0.040,0.280,0.042,0.012,0.528,0.010
3,MRS,folktables_employment,0.870,0.010,less_positive_class,0.1,203.900,35.061,0.289,0.041,0.602,0.013
4,FW-MRS,folktables_employment,0.867,0.012,less_positive_class,0.1,195.833,36.854,0.295,0.038,0.604,0.012
5,FW-MRS$_{SVM}$,folktables_employment,0.862,0.012,less_positive_class,0.1,269.600,32.617,0.148,0.039,0.577,0.013
6,Uniform,folktables_income,0.838,0.013,less_positive_class,0.1,0.000,0.000,0.353,0.041,0.613,0.014
7,KMM,folktables_income,0.820,0.014,less_positive_class,0.1,0.000,0.000,0.093,0.026,0.528,0.007
8,PSA,folktables_income,0.831,0.014,less_positive_class,0.1,0.160,0.703,0.045,0.014,0.519,0.008
9,MRS,folktables_income,0.838,0.013,less_positive_class,0.1,199.400,49.139,0.286,0.052,0.587,0.019
10,FW-MRS,folktables_income,0.834,0.014,less_positive_class,0.1,201.556,49.731,0.267,0.055,0.584,0.017
11,FW-MRS$_{SVM}$,folktables_income,0.832,0.014,less_positive_class,0.1,300.700,28.618,0.120,0.036,0.572,0.015
12,Uniform,breast_cancer,0.988,0.006,less_positive_class,0.1,0.000,0.000,0.934,0.049,0.731,0.018
13,KMM,breast_cancer,0.989,0.005,less_positive_class,0.1,0.000,0.000,0.142,0.048,0.592,0.029
14,PSA,breast_cancer,0.988,0.006,less_positive_class,0.1,0.000,0.000,0.370,0.087,0.583,0.028
15,MRS,breast_cancer,0.989,0.006,less_positive_class,0.1,53.060,6.301,0.668,0.085,0.649,0.029
16,FW-MRS,breast_cancer,0.980,0.011,less_positive_class,0.1,39.920,10.835,0.513,0.155,0.658,0.032
17,FW-MRS$_{SVM}$,breast_cancer,0.976,0.015,less_positive_class,0.1,50.360,9.323,0.366,0.127,0.678,0.048
18,Uniform,hr_analytics,0.753,0.018,less_positive_class,0.1,0.000,0.000,0.104,0.028,0.533,0.009
19,KMM,hr_analytics,0.749,0.019,less_positive_class,0.1,0.000,0.000,0.036,0.012,0.514,0.005
20,PSA,hr_analytics,0.750,0.019,less_positive_class,0.1,0.000,0.000,0.035,0.013,0.511,0.005
21,MRS,hr_analytics,0.751,0.019,less_positive_class,0.1,105.300,58.021,0.086,0.025,0.527,0.008
22,FW-MRS,hr_analytics,0.751,0.019,less_positive_class,0.1,110.100,54.786,0.086,0.025,0.525,0.008
23,FW-MRS$_{SVM}$,hr_analytics,0.752,0.020,less_positive_class,0.1,176.500,72.645,0.079,0.028,0.526,0.009
24,Uniform,loan_prediction,0.658,0.081,less_positive_class,0.1,0.000,0.000,0.350,0.107,0.570,0.030
25,KMM,loan_prediction,0.610,0.097,less_positive_class,0.1,0.000,0.000,0.246,0.061,0.585,0.024
26,PSA,loan_prediction,0.628,0.095,less_positive_class,0.1,0.000,0.000,0.172,0.055,0.554,0.021
27,MRS,loan_prediction,0.638,0.097,less_positive_class,0.1,8.420,5.367,0.281,0.101,0.551,0.018
28,FW-MRS,loan_prediction,0.612,0.092,less_positive_class,0.1,3.920,3.520,0.244,0.109,0.553,0.023
29,FW-MRS$_{SVM}$,loan_prediction,0.574,0.097,less_positive_class,0.1,5.560,4.513,0.206,0.085,0.550,0.019
30,Uniform,diabetes,0.791,0.022,less_positive_class,0.1,0.000,0.000,0.106,0.035,0.525,0.009
31,KMM,diabetes,0.781,0.022,less_positive_class,0.1,0.000,0.000,0.044,0.012,0.522,0.008
32,PSA,diabetes,0.787,0.023,less_positive_class,0.1,0.000,0.000,0.037,0.010,0.512,0.004
33,MRS,diabetes,0.789,0.024,less_positive_class,0.1,39.600,32.494,0.095,0.036,0.522,0.010
34,FW-MRS,diabetes,0.786,0.023,less_positive_class,0.1,42.700,34.630,0.090,0.031,0.520,0.009
35,FW-MRS$_{SVM}$,diabetes,0.783,0.027,less_positive_class,0.1,71.500,37.473,0.080,0.032,0.519,0.007
36,Uniform,german_credit,0.667,0.054,less_positive_class,0.1,0.000,0.000,0.158,0.068,0.538,0.016
37,KMM,german_credit,0.649,0.053,less_positive_class,0.1,0.000,0.000,0.116,0.041,0.547,0.015
38,PSA,german_credit,0.659,0.055,less_positive_class,0.1,0.000,0.000,0.090,0.026,0.533,0.009
39,MRS,german_credit,0.668,0.055,less_positive_class,0.1,12.800,11.453,0.141,0.057,0.534,0.012
40,FW-MRS,german_credit,0.644,0.062,less_positive_class,0.1,7.700,11.100,0.122,0.065,0.531,0.011
41,FW-MRS$_{SVM}$,german_credit,0.668,0.037,less_positive_class,0.1,2.500,2.500,0.077,0.005,0.523,0.006
42,Uniform,bank_marketing,0.847,0.021,less_positive_class,0.1,0.000,0.000,0.080,0.032,0.523,0.009
43,KMM,bank_marketing,0.832,0.026,less_positive_class,0.1,0.000,0.000,0.063,0.022,0.521,0.007
44,PSA,bank_marketing,0.839,0.026,less_positive_class,0.1,0.000,0.000,0.037,0.011,0.512,0.004
45,MRS,bank_marketing,0.846,0.021,less_positive_class,0.1,58.800,35.207,0.065,0.024,0.517,0.007
46,FW-MRS,bank_marketing,0.845,0.020,less_positive_class,0.1,56.400,30.100,0.070,0.028,0.518,0.007
47,FW-MRS$_{SVM}$,bank_marketing,0.839,0.019,less_positive_class,0.1,66.250,26.309,0.064,0.024,0.517,0.006

In [42]:
result_df["Rank AUROC"] = result_df.round(3).groupby("Data Set")["AUROC Mean"].rank(ascending=False)
result_df["Rank PAD"] = result_df.round(3).groupby("Data Set")["SVM PAD Mean"].rank(ascending=True)
result_df["Rank Domain"] = result_df.round(3).groupby("Data Set")["RF Domain AUROC Mean"].rank(ascending=True)
result_df[["Method", "Rank AUROC", "Rank PAD", "Rank Domain"]].groupby("Method").mean()

                Rank AUROC  Rank PAD  Rank Domain
Method
FW-MRS              4.0000    4.1875       3.5000
FW-MRS$_{SVM}$      4.2500    2.5000       2.6875
KMM                 5.1875    2.2500       3.5625
MRS                 2.0000    4.6875       3.7500
PSA                 3.9375    1.3750       1.7500
Uniform             1.6250    6.0000       5.7500