In [49]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [50]:
result_path = Path("../results/downstream_task")
bias_types = ["less_positive_class"]
less_bias_strengths = ["0.1"]
method_name_replacer = {"uniform": "Uniform", 
                        "kmm": "KMM",
                        "psa": "PSA",
                        "soft-mrs-linear": "Soft-MRS",
                        "mrs-forest": "MRS",
                      #  "fw-mrs-temperature": "FW-MRS",
                      #  "fw-mrs-temperature-svm": "FW-MRS$_{SVM}$",
                        }
data_set_replacer = {"diabetes": "Diabetes",
                    "folktables_employment": "Employment", 
                     "folktables_income": "Income",
                     "bank_marketing": "Bank Marketing",
                     "hr_analytics": "HR Analytic",
                     "german_credit": "German Credit", 
                     "breast_cancer": "Breast Cancer", 
                     "loan_prediction": "Loan",
                    }

data_set_targets = {"diabetes": "Diabetes_binary_relative_bias",
                    "folktables_employment": "Employment_relative_bias", 
                    "folktables_income": "Binary Income_relative_bias",
                    "bank_marketing": "y_relative_bias",
                    "hr_analytics": "target_relative_bias",
                    "german_credit": "class_relative_bias", 
                    "breast_cancer": "class_relative_bias", 
                    "loan_prediction": "Loan_Status_relative_bias",
                    }

In [51]:
dict_list = []
for dataset in data_set_replacer.keys():
    for bias_type in bias_types:
        for method in method_name_replacer.keys():
            bias_strengths = less_bias_strengths
            for bias_strength in bias_strengths:
                json_file = result_path / dataset / bias_type /  bias_strength/ method / "similarity_results_T.json"
                result_file = pd.read_json(str(json_file))
                dict_list.append(
                    {
                        "Method": method, "Data Set": dataset, 
                        "MMD Mean": result_file["MMDs"]["mean"], 
                        "MMD Std": result_file["MMDs"]["sd"], 
                        "Relative Bias Mean": result_file[data_set_targets[dataset]]["bias mean"], 
                        "Relative Bias Std": result_file[data_set_targets[dataset]]["bias sd"], 
                        "Bias Type": bias_type, "Bias Strength": bias_strength,
                    }
                                )
result_df = pd.DataFrame(data=dict_list)

In [52]:
for bias_type in bias_types:
    bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_mmd_values = []
            std_mmd_values = []
            for method in result_df["Method"].unique():

                mean_mmd = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["MMD Mean"].iloc[0]
                mean_mmd_values.append(np.round(mean_mmd, 4))

                std_mmd = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["MMD Std"].iloc[0]
                std_mmd_values.append(np.round(std_mmd, 3))

                

            print(f"{data_set_replacer[dataset]} \
& ${mean_mmd_values[0]}\\pm{std_mmd_values[0]}$ \
& ${mean_mmd_values[1]}\\pm{std_mmd_values[1]}$ \
& ${mean_mmd_values[2]}\\pm{std_mmd_values[2]}$ \
& ${mean_mmd_values[3]}\\pm{std_mmd_values[3]}$ \
& ${mean_mmd_values[4]}\\pm{std_mmd_values[4]}$ \
\\\\")
    print("\n")

less_positive_class, 0.1
Diabetes & $0.0358\pm0.006$ & $0.0217\pm0.003$ & $0.022\pm0.003$ & $0.0217\pm0.003$ & $0.0325\pm0.005$ \\
Employment & $0.0681\pm0.005$ & $0.0219\pm0.002$ & $0.024\pm0.002$ & $0.022\pm0.001$ & $0.0472\pm0.013$ \\
Income & $0.064\pm0.005$ & $0.0233\pm0.003$ & $0.0262\pm0.002$ & $0.023\pm0.002$ & $0.0501\pm0.011$ \\
Bank Marketing & $0.0282\pm0.003$ & $0.0226\pm0.002$ & $0.023\pm0.002$ & $0.0226\pm0.002$ & $0.027\pm0.002$ \\
HR Analytic & $0.0276\pm0.003$ & $0.0184\pm0.002$ & $0.0187\pm0.002$ & $0.0183\pm0.002$ & $0.0258\pm0.003$ \\
German Credit & $0.064\pm0.007$ & $0.0549\pm0.006$ & $0.0561\pm0.007$ & $0.0547\pm0.006$ & $0.0615\pm0.006$ \\
Breast Cancer & $0.3949\pm0.017$ & $0.0429\pm0.009$ & $0.1423\pm0.024$ & $0.0432\pm0.009$ & $0.2805\pm0.032$ \\
Loan & $0.1413\pm0.015$ & $0.0803\pm0.014$ & $0.1004\pm0.015$ & $0.0804\pm0.013$ & $0.1275\pm0.016$ \\

In [53]:
for bias_type in bias_types:
    bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_relative_bias_values = []
            std_relative_bias_values = []
            for method in result_df["Method"].unique():

                mean_relative_bias = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["Relative Bias Mean"].iloc[0]
                mean_relative_bias_values.append(np.round(mean_relative_bias, 2))

                std_relative_bias = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["Relative Bias Std"].iloc[0]
                std_relative_bias_values.append(np.round(std_relative_bias, 2))

                

            print(f"{data_set_replacer[dataset]} \
& ${mean_relative_bias_values[0]}\\pm{std_relative_bias_values[0]}$ \
& ${mean_relative_bias_values[1]}\\pm{std_relative_bias_values[1]}$ \
& ${mean_relative_bias_values[2]}\\pm{std_relative_bias_values[2]}$ \
& ${mean_relative_bias_values[3]}\\pm{std_relative_bias_values[3]}$ \
& ${mean_relative_bias_values[4]}\\pm{std_relative_bias_values[4]}$ \
\\\\")
    print("\n")

less_positive_class, 0.1
Diabetes & $88.76\pm0.03$ & $85.4\pm2.75$ & $86.82\pm0.65$ & $85.82\pm1.29$ & $88.56\pm0.2$ \\
Employment & $82.99\pm0.0$ & $64.48\pm2.99$ & $72.44\pm1.24$ & $65.96\pm1.79$ & $79.36\pm2.13$ \\
Income & $83.4\pm0.02$ & $64.46\pm3.41$ & $71.86\pm1.32$ & $65.77\pm1.78$ & $80.34\pm1.47$ \\
Bank Marketing & $88.77\pm0.03$ & $81.77\pm2.79$ & $83.03\pm1.44$ & $82.07\pm1.51$ & $88.49\pm0.22$ \\
HR Analytic & $0.8\pm0.58$ & $0.8\pm0.67$ & $0.82\pm0.66$ & $0.81\pm0.65$ & $0.75\pm0.51$ \\
German Credit & $86.3\pm0.0$ & $80.21\pm3.72$ & $82.5\pm3.92$ & $81.2\pm3.2$ & $86.08\pm0.74$ \\
Breast Cancer & $75.59\pm0.18$ & $7.08\pm3.25$ & $35.6\pm4.6$ & $7.74\pm2.4$ & $57.15\pm4.83$ \\
Loan & $6.38\pm5.2$ & $5.0\pm3.31$ & $5.16\pm3.72$ & $4.99\pm3.22$ & $5.91\pm5.03$ \\

In [54]:
result_df = result_df.replace(method_name_replacer)
result_df

,Method,Data Set,MMD Mean,MMD Std,Relative Bias Mean,Relative Bias Std,Bias Type,Bias Strength
0,Uniform,diabetes,0.035790,0.006027,88.764886,2.972893e-02,less_positive_class,0.1
1,KMM,diabetes,0.021661,0.003101,85.403825,2.745357e+00,less_positive_class,0.1
2,PSA,diabetes,0.021974,0.002963,86.818399,6.500400e-01,less_positive_class,0.1
3,Soft-MRS,diabetes,0.021664,0.003074,85.821534,1.290378e+00,less_positive_class,0.1
4,MRS,diabetes,0.032462,0.005429,88.562630,1.970144e-01,less_positive_class,0.1
5,Uniform,folktables_employment,0.068065,0.005092,82.985481,5.684342e-14,less_positive_class,0.1
6,KMM,folktables_employment,0.021865,0.001573,64.483977,2.991754e+00,less_positive_class,0.1
7,PSA,folktables_employment,0.024042,0.001788,72.442898,1.238853e+00,less_positive_class,0.1
8,Soft-MRS,folktables_employment,0.021971,0.001478,65.959261,1.787170e+00,less_positive_class,0.1
9,MRS,folktables_employment,0.047241,0.012916,79.360640,2.132048e+00,less_positive_class,0.1
10,Uniform,folktables_income,0.063995,0.005134,83.396447,1.534683e-02,less_positive_class,0.1
11,KMM,folktables_income,0.023319,0.002842,64.457094,3.410984e+00,less_positive_class,0.1
12,PSA,folktables_income,0.026209,0.002453,71.864346,1.317663e+00,less_positive_class,0.1
13,Soft-MRS,folktables_income,0.023032,0.001991,65.774719,1.784551e+00,less_positive_class,0.1
14,MRS,folktables_income,0.050118,0.010829,80.343288,1.468238e+00,less_positive_class,0.1
15,Uniform,bank_marketing,0.028176,0.002776,88.770556,3.340664e-02,less_positive_class,0.1
16,KMM,bank_marketing,0.022634,0.001817,81.765934,2.794034e+00,less_positive_class,0.1
17,PSA,bank_marketing,0.022958,0.001663,83.031803,1.439390e+00,less_positive_class,0.1
18,Soft-MRS,bank_marketing,0.022573,0.001744,82.065840,1.505247e+00,less_positive_class,0.1
19,MRS,bank_marketing,0.026982,0.002461,88.487270,2.173149e-01,less_positive_class,0.1
20,Uniform,hr_analytics,0.027595,0.003097,0.804678,5.828456e-01,less_positive_class,0.1
21,KMM,hr_analytics,0.018422,0.002220,0.804914,6.679480e-01,less_positive_class,0.1
22,PSA,hr_analytics,0.018713,0.002327,0.823168,6.597071e-01,less_positive_class,0.1
23,Soft-MRS,hr_analytics,0.018276,0.002280,0.813494,6.542688e-01,less_positive_class,0.1
24,MRS,hr_analytics,0.025805,0.002817,0.751135,5.148039e-01,less_positive_class,0.1
25,Uniform,german_credit,0.064033,0.006621,86.301370,7.105427e-14,less_positive_class,0.1
26,KMM,german_credit,0.054874,0.005913,80.209430,3.717328e+00,less_positive_class,0.1
27,PSA,german_credit,0.056055,0.006544,82.495010,3.917639e+00,less_positive_class,0.1
28,Soft-MRS,german_credit,0.054676,0.005709,81.202178,3.202343e+00,less_positive_class,0.1
29,MRS,german_credit,0.061532,0.006233,86.078065,7.417124e-01,less_positive_class,0.1
30,Uniform,breast_cancer,0.394904,0.017140,75.586060,1.777548e-01,less_positive_class,0.1
31,KMM,breast_cancer,0.042864,0.009061,7.084018,3.250241e+00,less_positive_class,0.1
32,PSA,breast_cancer,0.142252,0.023988,35.602627,4.602077e+00,less_positive_class,0.1
33,Soft-MRS,breast_cancer,0.043192,0.008983,7.736700,2.404543e+00,less_positive_class,0.1
34,MRS,breast_cancer,0.280492,0.032003,57.150645,4.826247e+00,less_positive_class,0.1
35,Uniform,loan_prediction,0.141282,0.015288,6.381475,5.203385e+00,less_positive_class,0.1
36,KMM,loan_prediction,0.080285,0.014295,5.000049,3.309805e+00,less_positive_class,0.1
37,PSA,loan_prediction,0.100370,0.014911,5.162500,3.724999e+00,less_positive_class,0.1
38,Soft-MRS,loan_prediction,0.080448,0.013103,4.987323,3.219976e+00,less_positive_class,0.1
39,MRS,loan_prediction,0.127454,0.016340,5.905138,5.032396e+00,less_positive_class,0.1

In [55]:
result_df["Rank MMD"] = result_df.groupby("Data Set")["MMD Mean"].rank(ascending=True)
result_df["Rank Relative Bias"] = result_df.groupby("Data Set")["Relative Bias Mean"].rank(ascending=True)
result_df[["Method", "Rank MMD", "Rank Relative Bias"]].groupby("Method").mean()

          Rank MMD  Rank Relative Bias
Method
KMM            1.5               1.375
MRS            4.0               3.625
PSA            3.0               3.250
Soft-MRS       1.5               2.125
Uniform        5.0               4.625