In [21]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [22]:
result_path = Path("../results/downstream_task")
bias_types = ["less_positive_class"]
metrics = ["AUROC", "AUPRC"]
method_name_replacer = {"uniform": "Uniform", 
                        "kmm": "KMM",
                        "psa": "PSA",
                        "mrs-forest": "MRS",
                        "fw-mrs-temperature": "FW-MRS",
                        "fw-mrs-temperature-svm": "FW-MRS$_{SVM}$",
                        "soft-mrs-linear": "Soft-MRS",
                        }
data_set_replacer = {"diabetes": "Diabetes",
    "folktables_employment": "Employment", 
                     "folktables_income": "Income",
                     "bank_marketing": "Bank Marketing",
                     "hr_analytics": "HR Analytic",
                     "german_credit": "German Credit", 
                     "breast_cancer": "Breast Cancer", 
                     "loan_prediction": "Loan",
                    }

In [ ]:
aurocs = []
auprcs = []
dict_list = []
for dataset in data_set_replacer.keys():
    for bias_type in bias_types:
        for method in method_name_replacer.keys():
            json_file = result_path / dataset / bias_type /  "0.1"/ method / "classification_results.json"
            try:
                result_file = pd.read_json(str(json_file))
            except FileNotFoundError:
                continue
            dict_list.append(
                {
                    "Method": method, "Data Set": dataset, 
                    "AUROC Mean": result_file["random forest auroc"]["mean"], 
                    "AUROC Std": result_file["random forest auroc"]["sd"], 
                    "AUPRC Mean": result_file["random forest auprc"]["mean"], 
                    "AUPRC Std": result_file["random forest auprc"]["sd"], 
                    "Bias Type": bias_type, "Bias Strength": "0.1",
                    "Dropped Samples Mean": result_file["dropped_samples"]["mean"],
                    "Dropped Samples Std": result_file["dropped_samples"]["std"],
                }
                            )
result_df = pd.DataFrame(data=dict_list)

In [24]:
result_df = result_df.replace(method_name_replacer)
result_df

,Method,Data Set,AUROC Mean,AUROC Std,AUPRC Mean,AUPRC Std,Bias Type,Bias Strength,Dropped Samples Mean,Dropped Samples Std
0,Uniform,diabetes,0.791498,0.022072,0.371281,0.037717,less_positive_class,0.1,0.000000,0.000000
1,KMM,diabetes,0.781169,0.021943,0.357066,0.041765,less_positive_class,0.1,0.000000,0.000000
2,PSA,diabetes,0.787277,0.023148,0.367046,0.037046,less_positive_class,0.1,0.000000,0.000000
3,MRS,diabetes,0.788607,0.023040,0.367308,0.039618,less_positive_class,0.1,49.900000,32.116818
4,FW-MRS,diabetes,0.784586,0.022317,0.359473,0.040166,less_positive_class,0.1,38.636364,29.778799
5,FW-MRS$_{SVM}$,diabetes,0.786527,0.025484,0.358726,0.043561,less_positive_class,0.1,71.052632,31.438283
6,Soft-MRS,diabetes,0.787917,0.021554,0.367637,0.037645,less_positive_class,0.1,0.000000,0.000000
7,Uniform,folktables_employment,0.870601,0.010491,0.826992,0.017307,less_positive_class,0.1,0.000000,0.000000
8,KMM,folktables_employment,0.856631,0.013580,0.808776,0.021985,less_positive_class,0.1,0.000000,0.000000
9,PSA,folktables_employment,0.867401,0.010937,0.823689,0.017363,less_positive_class,0.1,0.040000,0.280000
10,MRS,folktables_employment,0.869784,0.009878,0.825616,0.016272,less_positive_class,0.1,287.500000,107.215904
11,FW-MRS,folktables_employment,0.869503,0.009349,0.824149,0.015460,less_positive_class,0.1,330.789474,120.724383
12,FW-MRS$_{SVM}$,folktables_employment,0.863763,0.014583,0.817161,0.022405,less_positive_class,0.1,277.666667,32.345359
13,Soft-MRS,folktables_employment,0.862420,0.012423,0.818201,0.019590,less_positive_class,0.1,0.000000,0.000000
14,Uniform,folktables_income,0.838084,0.012878,0.788634,0.020309,less_positive_class,0.1,0.000000,0.000000
15,KMM,folktables_income,0.820208,0.014266,0.765446,0.019706,less_positive_class,0.1,0.000000,0.000000
16,PSA,folktables_income,0.831057,0.013985,0.780822,0.021689,less_positive_class,0.1,0.160000,0.703136
17,MRS,folktables_income,0.837289,0.012323,0.787584,0.019060,less_positive_class,0.1,274.500000,80.611724
18,FW-MRS,folktables_income,0.837248,0.013033,0.789319,0.019264,less_positive_class,0.1,275.500000,91.568281
19,FW-MRS$_{SVM}$,folktables_income,0.834939,0.013071,0.787534,0.017603,less_positive_class,0.1,293.437500,37.153346
20,Soft-MRS,folktables_income,0.826917,0.013205,0.773737,0.019415,less_positive_class,0.1,0.000000,0.000000
21,Uniform,bank_marketing,0.846908,0.021440,0.465787,0.051725,less_positive_class,0.1,0.000000,0.000000
22,KMM,bank_marketing,0.831756,0.026469,0.445607,0.058065,less_positive_class,0.1,0.000000,0.000000
23,PSA,bank_marketing,0.839479,0.025952,0.454844,0.048837,less_positive_class,0.1,0.000000,0.000000
24,MRS,bank_marketing,0.845264,0.021926,0.467804,0.052034,less_positive_class,0.1,62.900000,34.030721
25,FW-MRS,bank_marketing,0.845063,0.017435,0.456195,0.057247,less_positive_class,0.1,62.105263,23.357394
26,FW-MRS$_{SVM}$,bank_marketing,0.840241,0.018583,0.439633,0.048632,less_positive_class,0.1,69.687500,30.231851
27,Soft-MRS,bank_marketing,0.834325,0.025744,0.446626,0.053698,less_positive_class,0.1,0.000000,0.000000
28,Uniform,hr_analytics,0.752772,0.018290,0.455071,0.029285,less_positive_class,0.1,0.000000,0.000000
29,KMM,hr_analytics,0.749431,0.019074,0.449147,0.032049,less_positive_class,0.1,0.000000,0.000000
30,PSA,hr_analytics,0.750453,0.019049,0.453771,0.034252,less_positive_class,0.1,0.000000,0.000000
31,MRS,hr_analytics,0.751456,0.019457,0.456013,0.030210,less_positive_class,0.1,107.400000,53.630588
32,FW-MRS,hr_analytics,0.751297,0.026609,0.451483,0.041197,less_positive_class,0.1,106.944444,58.074160
33,FW-MRS$_{SVM}$,hr_analytics,0.749977,0.025536,0.448040,0.044065,less_positive_class,0.1,173.000000,74.739548
34,Soft-MRS,hr_analytics,0.751405,0.019091,0.453650,0.035232,less_positive_class,0.1,0.000000,0.000000
35,Uniform,german_credit,0.667239,0.053736,0.460906,0.064090,less_positive_class,0.1,0.000000,0.000000
36,KMM,german_credit,0.648943,0.052757,0.443033,0.062464,less_positive_class,0.1,0.000000,0.000000
37,PSA,german_credit,0.658996,0.055090,0.452393,0.063956,less_positive_class,0.1,0.000000,0.000000
38,MRS,german_credit,0.672495,0.051572,0.464485,0.066462,less_positive_class,0.1,13.600000,10.584895
39,FW-MRS,german_credit,0.641567,0.064352,0.440658,0.071346,less_positive_class,0.1,8.571429,11.791124
40,FW-MRS$_{SVM}$,german_credit,0.636781,0.058320,0.440793,0.077181,less_positive_class,0.1,13.043478,12.135031
41,Soft-MRS,german_credit,0.656869,0.053348,0.450931,0.059935,less_positive_class,0.1,0.000000,0.000000
42,Uniform,breast_cancer,0.987591,0.006273,0.993799,0.003288,less_positive_class,0.1,0.000000,0.000000
43,KMM,breast_cancer,0.989408,0.005247,0.994803,0.002604,less_positive_class,0.1,0.000000,0.000000
44,PSA,breast_cancer,0.987893,0.006442,0.994015,0.003248,less_positive_class,0.1,0.000000,0.000000
45,MRS,breast_cancer,0.988590,0.005984,0.994571,0.002792,less_positive_class,0.1,53.060000,6.807085
46,FW-MRS,breast_cancer,0.982941,0.010971,0.990870,0.006853,less_positive_class,0.1,41.633333,12.330135
47,FW-MRS$_{SVM}$,breast_cancer,0.978755,0.016294,0.988016,0.010075,less_positive_class,0.1,50.480000,10.568330
48,Soft-MRS,breast_cancer,0.988682,0.005525,0.994384,0.002774,less_positive_class,0.1,0.000000,0.000000
49,Uniform,loan_prediction,0.658389,0.080697,0.794671,0.050524,less_positive_class,0.1,0.000000,0.000000
50,KMM,loan_prediction,0.610365,0.096952,0.776497,0.061962,less_positive_class,0.1,0.000000,0.000000
51,PSA,loan_prediction,0.627560,0.095193,0.780323,0.058087,less_positive_class,0.1,0.000000,0.000000
52,MRS,loan_prediction,0.645463,0.085967,0.791333,0.053357,less_positive_class,0.1,8.120000,5.105448
53,FW-MRS,loan_prediction,0.622750,0.069752,0.783612,0.047470,less_positive_class,0.1,4.566667,4.079897
54,FW-MRS$_{SVM}$,loan_prediction,0.601155,0.079313,0.765509,0.050545,less_positive_class,0.1,4.875000,4.255511
55,Soft-MRS,loan_prediction,0.619324,0.100184,0.779368,0.062878,less_positive_class,0.1,0.000000,0.000000

In [25]:
for bias_type in bias_types:
    print(f"{bias_type}, {0.1}")
    for dataset in data_set_replacer.keys():
        mean_auroc_values = []
        std_auroc_values = []
        for method in result_df["Method"].unique():
            try:
                mean_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==0.1) & 
                                                    (result_df["Data Set"]==dataset)]["AUROC Mean"].iloc[0]
                mean_auroc_values.append(np.round(mean_auroc, 3))

                std_auroc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==0.1) & 
                                                    (result_df["Data Set"]==dataset)]["AUROC Std"].iloc[0]
                std_auroc_values.append(np.round(std_auroc, 2))
            except IndexError:
                mean_auroc_values.append(0)
                std_auroc_values.append(0)

        print(f"{data_set_replacer[dataset]} \
& ${mean_auroc_values[0]}\\pm{std_auroc_values[0]}$ \
& ${mean_auroc_values[1]}\\pm{std_auroc_values[1]}$ \
& ${mean_auroc_values[2]}\\pm{std_auroc_values[2]}$ \
& ${mean_auroc_values[3]}\\pm{std_auroc_values[3]}$ \
& ${mean_auroc_values[4]}\\pm{std_auroc_values[4]}$ \
& ${mean_auroc_values[5]}\\pm{std_auroc_values[5]}$ \
& ${mean_auroc_values[6]}\\pm{std_auroc_values[6]}$ \
\\\\")
    print("\n")

less_positive_class, 0.1
Diabetes & $0.791\pm0.02$ & $0.781\pm0.02$ & $0.787\pm0.02$ & $0.789\pm0.02$ & $0.785\pm0.02$ & $0.787\pm0.03$ & $0.788\pm0.02$ \\
Employment & $0.871\pm0.01$ & $0.857\pm0.01$ & $0.867\pm0.01$ & $0.87\pm0.01$ & $0.87\pm0.01$ & $0.864\pm0.01$ & $0.862\pm0.01$ \\
Income & $0.838\pm0.01$ & $0.82\pm0.01$ & $0.831\pm0.01$ & $0.837\pm0.01$ & $0.837\pm0.01$ & $0.835\pm0.01$ & $0.827\pm0.01$ \\
Bank Marketing & $0.847\pm0.02$ & $0.832\pm0.03$ & $0.839\pm0.03$ & $0.845\pm0.02$ & $0.845\pm0.02$ & $0.84\pm0.02$ & $0.834\pm0.03$ \\
HR Analytic & $0.753\pm0.02$ & $0.749\pm0.02$ & $0.75\pm0.02$ & $0.751\pm0.02$ & $0.751\pm0.03$ & $0.75\pm0.03$ & $0.751\pm0.02$ \\
German Credit & $0.667\pm0.05$ & $0.649\pm0.05$ & $0.659\pm0.06$ & $0.672\pm0.05$ & $0.642\pm0.06$ & $0.637\pm0.06$ & $0.657\pm0.05$ \\
Breast Cancer & $0.988\pm0.01$ & $0.989\pm0.01$ & $0.988\pm0.01$ & $0.989\pm0.01$ & $0.983\pm0.01$ & $0.979\pm0.02$ & $0.989\pm0.01$ \\
Loan & $0.658\pm0.08$ & $0.61\pm0.1$ & $0.628\pm0.1$ & $0.645\pm0.09$ & $0.623\pm0.07$ & $0.601\pm0.08$ & $0.619\pm0.1$ \\

In [32]:
for bias_type in bias_types:
    print(f"{bias_type}, {0.1}")
    for dataset in data_set_replacer.keys():
        mean_auprc_values = []
        std_auprc_values = []
        for method in result_df["Method"].unique():
            try:
                mean_auprc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==0.1) & 
                                                    (result_df["Data Set"]==dataset)]["AUPRC Mean"].iloc[0]
                mean_auprc_values.append(np.round(mean_auprc, 3))

                std_auprc = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==0.1) & 
                                                    (result_df["Data Set"]==dataset)]["AUPRC Std"].iloc[0]
                std_auprc_values.append(np.round(std_auprc, 2))
            except IndexError:
                mean_auprc_values.append(0)
                std_auprc_values.append(0)

        print(f"{data_set_replacer[dataset]} \
& ${mean_auprc_values[0]}\\pm{std_auprc_values[0]}$ \
& ${mean_auprc_values[1]}\\pm{std_auprc_values[1]}$ \
& ${mean_auprc_values[2]}\\pm{std_auprc_values[2]}$ \
& ${mean_auprc_values[3]}\\pm{std_auprc_values[3]}$ \
& ${mean_auprc_values[4]}\\pm{std_auprc_values[4]}$ \
& ${mean_auprc_values[5]}\\pm{std_auprc_values[5]}$ \
& ${mean_auprc_values[6]}\\pm{std_auprc_values[6]}$ \
& \\\\")
print("\n")

less_positive_class, 0.1
Diabetes & $0.371\pm0.04$ & $0.357\pm0.04$ & $0.367\pm0.04$ & $0.367\pm0.04$ & $0.359\pm0.04$ & $0.359\pm0.04$ & $0.368\pm0.04$ & \\
Employment & $0.827\pm0.02$ & $0.809\pm0.02$ & $0.824\pm0.02$ & $0.826\pm0.02$ & $0.824\pm0.02$ & $0.817\pm0.02$ & $0.818\pm0.02$ & \\
Income & $0.789\pm0.02$ & $0.765\pm0.02$ & $0.781\pm0.02$ & $0.788\pm0.02$ & $0.789\pm0.02$ & $0.788\pm0.02$ & $0.774\pm0.02$ & \\
Bank Marketing & $0.466\pm0.05$ & $0.446\pm0.06$ & $0.455\pm0.05$ & $0.468\pm0.05$ & $0.456\pm0.06$ & $0.44\pm0.05$ & $0.447\pm0.05$ & \\
HR Analytic & $0.455\pm0.03$ & $0.449\pm0.03$ & $0.454\pm0.03$ & $0.456\pm0.03$ & $0.451\pm0.04$ & $0.448\pm0.04$ & $0.454\pm0.04$ & \\
German Credit & $0.461\pm0.06$ & $0.443\pm0.06$ & $0.452\pm0.06$ & $0.464\pm0.07$ & $0.441\pm0.07$ & $0.441\pm0.08$ & $0.451\pm0.06$ & \\
Breast Cancer & $0.994\pm0.0$ & $0.995\pm0.0$ & $0.994\pm0.0$ & $0.995\pm0.0$ & $0.991\pm0.01$ & $0.988\pm0.01$ & $0.994\pm0.0$ & \\
Loan & $0.795\pm0.05$ & $0.776\pm0.06$ & $0.78\pm0.06$ & $0.791\pm0.05$ & $0.784\pm0.05$ & $0.766\pm0.05$ & $0.779\pm0.06$ & \\

In [27]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_pad_values = []
            std_pad_values = []
            for method in result_df["Method"].unique():
                try:
                    mean_pad = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["SVM PAD Mean"].iloc[0]
                    mean_pad_values.append(np.round(mean_pad, 3))

                    std_pad = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["SVM PAD Std"].iloc[0]
                    std_pad_values.append(np.round(std_pad, 2))
                except IndexError:
                    mean_pad_values.append(0)
                    std_pad_values.append(0)

            print(f"{data_set_replacer[dataset]} \
& ${mean_pad_values[0]}\\pm{std_pad_values[0]}$ \
& ${mean_pad_values[1]}\\pm{std_pad_values[1]}$ \
& ${mean_pad_values[2]}\\pm{std_pad_values[2]}$ \
& ${mean_pad_values[3]}\\pm{std_pad_values[3]}$ \
& ${mean_pad_values[4]}\\pm{std_pad_values[4]}$ \
& ${mean_pad_values[5]}\\pm{std_pad_values[5]}$ \
& \\\\")
        print("\n")

less_positive_class, 0.1

KeyError: 'SVM PAD Mean'

In [ ]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_domain_values = []
            std_domain_values = []
            for method in result_df["Method"].unique():
                try:
                    mean_domain = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["RF Domain AUROC Mean"].iloc[0]
                    mean_domain_values.append(np.round(mean_domain, 3))

                    std_domain = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                        (result_df["Bias Strength"]==bias_strength) & 
                                                        (result_df["Data Set"]==dataset)]["RF Domain AUROC Std"].iloc[0]
                    std_domain_values.append(np.round(std_domain, 2))
                except IndexError:
                    mean_domain_values.append(0)
                    std_domain_values.append(0)

            print(f"{data_set_replacer[dataset]} \
& ${mean_domain_values[0]}\\pm{std_domain_values[0]}$ \
& ${mean_domain_values[1]}\\pm{std_domain_values[1]}$ \
& ${mean_domain_values[2]}\\pm{std_domain_values[2]}$ \
& ${mean_domain_values[3]}\\pm{std_domain_values[3]}$ \
& ${mean_domain_values[4]}\\pm{std_domain_values[4]}$ \
& ${mean_domain_values[5]}\\pm{std_domain_values[5]}$ \
& \\\\")
        print("\n")

less_positive_class, 0.1
Employment & $0.63\pm0.01$ & $0.525\pm0.01$ & $0.528\pm0.01$ & $0.581\pm0.03$ & $0.54\pm0.03$ & $0.553\pm0.01$ & \\
Income & $0.613\pm0.01$ & $0.528\pm0.01$ & $0.519\pm0.01$ & $0.564\pm0.03$ & $0.557\pm0.03$ & $0.568\pm0.02$ & \\
Breast Cancer & $0.731\pm0.02$ & $0.592\pm0.03$ & $0.583\pm0.03$ & $0.65\pm0.03$ & $0.666\pm0.03$ & $0.675\pm0.05$ & \\
HR Analytic & $0.533\pm0.01$ & $0.514\pm0.01$ & $0.511\pm0.0$ & $0.526\pm0.01$ & $0.526\pm0.01$ & $0.524\pm0.01$ & \\
Loan & $0.57\pm0.03$ & $0.585\pm0.02$ & $0.554\pm0.02$ & $0.554\pm0.02$ & $0.553\pm0.01$ & $0.549\pm0.02$ & \\
Diabetes & $0.525\pm0.01$ & $0.522\pm0.01$ & $0.512\pm0.0$ & $0.52\pm0.01$ & $0.52\pm0.01$ & $0.517\pm0.01$ & \\
German Credit & $0.538\pm0.02$ & $0.547\pm0.02$ & $0.533\pm0.01$ & $0.533\pm0.01$ & $0.529\pm0.01$ & $0.531\pm0.01$ & \\
Bank Marketing & $0.523\pm0.01$ & $0.521\pm0.01$ & $0.512\pm0.0$ & $0.517\pm0.01$ & $0.517\pm0.01$ & $0.517\pm0.01$ & \\

In [ ]:
result_df.round(3)

,Method,Data Set,AUROC Mean,AUROC Std,AUPRC Mean,AUPRC Std,Bias Type,Bias Strength,Dropped Samples Mean,Dropped Samples Std,SVM PAD Mean,SVM PAD Std,RF Domain AUROC Mean,RF Domain AUROC Std
0,Uniform,folktables_employment,0.871,0.010,0.827,0.017,less_positive_class,0.1,0.000,0.000,0.357,0.037,0.630,0.010
1,KMM,folktables_employment,0.857,0.014,0.809,0.022,less_positive_class,0.1,0.000,0.000,0.099,0.023,0.525,0.009
2,PSA,folktables_employment,0.867,0.011,0.824,0.017,less_positive_class,0.1,0.040,0.280,0.042,0.012,0.528,0.010
3,MRS,folktables_employment,0.870,0.010,0.825,0.017,less_positive_class,0.1,270.300,99.922,0.226,0.090,0.581,0.031
4,FW-MRS,folktables_employment,0.864,0.012,0.819,0.018,less_positive_class,0.1,381.786,82.735,0.114,0.071,0.540,0.026
5,FW-MRS$_{SVM}$,folktables_employment,0.835,0.016,0.776,0.027,less_positive_class,0.1,271.200,29.267,0.100,0.037,0.553,0.014
6,Uniform,folktables_income,0.838,0.013,0.789,0.020,less_positive_class,0.1,0.000,0.000,0.353,0.041,0.613,0.014
7,KMM,folktables_income,0.820,0.014,0.765,0.020,less_positive_class,0.1,0.000,0.000,0.093,0.026,0.528,0.007
8,PSA,folktables_income,0.831,0.014,0.781,0.022,less_positive_class,0.1,0.160,0.703,0.045,0.014,0.519,0.008
9,MRS,folktables_income,0.837,0.013,0.787,0.019,less_positive_class,0.1,266.000,83.970,0.218,0.089,0.564,0.029
10,FW-MRS,folktables_income,0.835,0.013,0.789,0.019,less_positive_class,0.1,270.833,88.745,0.185,0.077,0.557,0.028
11,FW-MRS$_{SVM}$,folktables_income,0.827,0.016,0.779,0.020,less_positive_class,0.1,285.357,29.457,0.118,0.043,0.568,0.015
12,Uniform,breast_cancer,0.988,0.006,0.994,0.003,less_positive_class,0.1,0.000,0.000,0.934,0.049,0.731,0.018
13,KMM,breast_cancer,0.989,0.005,0.995,0.003,less_positive_class,0.1,0.000,0.000,0.142,0.048,0.592,0.029
14,PSA,breast_cancer,0.988,0.006,0.994,0.003,less_positive_class,0.1,0.000,0.000,0.370,0.087,0.583,0.028
15,MRS,breast_cancer,0.989,0.006,0.995,0.003,less_positive_class,0.1,53.060,6.807,0.672,0.088,0.650,0.029
16,FW-MRS,breast_cancer,0.983,0.012,0.991,0.007,less_positive_class,0.1,38.067,11.147,0.548,0.191,0.666,0.034
17,FW-MRS$_{SVM}$,breast_cancer,0.978,0.010,0.987,0.008,less_positive_class,0.1,51.460,10.048,0.344,0.129,0.675,0.049
18,Uniform,hr_analytics,0.753,0.018,0.455,0.029,less_positive_class,0.1,0.000,0.000,0.104,0.028,0.533,0.009
19,KMM,hr_analytics,0.749,0.019,0.449,0.032,less_positive_class,0.1,0.000,0.000,0.036,0.012,0.514,0.005
20,PSA,hr_analytics,0.750,0.019,0.454,0.034,less_positive_class,0.1,0.000,0.000,0.035,0.013,0.511,0.005
21,MRS,hr_analytics,0.751,0.019,0.456,0.030,less_positive_class,0.1,107.400,53.631,0.086,0.024,0.526,0.008
22,FW-MRS,hr_analytics,0.754,0.020,0.454,0.034,less_positive_class,0.1,94.722,51.706,0.085,0.028,0.526,0.007
23,FW-MRS$_{SVM}$,hr_analytics,0.749,0.023,0.451,0.043,less_positive_class,0.1,179.828,73.537,0.076,0.031,0.524,0.008
24,Uniform,loan_prediction,0.658,0.081,0.795,0.051,less_positive_class,0.1,0.000,0.000,0.350,0.107,0.570,0.030
25,KMM,loan_prediction,0.610,0.097,0.776,0.062,less_positive_class,0.1,0.000,0.000,0.246,0.061,0.585,0.024
26,PSA,loan_prediction,0.628,0.095,0.780,0.058,less_positive_class,0.1,0.000,0.000,0.172,0.055,0.554,0.021
27,MRS,loan_prediction,0.645,0.086,0.791,0.053,less_positive_class,0.1,8.120,5.105,0.286,0.102,0.554,0.019
28,FW-MRS,loan_prediction,0.610,0.094,0.770,0.062,less_positive_class,0.1,3.340,3.637,0.246,0.099,0.553,0.015
29,FW-MRS$_{SVM}$,loan_prediction,0.547,0.083,0.737,0.057,less_positive_class,0.1,3.260,4.467,0.200,0.095,0.549,0.015
30,Uniform,diabetes,0.791,0.022,0.371,0.038,less_positive_class,0.1,0.000,0.000,0.106,0.035,0.525,0.009
31,KMM,diabetes,0.781,0.022,0.357,0.042,less_positive_class,0.1,0.000,0.000,0.044,0.012,0.522,0.008
32,PSA,diabetes,0.787,0.023,0.367,0.037,less_positive_class,0.1,0.000,0.000,0.037,0.010,0.512,0.004
33,MRS,diabetes,0.789,0.023,0.367,0.040,less_positive_class,0.1,49.900,32.117,0.088,0.034,0.520,0.009
34,FW-MRS,diabetes,0.787,0.020,0.362,0.035,less_positive_class,0.1,36.667,28.424,0.093,0.029,0.520,0.008
35,FW-MRS$_{SVM}$,diabetes,0.790,0.024,0.368,0.038,less_positive_class,0.1,83.056,31.848,0.074,0.028,0.517,0.006
36,Uniform,german_credit,0.667,0.054,0.461,0.064,less_positive_class,0.1,0.000,0.000,0.158,0.068,0.538,0.016
37,KMM,german_credit,0.649,0.053,0.443,0.062,less_positive_class,0.1,0.000,0.000,0.116,0.041,0.547,0.015
38,PSA,german_credit,0.659,0.055,0.452,0.064,less_positive_class,0.1,0.000,0.000,0.090,0.026,0.533,0.009
39,MRS,german_credit,0.672,0.052,0.464,0.066,less_positive_class,0.1,13.600,10.585,0.134,0.056,0.533,0.012
40,FW-MRS,german_credit,0.641,0.061,0.433,0.067,less_positive_class,0.1,9.000,11.091,0.115,0.058,0.529,0.010
41,FW-MRS$_{SVM}$,german_credit,0.622,0.069,0.415,0.065,less_positive_class,0.1,12.021,13.553,0.113,0.055,0.531,0.012
42,Uniform,bank_marketing,0.847,0.021,0.466,0.052,less_positive_class,0.1,0.000,0.000,0.080,0.032,0.523,0.009
43,KMM,bank_marketing,0.832,0.026,0.446,0.058,less_positive_class,0.1,0.000,0.000,0.063,0.022,0.521,0.007
44,PSA,bank_marketing,0.839,0.026,0.455,0.049,less_positive_class,0.1,0.000,0.000,0.037,0.011,0.512,0.004
45,MRS,bank_marketing,0.845,0.022,0.468,0.052,less_positive_class,0.1,62.900,34.031,0.066,0.024,0.517,0.007
46,FW-MRS,bank_marketing,0.846,0.013,0.457,0.050,less_positive_class,0.1,67.619,24.232,0.061,0.020,0.517,0.007
47,FW-MRS$_{SVM}$,bank_marketing,0.835,0.025,0.441,0.053,less_positive_class,0.1,58.939,28.063,0.058,0.023,0.517,0.005

In [ ]:
result_df["Rank AUROC"] = result_df.round(3).groupby("Data Set")["AUROC Mean"].rank(ascending=False)
result_df["Rank AUPRC"] = result_df.round(3).groupby("Data Set")["AUPRC Mean"].rank(ascending=False)
result_df["Rank PAD"] = result_df.round(3).groupby("Data Set")["SVM PAD Mean"].rank(ascending=True)
result_df["Rank Domain"] = result_df.round(3).groupby("Data Set")["RF Domain AUROC Mean"].rank(ascending=True)
result_df[["Method", "Rank AUROC", "Rank AUPRC", "Rank PAD", "Rank Domain"]].groupby("Method").mean()

                Rank AUROC  Rank AUPRC  Rank PAD  Rank Domain
Method
FW-MRS              3.6250      4.0000    3.8125        3.000
FW-MRS$_{SVM}$      5.1875      5.2500    2.5000        3.125
KMM                 4.8125      4.6875    2.5625        3.625
MRS                 2.1875      1.8750    4.8750        3.750
PSA                 3.6250      3.4375    1.2500        1.750
Uniform             1.5625      1.7500    6.0000        5.750