In [39]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [40]:
result_path = Path("../thesis_results/decomposition")
methods_list = ["uniform","psa", "kmm", "mrs-forest", "fw-mrs-temperature",  "fw-mrs-temperature-svm", "soft-mrs-exponential"]
# bias_types = ["less_negative_class", "less_positive_class", "mean_difference"]
bias_types = ["less_negative_class"]
less_bias_strengths = ["0.1"]
mean_bias_strengthts = ["0.8"]
datasets = ["folktables_employment", "folktables_income", "hr_analytics", "breast_cancer", "loan_prediction"]

In [41]:
aurocs = []
auprcs = []
dict_list = []
for dataset in datasets:
    for bias_type in bias_types:
        for method in methods_list:
            if bias_type == "mean_difference":
                bias_strengths = mean_bias_strengthts
            else : 
                bias_strengths = less_bias_strengths
            for bias_strength in bias_strengths:
                json_file = result_path / dataset / bias_type /  bias_strength/ method / "bias_variance_decomposition.json"
                result_file = pd.read_json(str(json_file))
                dict_list.append(
                    {
                        "Method": method, "Data Set": dataset, 
                        "0-1 Bias": result_file["0-1 loss"]["average_bias"], 
                        "0-1 Variance": result_file["0-1 loss"]["average variance"], 
                        "0-1 Expexted Loss": result_file["0-1 loss"]["average expected loss"],
                        "MSE Bias": result_file["mse loss"]["average_bias"], 
                        "MSE Variance": result_file["mse loss"]["average variance"], 
                        "MSE Expexted Loss": result_file["mse loss"]["average expected loss"],
                        "Bias Type": bias_type, "Bias Strength": bias_strength,
                    }
                                )
result_df = pd.DataFrame(data=dict_list)

In [42]:
result_df = result_df.replace({"uniform": "Uniform", "kmm": "KMM", "psa": "PSA", "mrs-forest": "MRS",
                               "soft-mrs-linear": "Soft-MRS-Linear", "soft-mrs-exponential": "Soft-MRS-Exponential",
                               "fw-mrs-temperature-svm": "FW-MRS-SVM", "fw-mrs-temperature": "FW-MRS-RF"})
result_df

,Method,Data Set,0-1 Bias,0-1 Variance,0-1 Expexted Loss,MSE Bias,MSE Variance,MSE Expexted Loss,Bias Type,Bias Strength
0,Uniform,folktables_employment,0.341000,0.022610,0.334870,0.243566,0.005372,0.248938,less_negative_class,0.1
1,PSA,folktables_employment,0.338000,0.022350,0.332230,0.238597,0.004943,0.243540,less_negative_class,0.1
2,KMM,folktables_employment,0.337000,0.024290,0.329890,0.235516,0.006129,0.241645,less_negative_class,0.1
3,MRS,folktables_employment,0.338000,0.025950,0.330030,0.238875,0.005740,0.244615,less_negative_class,0.1
4,FW-MRS-RF,folktables_employment,0.355500,0.017740,0.352400,0.268735,0.006227,0.274962,less_negative_class,0.1
5,FW-MRS-SVM,folktables_employment,0.353000,0.018890,0.344550,0.259097,0.006980,0.266077,less_negative_class,0.1
6,Soft-MRS-Exponential,folktables_employment,0.335500,0.022030,0.331910,0.241198,0.004898,0.246096,less_negative_class,0.1
7,Uniform,folktables_income,0.458000,0.038910,0.446530,0.295579,0.006084,0.301663,less_negative_class,0.1
8,PSA,folktables_income,0.447500,0.033910,0.439210,0.285464,0.005229,0.290693,less_negative_class,0.1
9,KMM,folktables_income,0.445500,0.040880,0.437400,0.281531,0.006398,0.287929,less_negative_class,0.1
10,MRS,folktables_income,0.451000,0.051440,0.432660,0.282702,0.008025,0.290728,less_negative_class,0.1
11,FW-MRS-RF,folktables_income,0.488500,0.049120,0.488420,0.324463,0.008953,0.333416,less_negative_class,0.1
12,FW-MRS-SVM,folktables_income,0.481000,0.067310,0.479130,0.316887,0.013889,0.330776,less_negative_class,0.1
13,Soft-MRS-Exponential,folktables_income,0.446500,0.033780,0.438620,0.285069,0.005447,0.290516,less_negative_class,0.1
14,Uniform,hr_analytics,0.372529,0.249514,0.437749,0.249502,0.008943,0.258445,less_negative_class,0.1
15,PSA,hr_analytics,0.364824,0.230338,0.422995,0.242372,0.009207,0.251579,less_negative_class,0.1
16,KMM,hr_analytics,0.329648,0.222982,0.410171,0.239681,0.009862,0.249543,less_negative_class,0.1
17,MRS,hr_analytics,0.390620,0.233474,0.441554,0.253890,0.007435,0.261324,less_negative_class,0.1
18,FW-MRS-RF,hr_analytics,0.831156,0.098164,0.754459,0.355739,0.007693,0.363432,less_negative_class,0.1
19,FW-MRS-SVM,hr_analytics,0.782915,0.166714,0.690305,0.335853,0.009995,0.345849,less_negative_class,0.1
20,Soft-MRS-Exponential,hr_analytics,0.354439,0.219886,0.419578,0.241813,0.008705,0.250518,less_negative_class,0.1
21,Uniform,breast_cancer,0.087719,0.052368,0.102368,0.062548,0.006940,0.069488,less_negative_class,0.1
22,PSA,breast_cancer,0.083333,0.049474,0.096491,0.059329,0.006754,0.066083,less_negative_class,0.1
23,KMM,breast_cancer,0.078947,0.051842,0.093070,0.058483,0.006006,0.064489,less_negative_class,0.1
24,MRS,breast_cancer,0.078947,0.051579,0.093158,0.058253,0.006663,0.064916,less_negative_class,0.1
25,FW-MRS-RF,breast_cancer,0.092105,0.074474,0.118158,0.067857,0.013815,0.081672,less_negative_class,0.1
26,FW-MRS-SVM,breast_cancer,0.096491,0.079035,0.118333,0.065256,0.016966,0.082222,less_negative_class,0.1
27,Soft-MRS-Exponential,breast_cancer,0.083333,0.051579,0.094737,0.057252,0.007266,0.064518,less_negative_class,0.1
28,Uniform,loan_prediction,0.306250,0.003625,0.303375,0.246902,0.004104,0.251006,less_negative_class,0.1
29,PSA,loan_prediction,0.306250,0.003750,0.303500,0.246208,0.004226,0.250434,less_negative_class,0.1
30,KMM,loan_prediction,0.306250,0.002500,0.305000,0.250978,0.003694,0.254672,less_negative_class,0.1
31,MRS,loan_prediction,0.306250,0.003000,0.303750,0.249112,0.003768,0.252880,less_negative_class,0.1
32,FW-MRS-RF,loan_prediction,0.306250,0.013000,0.301500,0.247245,0.010198,0.257444,less_negative_class,0.1
33,FW-MRS-SVM,loan_prediction,0.306250,0.001625,0.305625,0.267384,0.004019,0.271403,less_negative_class,0.1
34,Soft-MRS-Exponential,loan_prediction,0.306250,0.003250,0.304000,0.249993,0.003957,0.253950,less_negative_class,0.1

In [43]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            bias_01_values = []
            for dataset in datasets:
                bias_01 = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["0-1 Bias"].iloc[0]
                bias_01_values.append(round(bias_01, 4))


            print(f"\t& {method} & {bias_01_values[0]} & {bias_01_values[1]} & {bias_01_values[2]} & {bias_01_values[3]} & {bias_01_values[4]} & \\\\")
        print("\n")

less_negative_class, 0.1
	& Uniform & 0.341 & 0.458 & 0.3725 & 0.0877 & 0.3062 & \\
	& PSA & 0.338 & 0.4475 & 0.3648 & 0.0833 & 0.3062 & \\
	& KMM & 0.337 & 0.4455 & 0.3296 & 0.0789 & 0.3062 & \\
	& MRS & 0.338 & 0.451 & 0.3906 & 0.0789 & 0.3062 & \\
	& FW-MRS-RF & 0.3555 & 0.4885 & 0.8312 & 0.0921 & 0.3062 & \\
	& FW-MRS-SVM & 0.353 & 0.481 & 0.7829 & 0.0965 & 0.3062 & \\
	& Soft-MRS-Exponential & 0.3355 & 0.4465 & 0.3544 & 0.0833 & 0.3062 & \\

In [44]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for method in result_df["Method"].unique():
            variance_01_values = []
            for dataset in datasets:
                variance_01 = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["0-1 Variance"].iloc[0]
                variance_01_values.append(np.round(variance_01, 4))

            print(f"\t& {method} & {variance_01_values[0]} & {variance_01_values[1]} & {variance_01_values[2]} & {variance_01_values[3]} & \
{variance_01_values[4]} & \\\\")
        print("\n")

less_negative_class, 0.1
	& Uniform & 0.0226 & 0.0389 & 0.2495 & 0.0524 & 0.0036 & \\
	& PSA & 0.0224 & 0.0339 & 0.2303 & 0.0495 & 0.0038 & \\
	& KMM & 0.0243 & 0.0409 & 0.223 & 0.0518 & 0.0025 & \\
	& MRS & 0.026 & 0.0514 & 0.2335 & 0.0516 & 0.003 & \\
	& FW-MRS-RF & 0.0177 & 0.0491 & 0.0982 & 0.0745 & 0.013 & \\
	& FW-MRS-SVM & 0.0189 & 0.0673 & 0.1667 & 0.079 & 0.0016 & \\
	& Soft-MRS-Exponential & 0.022 & 0.0338 & 0.2199 & 0.0516 & 0.0032 & \\

In [45]:
result_df["Rank Bias"] = result_df.groupby("Data Set")["0-1 Bias"].rank(ascending=True)
result_df["Rank Variance"] = result_df.groupby("Data Set")["0-1 Variance"].rank(ascending=True)
result_df[["Method", "Rank Bias", "Rank Variance"]].groupby("Method").mean()

                      Rank Bias  Rank Variance
Method
FW-MRS-RF                   6.2            4.0
FW-MRS-SVM                  5.8            3.8
KMM                         1.9            4.0
MRS                         3.6            4.9
PSA                         3.4            3.6
Soft-MRS-Exponential        2.5            2.7
Uniform                     4.6            5.0